---
title: "20240507_pharate_axonal_branching"
author: "John Santiago"
date: "2024-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = F}

ab = read.csv("https://raw.githubusercontent.com/johncsantiago/WhartonLab/master/20240507_pharate_axonal_branching_Raw_Data.csv", header = T)

morph = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/20240513_pharate_axonal_morphology_Raw_Data.csv")

ab = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/UB7 - G85R Pharate Leg Axonal Branching & Mitochondria  - CSV_Branching.csv", header = T)

```


```{r echo = F}

plotdata = data.frame(x = paste(ab$Genotype, ab$Sex),
                      y = ab$X.Primary,
                      color = as.numeric(factor(ab$Genotype)))
plotdata = plotdata[order(ab$Sex),]
plotdata$x = factor(plotdata$x, levels = c(unique(plotdata$x)))
boxplot(plotdata$y~plotdata$x, xlab="",     
        main= "",ylab="Number of Primary Branches", las = 2, cex.axis = .8)
points(x=as.numeric(factor(plotdata$x)),
       y=plotdata$y,
       cex=1,
       pch=21,
       bg=c('firebrick',"gold","darkgreen","dodgerblue")[plotdata$color])

```




```{r echo = F}

plotdata = data.frame(x = paste(ab$Genotype, paste(ab$Sex, ab$Leg.Location)),
                      y = ab$X.Primary,
                      color = as.numeric(factor(ab$Genotype)))
plotdata = plotdata[order(paste0(ab$Sex, paste0(ab$Leg.Location, ab$Genotype))),]
plotdata$x = factor(plotdata$x, levels = c(unique(plotdata$x)))

par(mar = c(8,5,2,2))
boxplot(plotdata$y~plotdata$x, xlab="",     
        main= "",ylab="Number of Primary Branches", las = 2, cex.axis = .8)
points(x=as.numeric(factor(plotdata$x)),
       y=plotdata$y,
       cex=1,
       pch=21,
       bg=c('firebrick',"gold","darkgreen","dodgerblue")[plotdata$color])

```




```{r echo = F}

plotdata = data.frame(x = paste(ab$Genotype, ab$Sex),
                      y = ab$Avg.Mito.Branch.Length,
                      color = as.numeric(factor(ab$Genotype)))
plotdata = plotdata[order(ab$Sex),]
plotdata$x = factor(plotdata$x, levels = c(unique(plotdata$x)))
boxplot(plotdata$y~plotdata$x, xlab="",     
        main= "",ylab="Average Mitochondria", las = 2, cex.axis = .8)
points(x=as.numeric(factor(plotdata$x)),
       y=plotdata$y,
       cex=1,
       pch=21,
       bg=c('firebrick',"gold","darkgreen","dodgerblue")[plotdata$color])

```



```{r echo = F}

plotdata = data.frame(x = paste(ab$Genotype, paste(ab$Sex, ab$Leg.Location)),
                      y = ab$Avg.Mito.Branch.Length,
                      color = as.numeric(factor(ab$Genotype)))
plotdata = plotdata[order(paste0(ab$Sex, paste0(ab$Leg.Location, ab$Genotype))),]
plotdata$x = factor(plotdata$x, levels = c(unique(plotdata$x)))

par(mar = c(8,5,2,2))
boxplot(plotdata$y~plotdata$x, xlab="",     
        main= "",ylab="Average Mitochondria", las = 2, cex.axis = .8)
points(x=as.numeric(factor(plotdata$x)),
       y=plotdata$y,
       cex=1,
       pch=21,
       bg=c('firebrick',"gold","darkgreen","dodgerblue")[plotdata$color])

```






```{r echo = F}

plotdata = data.frame(x = paste(ab$Genotype, ab$Sex),
                      y = ab$Longest.Primary.Branch..um.,
                      color = as.numeric(factor(ab$Genotype)))
plotdata = plotdata[order(ab$Sex),]
plotdata$x = factor(plotdata$x, levels = c(unique(plotdata$x)))
boxplot(plotdata$y~plotdata$x, xlab="",     
        main= "",ylab="Longest Primary Branch", las = 2, cex.axis = .8)
points(x=as.numeric(factor(plotdata$x)),
       y=plotdata$y,
       cex=1,
       pch=21,
       bg=c('firebrick',"gold","darkgreen","dodgerblue")[plotdata$color])

```



```{r echo = F}

plotdata = data.frame(x = paste(ab$Genotype, paste(ab$Sex, ab$Leg.Location)),
                      y = ab$Longest.Primary.Branch..um.,
                      color = as.numeric(factor(ab$Genotype)))
plotdata = plotdata[order(paste0(ab$Sex, paste0(ab$Leg.Location, ab$Genotype))),]
plotdata$x = factor(plotdata$x, levels = c(unique(plotdata$x)))

par(mar = c(8,5,2,2))
boxplot(plotdata$y~plotdata$x, xlab="",     
        main= "",ylab="Longest Primary Branch", las = 2, cex.axis = .8)
points(x=as.numeric(factor(plotdata$x)),
       y=plotdata$y,
       cex=1,
       pch=21,
       bg=c('firebrick',"gold","darkgreen","dodgerblue")[plotdata$color])

```






```{r echo = F}

plotdata = data.frame(x = paste(ab$Genotype, ab$Sex),
                      y = ab$Shortest.Primary.Branch..um.,
                      color = as.numeric(factor(ab$Genotype)))
plotdata = plotdata[order(ab$Sex),]
plotdata$x = factor(plotdata$x, levels = c(unique(plotdata$x)))
boxplot(plotdata$y~plotdata$x, xlab="",     
        main= "",ylab="Shortest Primary Branch", las = 2, cex.axis = .8)
points(x=as.numeric(factor(plotdata$x)),
       y=plotdata$y,
       cex=1,
       pch=21,
       bg=c('firebrick',"gold","darkgreen","dodgerblue")[plotdata$color])

```



```{r echo = F}

plotdata = data.frame(x = paste(ab$Genotype, paste(ab$Sex, ab$Leg.Location)),
                      y = ab$Shortest.Primary.Branch..um.,
                      color = as.numeric(factor(ab$Genotype)))
plotdata = plotdata[order(paste0(ab$Sex, paste0(ab$Leg.Location, ab$Genotype))),]
plotdata$x = factor(plotdata$x, levels = c(unique(plotdata$x)))

par(mar = c(8,5,2,2))
boxplot(plotdata$y~plotdata$x, xlab="",     
        main= "",ylab="Shortest Primary Branch", las = 2, cex.axis = .8)
points(x=as.numeric(factor(plotdata$x)),
       y=plotdata$y,
       cex=1,
       pch=21,
       bg=c('firebrick',"gold","darkgreen","dodgerblue")[plotdata$color])

```

