---
title: "Anton Tau activity assay"
author: "John Santiago"
date: "2025-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r echo = F, fig.height=7, fig.width= 7}
library(kableExtra)
library(beeswarm)


mm.per.pix = setNames(c(146/1035, 146/1030,
                        146/1030, 146/1030,
                        146/1030, 146/1025), 
                      c("TauWTD1", "TauWTD14",
                        "TauR406WD1", "TauR406WD14", 
                        "LacZD1", "LacZD14"))

fps = 30

speed.conversion = mm.per.pix*fps

temp = read.csv("/Users/johncsantiago/Documents/GitHub/Python/LarvalLocomotion/PreliminaryCode/5106_TauWT_D1_mask_median_improved.csv")

colnames(temp)[2:4] = c("ObjectID", "X", "Y")

title = "TauWT D1"


max.frame = setNames(rep(0, length(unique(temp$ObjectID))), unique(temp$ObjectID))
max.frame = c(max(temp$Frame[temp$ObjectID == 1]),
              max(temp$Frame[temp$ObjectID == 2]),
              max(temp$Frame[temp$ObjectID == 3]),
              max(temp$Frame[temp$ObjectID == 4]),
              max(temp$Frame[temp$ObjectID == 5]))


temp = temp[(temp$ObjectID == 1 & temp$Frame <= max.frame[1]) |
              (temp$ObjectID == 2 & temp$Frame <= max.frame[2]) |
              (temp$ObjectID == 3 & temp$Frame <= max.frame[3]) |
              (temp$ObjectID == 4 & temp$Frame <= max.frame[4]) |
              (temp$ObjectID == 5 & temp$Frame <= max.frame[5]),]

distance = setNames(rep(0, length(unique(temp$ObjectID))), unique(temp$ObjectID))

temp$Y = 1400 - temp$Y
temp$X = temp$X

x = temp$X
y = temp$Y

temp$X = x
temp$Y = y

i=1
while(i<=length(unique(names(distance)))){
  j = 101
  while(j < max.frame[i]){
    x1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "X"]
    x2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "X"]
    y1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "Y"]
    y2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "Y"]
    distance[i] = distance[i] + sqrt((x2-x1)^2 + (y2-y1)^2)
    j=j+100
  }
  i=i+1
}



speed = distance/max.frame

distance = distance*mm.per.pix["TauWTD1"]
speed = speed * speed.conversion["TauWTD1"]


TauWTD1.dist = distance
TauWTD1.speed = speed

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")


lines(x = temp$X[temp$ObjectID ==2],
     y = temp$Y[temp$ObjectID ==2],
     lwd = 1,
     col = "firebrick")

lines(x = temp$X[temp$ObjectID ==3],
     y = temp$Y[temp$ObjectID ==3],
     lwd = 1,
     col = "royalblue")

lines(x = temp$X[temp$ObjectID ==4],
     y = temp$Y[temp$ObjectID ==4],
     lwd = 1,
     col = "darkgreen")

lines(x = temp$X[temp$ObjectID ==5],
     y = temp$Y[temp$ObjectID ==5],
     lwd = 1,
     col = "violetred")

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3)), 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred'),
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")

```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 1

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 2

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")

```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 3

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")

```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 4

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```



```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 5

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```



```{r echo = F, fig.height=7, fig.width= 7}


frame.distance = data.frame(Rep = c(rep("1", ((floor(max.frame[1]/100)))),
                                 rep("2", ((floor(max.frame[2]/100)))),
                                 rep("3", ((floor(max.frame[3]/100)))),
                                 rep("4", ((floor(max.frame[4]/100)))),
                                 rep("5", ((floor(max.frame[5]/100))))),
                      frame = c(100*(1:floor(max.frame[1]/100)-1),
                                100*(1:floor(max.frame[2]/100)-1),
                                100*(1:floor(max.frame[3]/100)-1),
                                100*(1:floor(max.frame[4]/100)-1),
                                100*(1:floor(max.frame[5]/100)-1)),
                        distance = c(0))


i=1
while(i<=length(unique(names(distance)))){
  temp.distance = 0
  j = 200
  while(j-100 < max.frame[i]){
    x1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "X"]
    x2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "X"]
    y1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "Y"]
    y2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "Y"]
    temp.distance = temp.distance + sqrt((x2-x1)^2 + (y2-y1)^2)
    frame.distance[frame.distance$Rep == names(distance)[i] &
                     frame.distance$frame == j-100, "distance"]= temp.distance
    j=j+100
  }
  i=i+1
}

frame.distance$distance = frame.distance$distance*mm.per.pix["TauWTD1"]

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,3500), xlim = c(0,9800),
     xlab = "Frame",
     ylab = "Distance (mm)")

lines(x = frame.distance$frame[frame.distance$Rep ==1],
     y = frame.distance$distance[frame.distance$Rep ==1],
     lwd = 1,
     col = "darkorange")


lines(x = frame.distance$frame[frame.distance$Rep ==2],
     y = frame.distance$distance[frame.distance$Rep ==2],
     lwd = 1,
     col = "firebrick")

lines(x = frame.distance$frame[frame.distance$Rep ==3],
     y = frame.distance$distance[frame.distance$Rep ==3],
     lwd = 1,
     col = "royalblue")

lines(x = frame.distance$frame[frame.distance$Rep ==4],
     y = frame.distance$distance[frame.distance$Rep ==4],
     lwd = 1,
     col = "darkgreen")

lines(x = frame.distance$frame[frame.distance$Rep ==5],
     y = frame.distance$distance[frame.distance$Rep ==5],
     lwd = 1,
     col = "violetred")

legend(x = 10200,
       y = 3500,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3)), 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred'),
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm")
       


```



```{r echo = F, fig.height=7, fig.width= 7}

temp = read.csv("/Users/johncsantiago/Documents/GitHub/Python/LarvalLocomotion/PreliminaryCode/5106 Tau WT D14_mask_median_output_improved.csv")

colnames(temp)[2:4] = c("ObjectID", "X", "Y")

title = "Tau WT D14"


max.frame = setNames(rep(0, length(unique(temp$ObjectID))), unique(temp$ObjectID))
max.frame = c(max(temp$Frame[temp$ObjectID == 1]),
              max(temp$Frame[temp$ObjectID == 2]),
              max(temp$Frame[temp$ObjectID == 3]),
              max(temp$Frame[temp$ObjectID == 4]))


temp = temp[(temp$ObjectID == 1 & temp$Frame <= max.frame[1]) |
              (temp$ObjectID == 2 & temp$Frame <= max.frame[2]) |
              (temp$ObjectID == 3 & temp$Frame <= max.frame[3]) |
              (temp$ObjectID == 4 & temp$Frame <= max.frame[4]),]

distance = setNames(rep(0, length(unique(temp$ObjectID))), unique(temp$ObjectID))

temp$Y = 1400 - temp$Y
temp$X = temp$X

x = temp$X
y = temp$Y

temp$X = x
temp$Y = y

i=1
while(i<=length(unique(names(distance)))){
  j = 101
  while(j < max.frame[i]){
    x1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "X"]
    x2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "X"]
    y1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "Y"]
    y2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "Y"]
    distance[i] = distance[i] + sqrt((x2-x1)^2 + (y2-y1)^2)
    j=j+100
  }
  i=i+1
}


speed = distance/max.frame

distance = distance*mm.per.pix["TauWTD14"]
speed = speed * speed.conversion["TauWTD14"]

TauWTD14.dist = distance
TauWTD14.speed = speed

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")


lines(x = temp$X[temp$ObjectID ==2],
     y = temp$Y[temp$ObjectID ==2],
     lwd = 1,
     col = "firebrick")

lines(x = temp$X[temp$ObjectID ==3],
     y = temp$Y[temp$ObjectID ==3],
     lwd = 1,
     col = "royalblue")

lines(x = temp$X[temp$ObjectID ==4],
     y = temp$Y[temp$ObjectID ==4],
     lwd = 1,
     col = "darkgreen")

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3)), 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen'),
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")

```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 1

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 2

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 3

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 4

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```





```{r echo = F, fig.height=7, fig.width= 7}


frame.distance = data.frame(Rep = c(rep("1", ((floor(max.frame[1]/100)))),
                                 rep("2", ((floor(max.frame[2]/100)))),
                                 rep("3", ((floor(max.frame[3]/100)))),
                                 rep("4", ((floor(max.frame[4]/100))))),
                      frame = c(100*(1:floor(max.frame[1]/100)-1),
                                100*(1:floor(max.frame[2]/100)-1),
                                100*(1:floor(max.frame[3]/100)-1),
                                100*(1:floor(max.frame[4]/100)-1)),
                        distance = c(0))


i=1
while(i<=length(unique(names(distance)))){
  temp.distance = 0
  j = 200
  while(j-100 < max.frame[i]){
    x1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "X"]
    x2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "X"]
    y1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "Y"]
    y2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "Y"]
    temp.distance = temp.distance + sqrt((x2-x1)^2 + (y2-y1)^2)
    frame.distance[frame.distance$Rep == names(distance)[i] &
                     frame.distance$frame == j-100, "distance"]= temp.distance
    j=j+100
  }
  i=i+1
}

frame.distance$distance = frame.distance$distance*mm.per.pix["TauWTD14"]

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,3500), xlim = c(0,9800),
     xlab = "Frame",
     ylab = "Distance (mm)")

lines(x = frame.distance$frame[frame.distance$Rep ==1],
     y = frame.distance$distance[frame.distance$Rep ==1],
     lwd = 1,
     col = "darkorange")


lines(x = frame.distance$frame[frame.distance$Rep ==2],
     y = frame.distance$distance[frame.distance$Rep ==2],
     lwd = 1,
     col = "firebrick")

lines(x = frame.distance$frame[frame.distance$Rep ==3],
     y = frame.distance$distance[frame.distance$Rep ==3],
     lwd = 1,
     col = "royalblue")

lines(x = frame.distance$frame[frame.distance$Rep ==4],
     y = frame.distance$distance[frame.distance$Rep ==4],
     lwd = 1,
     col = "darkgreen")

legend(x = 10200,
       y = 3500,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3)), 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen'),
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm")


```





```{r echo = F, fig.height=7, fig.width= 7}

temp = read.csv("/Users/johncsantiago/Documents/GitHub/Python/LarvalLocomotion/PreliminaryCode/5106_TauR406W_D1_mask_median_improved.csv")

colnames(temp)[2:4] = c("ObjectID", "X", "Y")

title = "TauR406W D1"


max.frame = setNames(rep(0, length(unique(temp$ObjectID))), unique(temp$ObjectID))
max.frame = c(max(temp$Frame[temp$ObjectID == 1]),
              max(temp$Frame[temp$ObjectID == 2]),
              max(temp$Frame[temp$ObjectID == 3]),
              max(temp$Frame[temp$ObjectID == 4]),
              max(temp$Frame[temp$ObjectID == 5]))


temp = temp[(temp$ObjectID == 1 & temp$Frame <= max.frame[1]) |
              (temp$ObjectID == 2 & temp$Frame <= max.frame[2]) |
              (temp$ObjectID == 3 & temp$Frame <= max.frame[3]) |
              (temp$ObjectID == 4 & temp$Frame <= max.frame[4]) |
              (temp$ObjectID == 5 & temp$Frame <= max.frame[5]),]

distance = setNames(rep(0, length(unique(temp$ObjectID))), unique(temp$ObjectID))

temp$Y = 1400 - temp$Y
temp$X = temp$X

x = temp$X
y = temp$Y

temp$X = x
temp$Y = y

i=1
while(i<=length(unique(names(distance)))){
  j = 101
  while(j < max.frame[i]){
    x1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "X"]
    x2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "X"]
    y1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "Y"]
    y2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "Y"]
    distance[i] = distance[i] + sqrt((x2-x1)^2 + (y2-y1)^2)
    j=j+100
  }
  i=i+1
}


speed = distance/max.frame

distance = distance*mm.per.pix["TauR406WD1"]
speed = speed * speed.conversion["TauR406WD1"]

TauR406WD1.dist = distance
TauR406WD1.speed = speed

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")


lines(x = temp$X[temp$ObjectID ==2],
     y = temp$Y[temp$ObjectID ==2],
     lwd = 1,
     col = "firebrick")

lines(x = temp$X[temp$ObjectID ==3],
     y = temp$Y[temp$ObjectID ==3],
     lwd = 1,
     col = "royalblue")

lines(x = temp$X[temp$ObjectID ==4],
     y = temp$Y[temp$ObjectID ==4],
     lwd = 1,
     col = "darkgreen")

lines(x = temp$X[temp$ObjectID ==5],
     y = temp$Y[temp$ObjectID ==5],
     lwd = 1,
     col = "violetred")

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3)), 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred'),
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")

```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 1

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 2

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 3

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 4

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```



```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 5

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```



```{r echo = F, fig.height=7, fig.width= 7}


frame.distance = data.frame(Rep = c(rep("1", ((floor(max.frame[1]/100)))),
                                 rep("2", ((floor(max.frame[2]/100)))),
                                 rep("3", ((floor(max.frame[3]/100)))),
                                 rep("4", ((floor(max.frame[4]/100)))),
                                 rep("5", ((floor(max.frame[5]/100))))),
                      frame = c(100*(1:floor(max.frame[1]/100)-1),
                                100*(1:floor(max.frame[2]/100)-1),
                                100*(1:floor(max.frame[3]/100)-1),
                                100*(1:floor(max.frame[4]/100)-1),
                                100*(1:floor(max.frame[5]/100)-1)),
                        distance = c(0))


i=1
while(i<=length(unique(names(distance)))){
  temp.distance = 0
  j = 200
  while(j-100 < max.frame[i]){
    x1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "X"]
    x2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "X"]
    y1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "Y"]
    y2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "Y"]
    temp.distance = temp.distance + sqrt((x2-x1)^2 + (y2-y1)^2)
    frame.distance[frame.distance$Rep == names(distance)[i] &
                     frame.distance$frame == j-100, "distance"]= temp.distance
    j=j+100
  }
  i=i+1
}

frame.distance$distance = frame.distance$distance*mm.per.pix["TauR406WD1"]

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,3500), xlim = c(0,9800),
     xlab = "Frame",
     ylab = "Distance (mm)")

lines(x = frame.distance$frame[frame.distance$Rep ==1],
     y = frame.distance$distance[frame.distance$Rep ==1],
     lwd = 1,
     col = "darkorange")


lines(x = frame.distance$frame[frame.distance$Rep ==2],
     y = frame.distance$distance[frame.distance$Rep ==2],
     lwd = 1,
     col = "firebrick")

lines(x = frame.distance$frame[frame.distance$Rep ==3],
     y = frame.distance$distance[frame.distance$Rep ==3],
     lwd = 1,
     col = "royalblue")

lines(x = frame.distance$frame[frame.distance$Rep ==4],
     y = frame.distance$distance[frame.distance$Rep ==4],
     lwd = 1,
     col = "darkgreen")

lines(x = frame.distance$frame[frame.distance$Rep ==5],
     y = frame.distance$distance[frame.distance$Rep ==5],
     lwd = 1,
     col = "violetred")

legend(x = 10200,
       y = 3500,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3)), 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred'),
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm")


```




```{r echo = F, fig.height=7, fig.width= 7}

temp = read.csv("/Users/johncsantiago/Documents/GitHub/Python/LarvalLocomotion/PreliminaryCode/5106 TauR406W D14_mask_median_output_improved.csv")

colnames(temp)[2:4] = c("ObjectID", "X", "Y")

title = "TauR406W D14"


max.frame = setNames(rep(0, length(unique(temp$ObjectID))), unique(temp$ObjectID))
max.frame = c(max(temp$Frame[temp$ObjectID == 1]),
              max(temp$Frame[temp$ObjectID == 2]),
              max(temp$Frame[temp$ObjectID == 3]),
              max(temp$Frame[temp$ObjectID == 4]),
              max(temp$Frame[temp$ObjectID == 5]))


temp = temp[(temp$ObjectID == 1 & temp$Frame <= max.frame[1]) |
              (temp$ObjectID == 2 & temp$Frame <= max.frame[2]) |
              (temp$ObjectID == 3 & temp$Frame <= max.frame[3]) |
              (temp$ObjectID == 4 & temp$Frame <= max.frame[4]) |
              (temp$ObjectID == 5 & temp$Frame <= max.frame[5]),]

distance = setNames(rep(0, length(unique(temp$ObjectID))), unique(temp$ObjectID))

temp$Y = 1400 - temp$Y
temp$X = temp$X

x = temp$X
y = temp$Y

temp$X = x
temp$Y = y

i=1
while(i<=length(unique(names(distance)))){
  j = 101
  while(j < max.frame[i]){
    x1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "X"]
    x2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "X"]
    y1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "Y"]
    y2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "Y"]
    distance[i] = distance[i] + sqrt((x2-x1)^2 + (y2-y1)^2)
    j=j+100
  }
  i=i+1
}


speed = distance/max.frame

distance = distance*mm.per.pix["TauR406WD14"]
speed = speed * speed.conversion["TauR406WD14"]

TauR406WD14.dist = distance
TauR406WD14.speed = speed

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")


lines(x = temp$X[temp$ObjectID ==2],
     y = temp$Y[temp$ObjectID ==2],
     lwd = 1,
     col = "firebrick")

lines(x = temp$X[temp$ObjectID ==3],
     y = temp$Y[temp$ObjectID ==3],
     lwd = 1,
     col = "royalblue")

lines(x = temp$X[temp$ObjectID ==4],
     y = temp$Y[temp$ObjectID ==4],
     lwd = 1,
     col = "darkgreen")

lines(x = temp$X[temp$ObjectID ==5],
     y = temp$Y[temp$ObjectID ==5],
     lwd = 1,
     col = "violetred")

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3)), 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred'),
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")

```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 1

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 2

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 3

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 4

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```



```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 5

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```



```{r echo = F, fig.height=7, fig.width= 7}


frame.distance = data.frame(Rep = c(rep("1", ((floor(max.frame[1]/100)))),
                                 rep("2", ((floor(max.frame[2]/100)))),
                                 rep("3", ((floor(max.frame[3]/100)))),
                                 rep("4", ((floor(max.frame[4]/100)))),
                                 rep("5", ((floor(max.frame[5]/100))))),
                      frame = c(100*(1:floor(max.frame[1]/100)-1),
                                100*(1:floor(max.frame[2]/100)-1),
                                100*(1:floor(max.frame[3]/100)-1),
                                100*(1:floor(max.frame[4]/100)-1),
                                100*(1:floor(max.frame[5]/100)-1)),
                        distance = c(0))


i=1
while(i<=length(unique(names(distance)))){
  temp.distance = 0
  j = 200
  while(j-100 < max.frame[i]){
    x1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "X"]
    x2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "X"]
    y1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "Y"]
    y2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "Y"]
    temp.distance = temp.distance + sqrt((x2-x1)^2 + (y2-y1)^2)
    frame.distance[frame.distance$Rep == names(distance)[i] &
                     frame.distance$frame == j-100, "distance"]= temp.distance
    j=j+100
  }
  i=i+1
}

frame.distance$distance = frame.distance$distance*mm.per.pix["TauR406WD14"]

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,3500), xlim = c(0,9800),
     xlab = "Frame",
     ylab = "Distance (mm)")

lines(x = frame.distance$frame[frame.distance$Rep ==1],
     y = frame.distance$distance[frame.distance$Rep ==1],
     lwd = 1,
     col = "darkorange")


lines(x = frame.distance$frame[frame.distance$Rep ==2],
     y = frame.distance$distance[frame.distance$Rep ==2],
     lwd = 1,
     col = "firebrick")

lines(x = frame.distance$frame[frame.distance$Rep ==3],
     y = frame.distance$distance[frame.distance$Rep ==3],
     lwd = 1,
     col = "royalblue")

lines(x = frame.distance$frame[frame.distance$Rep ==4],
     y = frame.distance$distance[frame.distance$Rep ==4],
     lwd = 1,
     col = "darkgreen")

lines(x = frame.distance$frame[frame.distance$Rep ==5],
     y = frame.distance$distance[frame.distance$Rep ==5],
     lwd = 1,
     col = "violetred")

legend(x = 10200,
       y = 3500,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3)), 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred'),
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm")


```



```{r echo = F, fig.height=7, fig.width= 7}

temp = read.csv("/Users/johncsantiago/Documents/GitHub/Python/LarvalLocomotion/PreliminaryCode/5147 LacZ D1_mask_median_improved.csv")

colnames(temp)[2:4] = c("ObjectID", "X", "Y")

title = "LacZ D1"


max.frame = setNames(rep(0, length(unique(temp$ObjectID))), unique(temp$ObjectID))
max.frame = c(max(temp$Frame[temp$ObjectID == 1]),
              max(temp$Frame[temp$ObjectID == 2]),
              max(temp$Frame[temp$ObjectID == 3]),
              max(temp$Frame[temp$ObjectID == 4]),
              max(temp$Frame[temp$ObjectID == 5]))


temp = temp[(temp$ObjectID == 1 & temp$Frame <= max.frame[1]) |
              (temp$ObjectID == 2 & temp$Frame <= max.frame[2]) |
              (temp$ObjectID == 3 & temp$Frame <= max.frame[3]) |
              (temp$ObjectID == 4 & temp$Frame <= max.frame[4]) |
              (temp$ObjectID == 5 & temp$Frame <= max.frame[5]),]

distance = setNames(rep(0, length(unique(temp$ObjectID))), unique(temp$ObjectID))

temp$Y = 1400 - temp$Y
temp$X = temp$X

x = temp$X
y = temp$Y

temp$X = x
temp$Y = y

i=1
while(i<=length(unique(names(distance)))){
  j = 101
  while(j < max.frame[i]){
    x1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "X"]
    x2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "X"]
    y1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "Y"]
    y2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "Y"]
    distance[i] = distance[i] + sqrt((x2-x1)^2 + (y2-y1)^2)
    j=j+100
  }
  i=i+1
}


speed = distance/max.frame

distance = distance*mm.per.pix["LacZD1"]
speed = speed * speed.conversion["LacZD1"]

LacZD1.dist = distance
LacZD1.speed = speed

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")


lines(x = temp$X[temp$ObjectID ==2],
     y = temp$Y[temp$ObjectID ==2],
     lwd = 1,
     col = "firebrick")

lines(x = temp$X[temp$ObjectID ==3],
     y = temp$Y[temp$ObjectID ==3],
     lwd = 1,
     col = "royalblue")

lines(x = temp$X[temp$ObjectID ==4],
     y = temp$Y[temp$ObjectID ==4],
     lwd = 1,
     col = "darkgreen")

lines(x = temp$X[temp$ObjectID ==5],
     y = temp$Y[temp$ObjectID ==5],
     lwd = 1,
     col = "violetred")

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")

```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 1

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 2

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 3

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 4

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```



```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 5

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```



```{r echo = F, fig.height=7, fig.width= 7}


frame.distance = data.frame(Rep = c(rep("1", ((floor(max.frame[1]/100)))),
                                 rep("2", ((floor(max.frame[2]/100)))),
                                 rep("3", ((floor(max.frame[3]/100)))),
                                 rep("4", ((floor(max.frame[4]/100)))),
                                 rep("5", ((floor(max.frame[5]/100))))),
                      frame = c(100*(1:floor(max.frame[1]/100)-1),
                                100*(1:floor(max.frame[2]/100)-1),
                                100*(1:floor(max.frame[3]/100)-1),
                                100*(1:floor(max.frame[4]/100)-1),
                                100*(1:floor(max.frame[5]/100)-1)),
                        distance = c(0))


i=1
while(i<=length(unique(names(distance)))){
  temp.distance = 0
  j = 200
  while(j-100 < max.frame[i]){
    x1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "X"]
    x2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "X"]
    y1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "Y"]
    y2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "Y"]
    temp.distance = temp.distance + sqrt((x2-x1)^2 + (y2-y1)^2)
    frame.distance[frame.distance$Rep == names(distance)[i] &
                     frame.distance$frame == j-100, "distance"]= temp.distance
    j=j+100
  }
  i=i+1
}

frame.distance$distance = frame.distance$distance*mm.per.pix["LacZD1"]


par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,3500), xlim = c(0,9800),
     xlab = "Frame",
     ylab = "Distance (mm)")

lines(x = frame.distance$frame[frame.distance$Rep ==1],
     y = frame.distance$distance[frame.distance$Rep ==1],
     lwd = 1,
     col = "darkorange")


lines(x = frame.distance$frame[frame.distance$Rep ==2],
     y = frame.distance$distance[frame.distance$Rep ==2],
     lwd = 1,
     col = "firebrick")

lines(x = frame.distance$frame[frame.distance$Rep ==3],
     y = frame.distance$distance[frame.distance$Rep ==3],
     lwd = 1,
     col = "royalblue")

lines(x = frame.distance$frame[frame.distance$Rep ==4],
     y = frame.distance$distance[frame.distance$Rep ==4],
     lwd = 1,
     col = "darkgreen")

lines(x = frame.distance$frame[frame.distance$Rep ==5],
     y = frame.distance$distance[frame.distance$Rep ==5],
     lwd = 1,
     col = "violetred")

legend(x = 10200,
       y = 3000,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3)), 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred'),
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm")
       


```



```{r echo = F, fig.height=7, fig.width= 7}

temp = read.csv("/Users/johncsantiago/Documents/GitHub/Python/LarvalLocomotion/PreliminaryCode/5147 LacZ D14_mask_median_improved.csv")

colnames(temp)[2:4] = c("ObjectID", "X", "Y")

title = "LacZ D14"


max.frame = setNames(rep(0, length(unique(temp$ObjectID))), unique(temp$ObjectID))
max.frame = c(max(temp$Frame[temp$ObjectID == 1]),
              max(temp$Frame[temp$ObjectID == 2]),
              max(temp$Frame[temp$ObjectID == 3]),
              max(temp$Frame[temp$ObjectID == 4]),
              max(temp$Frame[temp$ObjectID == 5]))


temp = temp[(temp$ObjectID == 1 & temp$Frame <= max.frame[1]) |
              (temp$ObjectID == 2 & temp$Frame <= max.frame[2]) |
              (temp$ObjectID == 3 & temp$Frame <= max.frame[3]) |
              (temp$ObjectID == 4 & temp$Frame <= max.frame[4]) |
              (temp$ObjectID == 5 & temp$Frame <= max.frame[5]),]

distance = setNames(rep(0, length(unique(temp$ObjectID))), unique(temp$ObjectID))

temp$Y = 1400 - temp$Y
temp$X = temp$X

x = temp$X
y = temp$Y

temp$X = x
temp$Y = y

i=1
while(i<=length(unique(names(distance)))){
  j = 101
  while(j < max.frame[i]){
    x1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "X"]
    x2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "X"]
    y1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "Y"]
    y2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "Y"]
    distance[i] = distance[i] + sqrt((x2-x1)^2 + (y2-y1)^2)
    j=j+100
  }
  i=i+1
}

speed = distance/max.frame

distance = distance*mm.per.pix["LacZD14"]
speed = speed * speed.conversion["LacZD14"]

LacZD14.dist = distance
LacZD14.speed = speed

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")


lines(x = temp$X[temp$ObjectID ==2],
     y = temp$Y[temp$ObjectID ==2],
     lwd = 1,
     col = "firebrick")

lines(x = temp$X[temp$ObjectID ==3],
     y = temp$Y[temp$ObjectID ==3],
     lwd = 1,
     col = "royalblue")

lines(x = temp$X[temp$ObjectID ==4],
     y = temp$Y[temp$ObjectID ==4],
     lwd = 1,
     col = "darkgreen")

lines(x = temp$X[temp$ObjectID ==5],
     y = temp$Y[temp$ObjectID ==5],
     lwd = 1,
     col = "violetred")

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")

```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 1

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 2

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 3

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```


```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 4

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```



```{r echo = F, fig.height=7, fig.width= 7}

samplenum = 5

par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,1400), xlim = c(0,1400),
     xlab = "",
     ylab = "") #ylim = c(300,600), xlim = c(200,600))#

#rasterImage(bgpic, xleft = 0,
#            xright = 1080,
#            ybottom = 0,
#            ytop = 720)

if(samplenum == 1){
  lines(x = temp$X[temp$ObjectID ==1],
     y = temp$Y[temp$ObjectID ==1],
     lwd = 1,
     col = "darkorange")
}


if(samplenum == 2){
  lines(x = temp$X[temp$ObjectID ==2],
       y = temp$Y[temp$ObjectID ==2],
       lwd = 1,
       col = "firebrick")
}

if(samplenum == 3){
  lines(x = temp$X[temp$ObjectID ==3],
       y = temp$Y[temp$ObjectID ==3],
       lwd = 1,
       col = "royalblue")
}

if(samplenum == 4){
  lines(x = temp$X[temp$ObjectID ==4],
       y = temp$Y[temp$ObjectID ==4],
       lwd = 1,
       col = "darkgreen")
}

if(samplenum == 5){
  lines(x = temp$X[temp$ObjectID ==5],
       y = temp$Y[temp$ObjectID ==5],
       lwd = 1,
       col = "violetred")
}

legend(x = 1460,
       y = 1400,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3))[samplenum], 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred')[samplenum],
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm/s")
```



```{r echo = F, fig.height=7, fig.width= 7}


frame.distance = data.frame(Rep = c(rep("1", ((floor(max.frame[1]/100)))),
                                 rep("2", ((floor(max.frame[2]/100)))),
                                 rep("3", ((floor(max.frame[3]/100)))),
                                 rep("4", ((floor(max.frame[4]/100)))),
                                 rep("5", ((floor(max.frame[5]/100))))),
                      frame = c(100*(1:floor(max.frame[1]/100)-1),
                                100*(1:floor(max.frame[2]/100)-1),
                                100*(1:floor(max.frame[3]/100)-1),
                                100*(1:floor(max.frame[4]/100)-1),
                                100*(1:floor(max.frame[5]/100)-1)),
                        distance = c(0))


i=1
while(i<=length(unique(names(distance)))){
  temp.distance = 0
  j = 200
  while(j-100 < max.frame[i]){
    x1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "X"]
    x2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "X"]
    y1 = temp[temp$Frame == j-100 & temp$ObjectID == names(distance)[i], "Y"]
    y2 = temp[temp$Frame == j & temp$ObjectID == names(distance)[i], "Y"]
    temp.distance = temp.distance + sqrt((x2-x1)^2 + (y2-y1)^2)
    frame.distance[frame.distance$Rep == names(distance)[i] &
                     frame.distance$frame == j-100, "distance"]= temp.distance
    j=j+100
  }
  i=i+1
}

frame.distance$distance = frame.distance$distance*mm.per.pix["LacZD14"]


par(mar = c(5.35,5.35,5.35,5.35))

plot(NA, 
     type ="n",
     main = title,
     ylim = c(0,3500), xlim = c(0,9800),
     xlab = "Frame",
     ylab = "Distance (mm)")

lines(x = frame.distance$frame[frame.distance$Rep ==1],
     y = frame.distance$distance[frame.distance$Rep ==1],
     lwd = 1,
     col = "darkorange")


lines(x = frame.distance$frame[frame.distance$Rep ==2],
     y = frame.distance$distance[frame.distance$Rep ==2],
     lwd = 1,
     col = "firebrick")

lines(x = frame.distance$frame[frame.distance$Rep ==3],
     y = frame.distance$distance[frame.distance$Rep ==3],
     lwd = 1,
     col = "royalblue")

lines(x = frame.distance$frame[frame.distance$Rep ==4],
     y = frame.distance$distance[frame.distance$Rep ==4],
     lwd = 1,
     col = "darkgreen")

lines(x = frame.distance$frame[frame.distance$Rep ==5],
     y = frame.distance$distance[frame.distance$Rep ==5],
     lwd = 1,
     col = "violetred")

legend(x = 10200,
       y = 3000,
       #legend = c(paste0('1: ', floor(distance[1]), "px"),
       #          paste0('2: ', floor(distance[2]), "px"),
       #           paste0('3: ', floor(distance[3]), "px"),
       #            paste0('4: ', floor(distance[4]), "px"),
       #            paste0('5: ', floor(distance[5]), "px")),
       legend = c(signif(speed[1],3),
                  signif(speed[2],3),
                  signif(speed[3],3),
                  signif(speed[4],3),
                  signif(speed[5],3)), 
       fill = c("darkorange", "firebrick", "royalblue", 'darkgreen', 'violetred'),
       cex = 1,
       bty = 'n',
       pt.cex = .5,
       xpd = T,
       title = "mm")
       


```



```{r echo = F, fig.width= 10, fig.height= 7}

all.tau.data = data.frame(Genotype = c(rep("TauWT D1", 5),
                                       rep("TauWT D14", 4),
                                       rep("TauR406W D1", 5),
                                       rep("TauR406W D14", 5),
                                       rep("LacZ D1", 5),
                                       rep("LacZ D14", 5)),
                          Speed = c(TauWTD1.speed,TauWTD14.speed,
                                    TauR406WD1.speed, TauR406WD14.speed,
                                    LacZD1.speed, LacZD14.speed),
                          Distance = c(TauWTD1.dist, TauWTD14.dist,
                                       TauR406WD1.dist, TauR406WD14.dist,
                                       LacZD1.dist, LacZD14.dist))

all.tau.data$Genotype = factor(all.tau.data$Genotype, levels = c("TauWT D1", "TauWT D14", "TauR406W D1", "TauR406W D14", "LacZ D1", "LacZ D14"))

hex = function(color, alpha){
  rgb2hex = color
  i = 1
  while(i <= length(color)){
    rgbvals = col2rgb(color[i])
    rgb2hex[i] = rgb(rgbvals[1]/255, rgbvals[2]/255, rgbvals[3]/255, alpha)
    i = i+1
  }
  return(rgb2hex)
}


boxplot(all.tau.data$Speed~all.tau.data$Genotype,
        col = hex(c("navy", "navy", "firebrick","firebrick", "darkgreen","darkgreen")[unique(as.numeric(all.tau.data$Genotype))],.5), xlab = "", ylab = "Speed (mm/s)",
        ylim = c(0, 10))

beeswarm(all.tau.data$Speed~all.tau.data$Genotype,
       pch = c(21,23),
       cex = 2,
       method = "center",
       bg = hex(c("dodgerblue", "dodgerblue", "brown","brown", "green","green")[unique(as.numeric(all.tau.data$Genotype))],1),
       add = T)
```


```{r echo = F}


t.data = list("TauWTD1" = TauWTD1.speed,
              "TauWTD14" = c(TauWTD14.speed,NA),
              "TauR406WD1" = TauR406WD1.speed,
              "TauR406WD14" = TauR406WD14.speed,
              "LacZD1" = LacZD1.speed,
              "LacZD14" = LacZD14.speed)

t.table = data.frame(Genotype1 = character(),
                     Genotype2 = character(),
                     pval = numeric())

i=1
while(i <= length(t.data)){
  j = i+1
  while(j <= length(t.data)){
    t.temp = data.frame(Genotype1 = names(t.data)[i],
                        Genotype2 = names(t.data)[j],
                        pval = t.test(x = t.data[[i]],
                                      y = t.data[[j]],
                                      paired = F)[[3]])
    t.table = rbind(t.table, t.temp)
      j = j+1
  }
  i = i+1
}


t.stripe = t.table$pval <= .05
knitr::kable(t.table,
             caption = 'All t-tests Tau Activity')  %>%
kable_styling() %>%
row_spec(c(1:nrow(t.table))[t.table$pval <= .05], bold = T, color = "black", background = "gold")

```