---
title: "Emily TBPH Analysis"
author: "John Santiago"
date: "2024-02-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

Emily = read.csv('/Users/johncsantiago/Documents/GitHub/WhartonLab/EmilyTBPH_qPCR.csv', header = T)

data = Emily[Emily$Genotype != 'tbph',]

orer = data[data$Genotype=='OreR',]
otu = data[data$Genotype=='otu-RNAi',]
tudor = data[data$Genotype=='Tudor-SN-RNAi',]
lacz = data[data$Genotype=='LacZ',]
rnai = data[data$Genotype=='tbph-RNAi',]

sig.values = data.frame(Genotype = c("otu-RNAi", "Tudor-SN-RNAi", 'tbph-RNAi', 'LacZ'),
                        RelativeOreR = c(t.test(orer$dCT, otu$dCT, 
                                                paired = T, alternative = "g")[[3]],
                                         t.test(orer$dCT, tudor$dCT, 
                                                paired = T, alternative = "g")[[3]],
                                         t.test(orer$dCT, rnai$dCT, 
                                                paired = T, alternative = "g")[[3]],
                                         t.test(orer$dCT, lacz$dCT, 
                                                paired = T, alternative = "g")[[3]]),
                        RelativeLacZ = c(t.test(lacz$dCT, otu$dCT, paired = T)[[3]],
                                         t.test(lacz$dCT, tudor$dCT, paired = T)[[3]],
                                         t.test(lacz$dCT, rnai$dCT, paired = T)[[3]],
                                         NA))

```



```{r}

boxdata = na.omit(data)

boxdata = boxdata[boxdata$Genotype != 'Tudor-SN-RNAi',]

boxplot(boxdata$ddCT.FC ~ boxdata$Genotype, 
        xlab="",     
        main= "FC relative to OreR",
        ylab="FC (2^-ddCT)", 
        las = 1, 
        cex.axis = .8,
        ylim = c(0, 5))

points(x=as.numeric(factor(boxdata$Genotype)),
       y=boxdata$ddCT.FC,
       cex=1,
       pch=21,
       bg=c('firebrick',"gold","darkgreen","dodgerblue", 'mediumorchid')[as.numeric(factor(boxdata$Genotype))])

abline(h = 1, lty = 2)

#lines(x= )

text(x = c(2:4), y = c(5,5,5), labels = paste0("p = ", signif(sig.values[c(1,3,2),3],3)))

legend('topright',
       inset=c(-0.175,0),
       legend = c('OreR', 'Otu-RNAi', 'Tudor-SN-RNAi', 'tbph-RNAi', 'LacZ'), 
       fill = c('firebrick',"darkgreen","gold","dodgerblue", 'mediumorchid'),
       cex = .65,
       bty = 'n',
       pt.cex = .5)


```





```{r}

bardata = setNames(c(mean(data$ddCT.FC[data$Genotype == 'LacZ']),
                     mean(data$ddCT.FC[data$Genotype == 'otu-RNAi']),
                     mean(data$ddCT.FC[data$Genotype == 'Tudor-SN-RNAi']),
                     mean(data$ddCT.FC[data$Genotype == 'tbph-RNAi'])), 
                   c('LacZ', 'otu-RNAi', 'Tudor-SN-RNAi', 'tbph-RNAi'))


barplot(height = bardata, 
        xlab="",     
        main= "FC relative to OreR",
        ylab="FC (2^-ddCT)", 
        las = 1, 
        cex.axis = .8,
        col = c('brown',"gold2","darkgreen","steelblue"),
        ylim = c(0,5))

abline(h = 1, lty = 2)

text(x = c(2:4), y = c(4.5,4.5,4.5), labels = paste0("p = ", signif(sig.values[c(1,3,2),3],3)))

legend('topright',
       inset=c(-0.175,0),
       legend = c('OreR', 'Otu-RNAi', 'Tudor-SN-RNAi', 'tbph-RNAi', 'LacZ'), 
       fill = c('brown',"gold2","darkgreen","steelblue"),
       cex = .65,
       bty = 'n',
       pt.cex = .5)


```




```{r echo = F}

temp = read.csv("/Users/johncsantiago/Documents/track.csv", header = F)

plot(x=temp$V1, y=temp$V2, xlim = c(25, 225), pch = 21, bg='gold', cex = .5)
points(x=temp$V3, y=temp$V4, pch = 21, bg='brown', cex = .5)
```







````{r echo = F}
library(reshape2)
eclosion = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/Russo Fig 1 eclosion.csv", header = T)

eclosion = na.omit(melt(eclosion, variable.name = 'Genotype', value.name = "PercentEclosed"))

eclosion.aov = aov(eclosion$PercentEclosed~eclosion$Genotype)

eclosion.Tukey = TukeyHSD(eclosion.aov)

write.csv(eclosion.Tukey$`eclosion$Genotype`, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Russo Fig 1 eclosion_TukeyDATA.csv")

```






