---
title: "Emily Network"
author: "John Santiago"
date: "2024-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = F, fig.width = 12, fig.height = 12}

library(visNetwork)
networkdata = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/ConspiracyNetwork/ConspiracyNetwork.csv", header = T)

networkdata = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/NewEmilyNetwork.csv", header = T)

allSGs = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/SG Kankel.csv", header = T)
SGs = allSGs$FBGN
SGs = intersect(SGs, networkdata$FGbn)
SGs = unique(c(networkdata[networkdata$FGbn %in% SGs, 'to'], intersect(allSGs$GENE, networkdata$from)))

networkdata[networkdata == ''] = NA



nodes = data.frame(id = na.omit(unique(c(networkdata[, 1], networkdata[, 2]))))
parent = unique(networkdata$from)
nodes$group = 'interacting'
nodes[nodes$id %in% networkdata$to[duplicated(networkdata$to)], 'group'] = 'intersecting'
nodes[nodes$id %in% parent, 'group'] = 'target'
nodes[nodes$id %in% SGs, 'group'] = 'SG gene'




visedges = na.omit(networkdata[, 1:2])
visedges$color = 'black'

visNetwork(nodes,visedges)%>%
  visLayout(hierarchical=F, improvedLayout=T)%>%
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE)%>%
  visGroups(groupname = 'interacting', 
            shape = 'box', 
            color = list(background = 'darkblue', border = 'black'), 
            font = list(color= 'white',size=20))%>%
    visGroups(groupname = 'intersecting', 
            shape = 'box', 
            color = list(background = 'deeppink', border = 'black'), 
            font = list(color= 'black',size=20))%>%
  visGroups(groupname = 'target',
            shape = 'box', 
            color = list(background = 'goldenrod', border = 'black'), 
            font=list(color= 'black',size=20),
            physics = FALSE)%>%
  visGroups(groupname = 'SG gene',
            shape = 'box', 
            color = list(background = 'limegreen', border = 'black'), 
            font=list(color= 'black',size=20),
            physics = FALSE)



```

