---
title: "GO and KEGG Term Enrichment"
author: "John Santiago"
date: "2024-05-08"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```



```{r echo = F, message = F}

# Conditions
#Geno is WT or GR
#TKT is either "C", "OE", or "Df"
#Sex is "F" or "M"

Geno1 = "GR"
TKT1 = "C"
Sex1 = "F"

Geno2 = "WT"
TKT2 = "C"
Sex2 = "F"

##Conditions for second comparison
Geno3 = "GR"
TKT3 = "C"
Sex3 = "M"

Geno4 = "WT"
TKT4 = "C"
Sex4 = "M"





```

```{r echo = F, message = F, warning = F}


source('https://raw.githubusercontent.com/johncsantiago/WhartonLab/refs/heads/master/G85R.GOandKEGGPlottingFunctions.R')

plot.data = G85R.data(Geno1, Geno2, Geno3, Geno4,
                      Sex1, Sex2, Sex3, Sex4,
                      TKT1, TKT2, TKT3, TKT4)

```


```{r echo = F}

##Uses data from primary comparison
##Plots genes with an FDR <= 0.05
##point size is relative to maximum mean expression in the two conditions

G85R.volcano(plot.data)

```


```{r echo = F}

##Uses data from primary comparison
##point size is relative to max mean expression in any condition
##grey points indicate less than 1 fold difference between the comparisons
G85R.compare.genes(plot.data)

```


```{r echo = F}

##Uses data from primary comparison
##point size is relative to mean expression in variable condition
G85R.DEG.venn(plot.data)

```

```{r echo = F, include = F, warning = F}

####Uses sigDEGs from primary comparison
cat.data = G85R.Enrichment(plot.data)

```


```{r echo = F}

##plots the specified most significantly enriched KEGG categories
##which ranks of categories to use
##usecats is a vector of numbers specifying which ranks to use
##eg. c(1, 5:6) will use the first, fifth and sixth most sig. cats.
##can also just type 'sigs' 
usecats=c(1:20)
#usecats = 'sigs'  

G85R.KEGG20(cat.data, plot.data, usecats)

```


```{r echo = F, include = T}

##can be the exact name or 5 digit code in quotes
specific.kegg = "00230"

G85R.plotkegg.genes(specific.kegg, plot.data)

```


```{r echo = F, message=F, fig.width=7}

##Color is relative to Fold Change

##5 digits from KEGG ID
PathwayID = "00230"

#options include 'primary' or 'both'
use = 'both'


G85R.KEGG.diagram(PathwayID, plot.data, use, sigs.only = F)


```


```{r echo = F, include = T, warnings = F}

##Uses data from both comparisons
##Plot all of the genes in the selected KEGG category
##Size is relative to significance 


##can be the exact name or 5 digit code in quotes
specific.kegg = "00230"

G85R.comparekegg.genes(specific.kegg, plot.data)

```


```{r echo = F}

## BP, CC, or MF
GO.ontology = 'BP'

##can select which categories ot include or say 'sigs.only'
usecats=c(1:20)
#usecats = 'sigs.only'

G85R.GO20(cat.data, GO.ontology, plot.data, usecats)

```


```{r echo = F}

##the 7 digits of a GOterm id or the exact term name
specific.go = '0022008'

G85R.plotgo.genes(specific.go, plot.data)

```


```{r echo = F, warning = F}

##the 7 digits of a GOterm id or the exact term name
specific.go = '0022008'

G85R.comparego.genes(specific.go, plot.data)

```


```{r echo = F, warning = F, message = F}

##This function is very slow
## BP, CC, or MF
GO.ontology = 'BP'

rt = tree(cat.data, GO.ontology)
  
treemapPlot(rt)

```


```{r echo = F, warning = F}

##a parent category generated in the treemapPlot function
parent.category = 'neurogenesis'

G85R.plotparentcat.genes(parent.category, plot.data, sigs.only = T)

```


```{r echo = F}

##a parent category generated in the treemapPlot function
##parent.category = 'neurogenesis'

G85R.compareparent.genes(parent.category, plot.data, sigs.only = T)
##dot size is relative to the max FDR of either condition


```  









