---
title: "SpecificGO Genes"
author: "John Santiago"
date: "2026-04-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```



```{r echo = F, message = F, warning = FALSE}

source('https://raw.githubusercontent.com/johncsantiago/WhartonLab/refs/heads/master/GenesInGOVolcano_functions.R')

```




```{r}

##The comparison is the DEG analysis between 2 groups
##G85R options are:
##    "GRF.CxDf"  "GRF.CxOE"  "GRM.CxDf"  "GRM.CxOE"
##    "WTF.CxDf"  "WTF.CxOE"  "WTM.CxDf"  "WTM.CxOE"
##    "GRxWT.FC"  "GRxWT.FDf" "GRxWT.FOE"
##    "GRxWT.MC"  "GRxWT.MDf" "GRxWT.MOE" 
##    "GR.FxM"    "WT.FxM" 

##A4V options are:
##  "AvS3FH"  "AvS3MH"  "AvS3FT"  "AvS3MT"  "AvS3FA"  "AvS3MA"
##  "AvS9FH"  "AvS9MH"  "AvS9FT"  "AvS9MT"  "AvS9FA"  "AvS9MA"
##  "AvS40FH" "AvS40FT" "AvS40FA"
##  "A3v9FH"  "A3v9MH"  "A3v9FT"  "A3v9MT"  "A3v9FA"  "A3v9MA"
##  "S3v9FH"  "S3v9MH"  "S3v9FT"  "S3v9MT"  "S3v9FA"  "S3v9MA"
##  "A3v40FH" "A3v40FT" "A3v40FA"
##  "S3v40FH" "S3v40FT" "S3v40FA"
##  "A9v40FH" "A9v40FT" "A9v40FA"
##  "S9v40FH" "S9v40FT" "S9v40FA"
##  "A3FvMH"  "A3FvMT"  "A3FvMA"
##  "S3FvMH"  "S3FvMT"  "S3FvMA"
##  "A9FvMH"  "A9FvMT"  "A9FvMA"
##  "S9FvMH"  "S9FvMT"  "S9FvMA" 

comparison = "S3v9FT"
keyword = "lipid"



plot.multipleGOterms(comparison, 
                     keyword, 
                     sig.only = TRUE, 
                     printallcategories = FALSE)

```



