---
title: "GO and KEGG Term Enrichment"
author: "John Santiago"
date: "2024-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = F, message = F}

source('/Users/johncsantiago/Documents/GitHub/WhartonLab/GOandKEGGPlottingFunctions.R')

```


```{r echo = F, message = F}


#A4V conditions use 4 parameters:   A or S for genotype
#                                   3, 9 or 40 for time
#                                   M or F for sex
#                                   H, T or A for body section
#                                   example: A3MT

#G85R conditions use 3 parameters:  GR or WT for genotype
#                                   M or F for sex
#                                   C, Df or OE for TKT modulation
#                                   example: GRMOE
Variable.Condition = "A3MT" 
Control.Condition = "A9FT"
secondary.Variable.Condition = "A9FT"
secondary.Control.Condition = "S9FT"



comparison = paste0(Variable.Condition, 'v', Control.Condition)
secondary.comparison = paste0(secondary.Variable.Condition, 'v', secondary.Control.Condition)

if(length(intersect(comparison, names(A4V.comparekey))) == 1){
  FC = A4V.FC[,c(A4V.comparekey[comparison], A4V.comparekey[secondary.comparison])]
  FDR = A4V.FDR[,c(A4V.comparekey[comparison], A4V.comparekey[secondary.comparison])]
  mean.data = A4V.meancpm[,c(Variable.Condition, Control.Condition, 
                             secondary.Variable.Condition, secondary.Control.Condition)]
  metab.data = 'none'
}

if(length(intersect(comparison, names(G85R.comparekey))) == 1){
  FC = G85R.FC[,c(G85R.comparekey[comparison], G85R.comparekey[secondary.comparison])]
  FDR = G85R.FDR[,c(G85R.comparekey[comparison], G85R.comparekey[secondary.comparison])]
  mean.data = G85R.meancpm[,c(Variable.Condition, Control.Condition, 
                              secondary.Variable.Condition, secondary.Control.Condition)]
  metab.data = G85R.metab.comparekey[c(comparison, secondary.comparison)]
  if(G85R.metab.comparekey[c(comparison)] == G85R.metab.comparekey[c(secondary.comparison)]){
    metab.data = G85R.metab.comparekey[c(comparison)]
  }
}

subset = F

if(subset == T){
  geneset = biomarkers
  FC[setdiff(row.names(FC),geneset),] = 1 
  FDR[setdiff(row.names(FDR),geneset),] = 1 
}

```

```{r echo = F, include = T}

####Uses sigDEGs from primary comparison
cat.data = Enrichment(FDR)

```


```{r echo = F}

## BP, CC, or MF
GO.ontology = 'BP'

##can select which categories ot include or say 'sigs.only'
usecats=c(1:20)
#usecats = 'sigs.only'

GO20(cat.data, GO.ontology, FC, FDR, usecats)

```
