---
title: "FullMetabolicPathway"
author: "John Santiago"
date: "2026-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}

library(plotly)
git.dir = "https://raw.githubusercontent.com/johncsantiago/WhartonLab/refs/heads/master/GeneralDataFiles/"
metabFDR = read.csv(paste0(git.dir, "MetaboliteFDRs2.csv"), row.names = 1)
metabFC = read.csv(paste0(git.dir, "MetaboliteFCs2.csv"), row.names = 1)
metabFC$Metab = row.names(metabFC)
metabFDR$Metab = row.names(metabFDR)

temp.metab.ids = metabFC$KEGG
temp.metab.ids = unlist(strsplit(temp.metab.ids, split = " / "))
temp.metab.ids = unlist(strsplit(temp.metab.ids, split = "-"))
temp.metab.ids = temp.metab.ids[temp.metab.ids != "n/a"]

temp.FC = metabFC[metabFC$KEGG %in% intersect(temp.metab.ids, metabFC$KEGG),]
temp.FDR = metabFDR[metabFDR$KEGG %in% intersect(temp.metab.ids, metabFDR$KEGG),]

temp.FC$rowID = temp.FC$KEGG
temp.FDR$rowID = temp.FDR$KEGG
temp.metab.ids = setdiff(temp.metab.ids, temp.FC$KEGG)


i=1
while(i<=length(temp.metab.ids)){
  tempFC = metabFC[grep(temp.metab.ids[i], metabFC$KEGG),]
  tempFDR = metabFDR[grep(temp.metab.ids[i], metabFDR$KEGG),]
  
  tempFC$rowID = metabFC.ids[i]
  tempFDR$rowID = metabFC.ids[i]
  
  temp.FC = rbind(temp.FC, tempFC)
  temp.FDR = rbind(temp.FDR, tempFDR)
  i=i+1
}

row.names(temp.FC) = temp.FC$rowID
row.names(temp.FDR) = temp.FDR$rowID

metabFC = temp.FC[,c((ncol(temp.FC)-1),2:(ncol(temp.FC)-2))]
metabFDR = temp.FDR[,c((ncol(temp.FDR)-1),2:(ncol(temp.FDR)-2))]




dme01100 <- read.delim("/Users/johncsantiago/Documents/GitHub/WhartonLab/dme01100.txt", row.names = NULL, header = F, sep = " ")

start = grep("</entry>", dme01100$V5)

cpds = grep("compound", dme01100$V8)
cpd.names = substring(dme01100[cpds,"V7"],6, nchar(dme01100[cpds,"V7"]))
cpd.names = gsub("cpd:", "", cpd.names)
cpd.names = gsub("gl:", "", cpd.names)

cpd.info = as.list(cpd.names)
names(cpd.info) = cpd.names

i=1
while(i<=length(cpds)){
  cpd.info[[i]] =dme01100[(max(start[start<cpds[i]])+1):(min(start[start>cpds[i]])-1),5:18]
  i=i+1
}

cpd.coords = data.frame(Metab = NA_character_,
                        x = NA_integer_,
                        y = NA_integer_,
                        link = NA_character_)

i=1
while(i<=length(cpd.info)){
  name = names(cpd.info)[i]
  coords = cpd.info[[i]]
  link = coords[grep("link", coords$V9),"V9"]
  coords = coords[grep("type", coords$V14),]
  j=1
  while(j<=nrow(coords)){
    x = as.numeric(substring(coords[j,"V15"], 3, nchar(coords[j,"V15"])))
    y = as.numeric(substring(coords[j,"V16"], 3, nchar(coords[j,"V16"])))
    temp.cpd.coords = data.frame(Metab = name, 
                                 x = x, 
                                 y = y,
                                 link = link)
    cpd.coords = rbind(cpd.coords, temp.cpd.coords)
    j=j+1
  }
  i=i+1
}
cpd.coords = cpd.coords[-1,]
row.names(cpd.coords) = 1:nrow(cpd.coords)



metab.ids = unlist(strsplit(as.character(KEGG.Key), split = " / "))
metab.ids = unlist(strsplit(as.character(metab.ids), split = "-"))
metab.ids = intersect(metab.ids, names(cpd.info))

cpd.coords$bg = "grey"
cpd.coords[cpd.coords$Metab %in% metab.ids, "bg"] = "firebrick"


start = grep("</reaction>", dme01100$V5)

reacts = dme01100[min(start):max(start),]
substrates = reacts[grep("substrate", reacts$V9), "V11"]
products = reacts[grep("product", reacts$V9), "V11"]

snp = unique(c(substrates,products))
snp = gsub("name=cpd:", "", snp)
snp = gsub("name=gl:", "", snp)
snp = gsub("/>", "", snp)


all.cpd.coords = cpd.coords


xtras = c("C00080", "C00007", "C00001", "G00872",
          "C02075 C02588", "C02050", "C16163", "C16169",
          "C16168", "C21959", "C21967", "C16172",
          "C16173", "C03035", "G00169", "G00113",
          "G00170", "G00118", "G13354", "G13355", 
          "G13356", "G13046 C22963", "G13150 C22970",
          "G00142 C22972", "G13151 C22971",
          "G00124", "G13046 C22965", "C00004")


extra.metab = all.cpd.coords[all.cpd.coords$Metab %in% xtras,]
extra.metab$bg = "grey"

remove.extra = 
  data.frame(Metab = 
               c("C00080", "C00080", "C00080",
                 "C00080", "C00080", "C00007",
                 "C00001"),
             x =c(1772, 1772, 1631, 1702, 1702,
                  1596, 1596),
             y=c(3133, 3018, 3133, 3133, 3018,
                 3115, 3045))

extra.metab$ID = paste(extra.metab$Metab, extra.metab$x,extra.metab$y)
remove.extra$ID = paste(remove.extra$Metab, remove.extra$x,remove.extra$y)

extra.metab = extra.metab[!(extra.metab$ID %in% remove.extra$ID), ]

extra.metab = extra.metab[,c("Metab", "x", "y", "link", "bg")]


cpd.coords = cpd.coords[cpd.coords$Metab %in% snp,]

remove.nodes = 
  data.frame(Metab = 
               c("C00156", "C00008", "C00002", 
                 "C00006", "C02051", "C15972",
                 "C00031", "C00630", "C05223",
                 "C00288", "C00011", "C03771"),
                          x = c(1377, 1820, 1810,
                                1676, 1487, 1453,
                                823, 4511, 4148, 
                                4133, 4134, 4159),
                          y = c(2765, 3050, 3108,
                                2960, 2013, 1989,
                                1745, 1258, 2450, 
                                1957, 1988, 2199))

cpd.coords$ID = paste(cpd.coords$Metab,cpd.coords$x,cpd.coords$y)
remove.nodes$ID = paste(remove.nodes$Metab, remove.nodes$x,remove.nodes$y)
cpd.coords = cpd.coords[!(cpd.coords$ID %in% remove.nodes$ID), ]

cpd.coords = cpd.coords[,c("Metab", "x", "y", "link", "bg")]


cpd.coords = rbind(cpd.coords,extra.metab)
cpd.coords$link =gsub("link=", "", cpd.coords$link) 
cpd.coords$link =gsub(">", "", cpd.coords$link) 


start = grep("</entry>", dme01100$V5)

genes = grep("gene", dme01100$V8)
gene.names = substring(dme01100[genes,"V7"],6, nchar(dme01100[genes,"V7"]))
gene.info = as.list(gene.names)
names(gene.info) = gene.names

i=1
while(i<=length(genes)){
  gene.info[[i]] =dme01100[(max(start[start<genes[i]])+1):(min(start[start>genes[i]])-1),5:18]
  i=i+1
}

gene.coords = data.frame(Gene = NA_character_,
                         coords = NA_integer_,
                         reaction = NA_character_)

i=1
while(i<=length(gene.info)){
  name = names(gene.info)[i]
  coords = gene.info[[i]]
  reaction = substring(coords[1,"V9"], 10, nchar(coords[1,"V9"]))
  coords = coords[grep("type", coords$V14),]

  j=1
  while(j<=nrow(coords)){
    temp.coords = substring(coords[j,"V15"], 8, (nchar(coords[j,"V15"])-2))
    temp.gene.coords = data.frame(Gene = name,
                                  coords = temp.coords,
                                  reaction = reaction)
    gene.coords = rbind(gene.coords, temp.gene.coords)
    j=j+1
  }
  i=i+1
}
gene.coords = gene.coords[-1,]
row.names(gene.coords) = 1:nrow(gene.coords)

gene.reactions = unique(unlist(strsplit(gene.coords$reaction,
                          split = " ")))









```


```{r}

par(mar = c(1.25,0,0,0))


plot(x = cpd.coords$x,
     y = -cpd.coords$y,
     cex = .2,
     pch = 21,
     col = cpd.coords$bg,
     bg = cpd.coords$bg,
     axes = F,
     ylab = "",
     xlab = "")

i=1
while(i<=nrow(gene.coords)){
  temp.coords <-gene.coords[i, "coords"]
  nums <- as.numeric(strsplit(temp.coords, ",")[[1]])
  
  line_df <- data.frame(
    x = nums[c(TRUE, FALSE)],
    y = nums[c(FALSE, TRUE)]
    )
  
  lines(line_df$x, -line_df$y, col = "grey")
  points(line_df$x, -line_df$y, pch = 16, 
         cex = 0.1,
         col = "grey") 
  i=i+1
}

temp.coords <- "2358,806,2195,806,2195,806,2192,806,2189,805,2186,803,2184,801,2182,799,2180,797,2178,794,2177,791,2177,788,2177,788,2177,720,2177,720,2177,717,2178,714,2180,711,2182,709,2184,707,2186,705,2189,703,2192,702,2195,702,2195,702,2414,702,2414,702,2417,702,2420,703,2423,705,2425,707,2427,709,2429,711,2431,714,2432,717,2432,720,2432,720,2432,743"

nums <- as.numeric(strsplit(temp.coords, ",")[[1]])

line_df <- data.frame(
  x = nums[c(TRUE, FALSE)],
  y = nums[c(FALSE, TRUE)]
)

temp.coords2 <- "2177,827,2177,759,2177,759,2177,756,2176,754,2175,751,2173,749,2171,747,2169,745,2166,744,2164,743,2161,743,2161,743,2127,743"

nums2 <- as.numeric(strsplit(temp.coords2, ",")[[1]])

line_df2 <- data.frame(
  x = nums2[c(TRUE, FALSE)],
  y = nums2[c(FALSE, TRUE)]
)


lines(line_df$x, -line_df$y, col = "green")
points(line_df$x, -line_df$y, pch = 16, cex = 0.1,
       col = "green")

lines(line_df2$x, -line_df2$y, col = "deeppink")
points(line_df2$x, -line_df2$y, pch = 16, cex = 0.1,
       col = "deeppink")


points(x = cpd.coords$x[cpd.coords$bg == "lightgrey"],
       y = -cpd.coords$y[cpd.coords$bg == "lightgrey"],
       cex = .5,
       col = "grey",
       pch = 21,
       bg = "grey")

points(x = extra.metab$x,
       y = -extra.metab$y,
       cex = .5,
       col = "black",
       pch = 21,
       bg = "black")

points(x = cpd.coords$x[cpd.coords$bg == "firebrick"],
       y = -cpd.coords$y[cpd.coords$bg == "firebrick"],
       cex = .5,
       pch = 21,
       bg = "firebrick")



points(x=1000,
       y=-3000,
       pch =21,
       bg = "green")

```

```{r}

library(KEGGREST)

my.cpds <- c(
  "C00303","C02794","C00815","C07446","C16435","C00768","C00466",
  "C16438","C01718","C00542","C01073","C02571","C03145","C05984",
  "C02385","C00716","C03884","C01996","C01602","C00806","C00849",
  "C05198","C02057","C00943","C01551","C16433","C12269","C01420",
  "C02214","C02037","C17349","C01432","C03404","C00711","C02567",
  "C01536","C02470","C02455","C06255","C11695","C05330","C01817",
  "C00248","C01736","C02721","C04227","C02735","C15587","C03030",
  "C03672","C03339","C00736","C03783","C16436","C01799","C02979",
  "C01507","C01481","C02230","C02242","C03570","C02261","C03665",
  "C05145","C01074","C16439","C16434","C01933","C00612","C01029",
  "C01984","C07441","C04548"
)

my.cpds.full <- paste0("cpd:", my.cpds)

cpd.pathways <- keggLink("pathway", my.cpds.full)

pathway.df <- data.frame(
  compound = sub("cpd:", "", names(cpd.pathways)),
  pathway = sub("path:", "", cpd.pathways)
)

head(pathway.df)


cpds <- cpd.coords$Metab


all_compounds <- keggList("compound")

names_df <- data.frame(
  id = cpds,
  name = unname(all_compounds[cpds]),
  stringsAsFactors = FALSE
)

names_df

cpd.coords$Names[cpd.coords$Metab %in% names_df$id] = names_df$name

```


```{r}

temp = intersect(cpd.coords$Metab, metab.FC$KEGG)

temp = na.omit(metab.FC[metab.FC$KEGG %in% temp, c("KEGG", "GRxWT.C")])
cpd.coords$bg[cpd.coords$bg == "firebrick"] = "gold"

vdown = temp[temp$GRxWT.C< (-1), "KEGG"] 
down = temp[temp$GRxWT.C<0, "KEGG"] 
vup = temp[temp$GRxWT.C>1, "KEGG"] 
up = temp[temp$GRxWT.C>0, "KEGG"] 

cpd.coords$size = 4
cpd.coords[cpd.coords$Metab %in% down, "size"] = 6

cpd.coords[cpd.coords$Metab %in% vdown, "size"] = 12
cpd.coords[cpd.coords$Metab %in% up, "size"] = 6

cpd.coords[cpd.coords$Metab %in% vup, "size"] = 12

cpd.coords[cpd.coords$Metab %in% down, "bg"] = "deepskyblue"

cpd.coords[cpd.coords$Metab %in% vdown, "bg"] = "navy"
cpd.coords[cpd.coords$Metab %in% up, "bg"] = "deeppink"

cpd.coords[cpd.coords$Metab %in% vup, "bg"] = "firebrick"

# Convert gene.coords$coords into one long line dataframe
line_list <- lapply(seq_len(nrow(gene.coords)), function(i) {
  nums <- as.numeric(strsplit(gene.coords$coords[i], ",")[[1]])

  d <- data.frame(
    x = nums[c(TRUE, FALSE)],
    y = -nums[c(FALSE, TRUE)],
    line_id = gene.coords$Gene[i]
  )

  # NA row breaks the line before the next one
  rbind(d, data.frame(x = NA, y = NA, line_id = i))
})

lines_plot <- do.call(rbind, line_list)

fig <- plot_ly() %>%
  add_trace(
    data = lines_plot,
    x = ~x,
    y = ~y,
    type = "scattergl",
    mode = "lines",
    line = list(color = "black", width = 1),
    hoverinfo = "none",#"text",
    text = ~paste0("",
      "Name: ", line_id
      #"<br>ID: ", id,
      #"<br>Type: ", type
    ),
    showlegend = FALSE
  ) %>%
  add_trace(
    data = cpd.coords,
    x = ~x,
    y = ~-y,
    type = "scattergl",
    mode = "markers",
    marker = list(
      size = ~size,
      color = ~bg,
      line = list(color = ~bg, width = 1)
    ),
    text = ~paste0("",
      "Name: ", Names,
      "<br>x: ", x,
      "<br>y: ", y
    ),
    hoverinfo = "text",
    showlegend = FALSE
  ) %>%
  layout(
    xaxis = list(title = "", showgrid = FALSE, zeroline = FALSE),
    yaxis = list(
      title = "",
      showgrid = FALSE,
      zeroline = FALSE,
      scaleanchor = "x",
      scaleratio = 1
    ),
    plot_bgcolor = "white"
  )
fig <- fig %>%
  layout(
    xaxis = list(
      visible = FALSE
    ),
    yaxis = list(
      visible = FALSE
    )
  )


fig

```

