---
title: "Specific Gene or Metabolite Levels"
author: "John Santiago"
date: "2024-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include = F, echo = F}
source('https://raw.githubusercontent.com/johncsantiago/WhartonLab/refs/heads/master/Functions_OmicsQuickPlotFunctions.R')

```


```{r echo = F}

## Plot gene expression from G85R TKT RNAseq experiment
## ID needs to be the full or partial gene symbol or FBgn (case sensitive)

ID = "Zw"

plot.G85R(ID)
G85R.FC[GeneIDKey[GeneIDKey$Symbol == ID, "FBgn"],]
G85R.FDR[GeneIDKey[GeneIDKey$Symbol == ID, "FBgn"],]

```


```{r echo = F}

## Plot gene expression from A4V RNAseq experiment
## ID needs to be the full or partial gene symbol or FBgn (case sensitive)

ID = "FBgn0000635"
  
plot.A4V(ID)
```


```{r echo = F}

## Plot metabolite levels from the G85R TKT metabolomics experiment
## metabID needs to be the full or partial metabolite name as listed in the table (case sensitive)

metabID = "NADPH"

plot.metab(metabID)

```


```{r echo = F, fig.width= 10, fig.height=16}

## Plot gene expression from Single Cell RNAseq experiment
## gene name needs to be the full or partial gene symbol as listed in the table (case sensitive)

gene.name = "Sod1"

plot.serpe.allclusters(gene.name)

```


```{r echo = F, fig.width=16, fig.height=10}

## Plot expression of a gene set from Single Cell RNAseq experiment
## gene name needs to be the full or partial gene symbol as listed in the table (case sensitive)

heat.genes = c("dpp", "gbb", "put", "wit", "mav", "sax", "tkv")

serpe.heatmap(heat.genes)

```


```{r echo = F, fig.width=16, fig.height=10}

## Plot expression of a gene set from Single Cell RNAseq experiment
## gene name needs to be the full or partial gene symbol as listed in the table (case sensitive)

heat.genes = c("gbb", "dpp", "wit", "Mad", "put", "sax", "tkv", "mav", "babo", "Smox")

serpe.heatmap.noman(heat.genes)

```


```{r echo = F}
##Plot expression levels for a specific gene in the gbbOE dataset

ID = "Arc1"

plot.gbbOE(ID)

```

```{r echo = F}
##Plot expression levels for a specific gene in the gbb-null dataset


## WT = W1118
## KO = GBB1/GBB2 (both null alleles)
## Aaron and Catherine legend for RNAseq
## Whole larvae

ID = "Arc1"
  
plot.gbbKO(ID)

```



