---
title: "G85R Reversals"
author: "John Santiago"
date: "2026-02-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r echo = F}

library(plotly)
library(VennDiagram)
library(goseq)
library(org.Dm.eg.db)
library(rrvgo)
library(biomaRt)

# Set up fly database
fly = useMart("ensembl", dataset = "dmelanogaster_gene_ensembl")

# Get attributes (Fly Gene ID, Human Gene ID, Human Symbol)
ortho_bm <- getBM(attributes = c("ensembl_gene_id", 
                                 "hsapiens_homolog_ensembl_gene",
                                 "hsapiens_homolog_associated_gene_name",
                                 "hsapiens_homolog_orthology_confidence",
                                 "hsapiens_homolog_perc_id",
                                 "hsapiens_homolog_perc_id_r1"),
                  mart = fly)

##DIOPT data at: https://fgr.hms.harvard.edu/diopt



git.dir = "https://raw.githubusercontent.com/johncsantiago/WhartonLab/refs/heads/master/GeneralDataFiles/"

GeneIDKey = read.csv(paste0(git.dir, "GeneIDKey.csv"), row.names = 1)

G85R.geneFDR = read.csv(paste0(git.dir, "TKT.EdgeR.FDRTable2.csv"), row.names = 1)
                        
G85R.geneFC = read.csv(paste0(git.dir, "TKT.EdgeR.FCTable2.csv"), row.names = 1)

G85R.metabFDR = read.csv(paste0(git.dir, "MetaboliteFDRs2.csv"), row.names = 1)
G85R.metabFC = read.csv(paste0(git.dir, "MetaboliteFCs2.csv"), row.names = 1)

G85R.meancpm = read.csv(paste0(git.dir, "TKT_meancpmdata.csv"), row.names = 1)
G85R.meancpm.meta = read.csv(paste0(git.dir, "TKT_meancpmdatameta.csv"), row.names = 1)

KEGG.MetabKey = read.csv(paste0(git.dir, "RawMetabolomicData.csv"), row.names = 1)

KEGG.MetabKey = setNames(KEGG.MetabKey[-c(1:2), 2], row.names(KEGG.MetabKey)[-c(1:2)])

genesingo = readRDS(gzcon(url(paste0(git.dir, "genesingo.RData"))))

GenesInKegg = readRDS(gzcon(url(paste0(git.dir, "kegg.symbol2path.RData"))))

KEGG.Names = read.csv(paste0(git.dir, "KEGG.names.csv"), row.names = 1)

GO.Names = read.csv(paste0(git.dir, "GO.names.csv"), row.names = 1)

G85R.metabnorm = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/Metabolomics/NormalizedMetabolomicData.csv", row.names = 1)
G85R.metabmean = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/Metabolomics/MeanNormalizedMetabolomicData.csv", row.names = 1)
metab.id = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/Metabolomics/MetaboliteMultiKEGGIDKey.csv", row.names = 1)
metab.id = setNames(metab.id$metab, metab.id$KEGG)

# Connect to Ensembl Human database
human <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

library(org.Dm.eg.db)
genesingo=as.data.frame(org.Dm.egGO2ALLEGS)
genesingo$FBgn = setNames(GeneIDKey$FBgn, GeneIDKey$ensembl)[genesingo$gene_id]
genesingo$Symbol = setNames(GeneIDKey$Symbol, GeneIDKey$ensembl)[genesingo$gene_id]

A4V.cpm = read.csv(paste0(git.dir, "A4V.cpmdata.csv"), row.names = 1)

A4V.FDR = read.csv(paste0(git.dir, "A4V.FDRdata.csv"), row.names = 1)

A4V.FC = read.csv(paste0(git.dir, "A4V.FCdata.csv"), row.names = 1)

A4V.cats = (substring(colnames(A4V.cpm), 1, nchar(colnames(A4V.cpm))-1))
A4V.meancpm = A4V.cpm[,1:length(unique(A4V.cats))]
colnames(A4V.meancpm) = unique(A4V.cats)
i=1
while(i<=ncol(A4V.meancpm)){
  A4V.meancpm[,i] = apply(A4V.cpm[,A4V.cats==colnames(A4V.meancpm)[i]],
                          MARGIN = 1,
                          mean)
  i=i+1
}


```


```{r echo = F}

meancpm.cutoff = 10

GF = row.names(G85R.geneFDR)[G85R.geneFDR$GRxWT.FC <= 0.05]
GF = intersect(GF, row.names(G85R.meancpm)
               [apply(G85R.meancpm[,c("GR.F", "WT.F")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])

GM = row.names(G85R.geneFDR)[G85R.geneFDR$GRxWT.FC <= 0.05]
GM = intersect(GM, row.names(G85R.meancpm)
               [apply(G85R.meancpm[,c("GR.M", "WT.M")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])

DF = row.names(G85R.geneFDR)[G85R.geneFDR$GRDfxWT.F <= 0.05]
DF = intersect(GF, row.names(G85R.meancpm)
               [apply(G85R.meancpm[,c("TktDfGR.F", "WT.F")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])

DM = row.names(G85R.geneFDR)[G85R.geneFDR$GRDfxWT.M <= 0.05]
DM = intersect(GF, row.names(G85R.meancpm)
               [apply(G85R.meancpm[,c("TktDfGR.M", "WT.M")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])

OF = row.names(G85R.geneFDR)[G85R.geneFDR$GROExWT.F<= 0.05]
OF = intersect(GF, row.names(G85R.meancpm)
               [apply(G85R.meancpm[,c("TktOEGR.F", "WT.F")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])

OM = row.names(G85R.geneFDR)[G85R.geneFDR$GROExWT.M <= 0.05]
OM = intersect(GF, row.names(G85R.meancpm)
               [apply(G85R.meancpm[,c("TktOEGR.M", "WT.M")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])


GFU = intersect(GF,row.names(G85R.geneFC)[G85R.geneFC$GRxWT.FC>0])
GFD = intersect(GF,row.names(G85R.geneFC)[G85R.geneFC$GRxWT.FC<0])

GMU = intersect(GM,row.names(G85R.geneFC)[G85R.geneFC$GRxWT.MC>0])
GMD = intersect(GM,row.names(G85R.geneFC)[G85R.geneFC$GRxWT.MC<0])

DFU = intersect(DF,row.names(G85R.geneFC)[G85R.geneFC$GRDfxWT.F>0])
DFD = intersect(DF,row.names(G85R.geneFC)[G85R.geneFC$GRDfxWT.F<0])

DMU = intersect(DM,row.names(G85R.geneFC)[G85R.geneFC$GRDfxWT.M>0])
DMD = intersect(DM,row.names(G85R.geneFC)[G85R.geneFC$GRDfxWT.M<0])

OFU = intersect(OF,row.names(G85R.geneFC)[G85R.geneFC$GROExWT.F>0])
OFD = intersect(OF,row.names(G85R.geneFC)[G85R.geneFC$GROExWT.F<0])

OMU = intersect(OM,row.names(G85R.geneFC)[G85R.geneFC$GROExWT.M>0])
OMD = intersect(OM,row.names(G85R.geneFC)[G85R.geneFC$GROExWT.M<0])


AF3H = row.names(A4V.FDR)[A4V.FDR$AvS3FH<.05]

AF9H = row.names(A4V.FDR)[A4V.FDR$AvS9FH<.05]

AF40H = row.names(A4V.FDR)[A4V.FDR$AvS40FH<.05]

AF3H = intersect(AF3H, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A3FH", "A3FH")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])
AF9H = intersect(AF9H, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A9FH", "A9FH")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])
AF40H = intersect(AF40H, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A40FH", "A40FH")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])


AF3T = row.names(A4V.FDR)[A4V.FDR$AvS3FT<.05]
AF9T = row.names(A4V.FDR)[A4V.FDR$AvS9FT<.05]
AF40T = row.names(A4V.FDR)[A4V.FDR$AvS40FT<.05]

AF3T = intersect(AF3T, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A3FT", "A3FT")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])
AF9T = intersect(AF9T, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A9FT", "A9FT")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])
AF40T = intersect(AF40T, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A40FT", "A40FT")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])

AF3A = row.names(A4V.FDR)[A4V.FDR$AvS3FA<.05]
AF9A = row.names(A4V.FDR)[A4V.FDR$AvS9FA<.05]
AF40A = row.names(A4V.FDR)[A4V.FDR$AvS40FA<.05]

AF3A = intersect(AF3A, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A3FA", "A3FA")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])
AF9A = intersect(AF9A, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A9FA", "A9FA")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])
AF40A = intersect(AF40A, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A40FA", "A40FA")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])

AM3H = row.names(A4V.FDR)[A4V.FDR$AvS3MH<.05]
AM9H = row.names(A4V.FDR)[A4V.FDR$AvS9MH<.05]

AM3H = intersect(AM3H, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A3MH", "A3MH")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])
AM9H = intersect(AM9H, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A9MH", "A9MH")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])


AM3T = row.names(A4V.FDR)[A4V.FDR$AvS3MT<.05]
AM9T = row.names(A4V.FDR)[A4V.FDR$AvS9MT<.05]

AM3T = intersect(AM3T, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A3MT", "A3MT")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])
AM9T = intersect(AM9T, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A9MT", "A9MT")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])

AM3A = row.names(A4V.FDR)[A4V.FDR$AvS3MA<.05]
AM9A = row.names(A4V.FDR)[A4V.FDR$AvS9MA<.05]

AM3A = intersect(AM3A, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A3MA", "A3MA")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])
AM9A = intersect(AM9A, row.names(A4V.meancpm)
               [apply(A4V.meancpm[,c("A9MA", "A9MA")], 
                      MARGIN = 1, 
                      max) > meancpm.cutoff])

AF3HU = intersect(AF3H,row.names(A4V.FC)[A4V.FC$AvS3FH>0])
AF3HD = intersect(AF3H,row.names(A4V.FC)[A4V.FC$AvS3FH<0])

AF9HU = intersect(AF9H,row.names(A4V.FC)[A4V.FC$AvS9FH>0])
AF9HD = intersect(AF9H,row.names(A4V.FC)[A4V.FC$AvS9FH<0])

AF40HU = intersect(AF40H,row.names(A4V.FC)[A4V.FC$AvS40FH>0])
AF40HD = intersect(AF40H,row.names(A4V.FC)[A4V.FC$AvS40FH<0])

AF3TU = intersect(AF3T,row.names(A4V.FC)[A4V.FC$AvS3FT>0])
AF3TD = intersect(AF3T,row.names(A4V.FC)[A4V.FC$AvS3FT<0])

AF9TU = intersect(AF9T,row.names(A4V.FC)[A4V.FC$AvS9FT>0])
AF9TD = intersect(AF9T,row.names(A4V.FC)[A4V.FC$AvS9FT<0])

AF40TU = intersect(AF40T,row.names(A4V.FC)[A4V.FC$AvS40FT>0])
AF40TD = intersect(AF40T,row.names(A4V.FC)[A4V.FC$AvS40FT<0])

AF3AU = intersect(AF3A,row.names(A4V.FC)[A4V.FC$AvS3FA>0])
AF3AD = intersect(AF3A,row.names(A4V.FC)[A4V.FC$AvS3FA<0])

AF9AU = intersect(AF9A,row.names(A4V.FC)[A4V.FC$AvS9FA>0])
AF9AD = intersect(AF9A,row.names(A4V.FC)[A4V.FC$AvS9FA<0])

AF40AU = intersect(AF40A,row.names(A4V.FC)[A4V.FC$AvS40FA>0])
AF40AD = intersect(AF40A,row.names(A4V.FC)[A4V.FC$AvS40FA<0])

AM3HU = intersect(AM3H,row.names(A4V.FC)[A4V.FC$AvS3MH>0])
AM3HD = intersect(AM3H,row.names(A4V.FC)[A4V.FC$AvS3MH<0])

AM9HU = intersect(AM9H,row.names(A4V.FC)[A4V.FC$AvS9MH>0])
AM9HD = intersect(AM9H,row.names(A4V.FC)[A4V.FC$AvS9MH<0])

AM3TU = intersect(AM3T,row.names(A4V.FC)[A4V.FC$AvS3MT>0])
AM3TD = intersect(AM3T,row.names(A4V.FC)[A4V.FC$AvS3MT<0])

AM9TU = intersect(AM9T,row.names(A4V.FC)[A4V.FC$AvS9MT>0])
AM9TD = intersect(AM9T,row.names(A4V.FC)[A4V.FC$AvS9MT<0])

AM3AU = intersect(AM3A,row.names(A4V.FC)[A4V.FC$AvS3MA>0])
AM3AD = intersect(AM3A,row.names(A4V.FC)[A4V.FC$AvS3MA<0])

AM9AU = intersect(AM9A,row.names(A4V.FC)[A4V.FC$AvS9MA>0])
AM9AD = intersect(AM9A,row.names(A4V.FC)[A4V.FC$AvS9MA<0])


geneIDs = unique(c(row.names(G85R.geneFDR), row.names(A4V.FDR)))

gene.table = data.frame(GFD = rep(0, length(geneIDs)),
                        GFU = rep(0, length(geneIDs)),
                        GMD = rep(0, length(geneIDs)),
                        GMU = rep(0, length(geneIDs)),
                        
                        DFD = rep(0, length(geneIDs)),
                        DFU = rep(0, length(geneIDs)),
                        OFD = rep(0, length(geneIDs)),
                        OFU = rep(0, length(geneIDs)),
                        
                        DMD = rep(0, length(geneIDs)),
                        DMU = rep(0, length(geneIDs)),
                        OMD = rep(0, length(geneIDs)),
                        OMU = rep(0, length(geneIDs)),
                        
                        AF3HD = rep(0, length(geneIDs)),
                        AF3HU = rep(0, length(geneIDs)),
                        AF9HD = rep(0, length(geneIDs)),
                        AF9HU = rep(0, length(geneIDs)),
                        AF40HD = rep(0, length(geneIDs)),
                        AF40HU = rep(0, length(geneIDs)),
                        
                        AM3HD = rep(0, length(geneIDs)),
                        AM3HU = rep(0, length(geneIDs)),
                        AM9HD = rep(0, length(geneIDs)),
                        AM9HU = rep(0, length(geneIDs)),
                        
                        AF3TD = rep(0, length(geneIDs)),
                        AF3TU = rep(0, length(geneIDs)),
                        AF9TD = rep(0, length(geneIDs)),
                        AF9TU = rep(0, length(geneIDs)),
                        AF40TD = rep(0, length(geneIDs)),
                        AF40TU = rep(0, length(geneIDs)),
                        
                        AM3TD = rep(0, length(geneIDs)),
                        AM3TU = rep(0, length(geneIDs)),
                        AM9TD = rep(0, length(geneIDs)),
                        AM9TU = rep(0, length(geneIDs)),
                        
                        AF3AD = rep(0, length(geneIDs)),
                        AF3AU = rep(0, length(geneIDs)),
                        AF9AD = rep(0, length(geneIDs)),
                        AF9AU = rep(0, length(geneIDs)),
                        AF40AD = rep(0, length(geneIDs)),
                        AF40AU = rep(0, length(geneIDs)),
                        
                        AM3AD = rep(0, length(geneIDs)),
                        AM3AU = rep(0, length(geneIDs)),
                        AM9AD = rep(0, length(geneIDs)),
                        AM9AU = rep(0, length(geneIDs)))

row.names(gene.table) = geneIDs

gene.table[GFD, "GFD"] = 1
gene.table[GFU, "GFU"] = 1
gene.table[GMD, "GMD"] = 1
gene.table[GMU, "GMU"] = 1

gene.table[DFD, "DFD"] = 1
gene.table[DFU, "DFU"] = 1
gene.table[OFD, "OFD"] = 1
gene.table[OFU, "OFU"] = 1

gene.table[DMD, "DMD"] = 1
gene.table[DMU, "DMU"] = 1
gene.table[OMD, "OMD"] = 1
gene.table[OMU, "OMU"] = 1

gene.table[AF3HD, "AF3HD"] = 1
gene.table[AF3HU, "AF3HU"] = 1
gene.table[AF9HD, "AF9HD"] = 1
gene.table[AF9HU, "AF9HU"] = 1
gene.table[AF40HD, "AF40HD"] = 1
gene.table[AF40HU, "AF40HU"] = 1

gene.table[AM3HD, "AM3HD"] = 1
gene.table[AM3HU, "AM3HU"] = 1
gene.table[AM9HD, "AM9HD"] = 1
gene.table[AM9HU, "AM9HU"] = 1

gene.table[AF3TD, "AF3TD"] = 1
gene.table[AF3TU, "AF3TU"] = 1
gene.table[AF9TD, "AF9TD"] = 1
gene.table[AF9TU, "AF9TU"] = 1
gene.table[AF40TD, "AF40TD"] = 1
gene.table[AF40TU, "AF40TU"] = 1

gene.table[AM3TD, "AM3TD"] = 1
gene.table[AM3TU, "AM3TU"] = 1
gene.table[AM9TD, "AM9TD"] = 1
gene.table[AM9TU, "AM9TU"] = 1

gene.table[AF3AD, "AF3AD"] = 1
gene.table[AF3AU, "AF3AU"] = 1
gene.table[AF9AD, "AF9AD"] = 1
gene.table[AF9AU, "AF9AU"] = 1
gene.table[AF40AD, "AF40AD"] = 1
gene.table[AF40AU, "AF40AU"] = 1

gene.table[AM3AD, "AM3AD"] = 1
gene.table[AM3AU, "AM3AU"] = 1
gene.table[AM9AD, "AM9AD"] = 1
gene.table[AM9AU, "AM9AU"] = 1

reverse.table = data.frame(GDFFD = rep(0, length(geneIDs)),
                           GDFFU = rep(0, length(geneIDs)),
                           GOEFD = rep(0, length(geneIDs)),
                           GOEFU = rep(0, length(geneIDs)),
                           GDFMD = rep(0, length(geneIDs)),
                           GDFMU = rep(0, length(geneIDs)),
                           GOEMD = rep(0, length(geneIDs)),
                           GOEMU = rep(0, length(geneIDs)))

row.names(reverse.table) = geneIDs

GDFFD = intersect(row.names(G85R.geneFDR)[G85R.geneFDR$GRF.CxDf < .05],
                  row.names(G85R.geneFC)[G85R.geneFC$GRF.CxDf < 0])

GDFFU = intersect(row.names(G85R.geneFDR)[G85R.geneFDR$GRF.CxDf < .05],
                  row.names(G85R.geneFC)[G85R.geneFC$GRF.CxDf > 0])

GOEFD = intersect(row.names(G85R.geneFDR)[G85R.geneFDR$GRF.CxOE < .05],
                  row.names(G85R.geneFC)[G85R.geneFC$GRF.CxOE < 0])

GOEFU = intersect(row.names(G85R.geneFDR)[G85R.geneFDR$GRF.CxOE < .05],
                  row.names(G85R.geneFC)[G85R.geneFC$GRF.CxOE > 0])

GDFMD = intersect(row.names(G85R.geneFDR)[G85R.geneFDR$GRM.CxDf < .05],
                  row.names(G85R.geneFC)[G85R.geneFC$GRM.CxDf < 0])

GDFMU = intersect(row.names(G85R.geneFDR)[G85R.geneFDR$GRM.CxDf < .05],
                  row.names(G85R.geneFC)[G85R.geneFC$GRM.CxDf > 0])

GOEMD = intersect(row.names(G85R.geneFDR)[G85R.geneFDR$GRM.CxOE < .05],
                  row.names(G85R.geneFC)[G85R.geneFC$GRM.CxOE < 0])

GOEMU = intersect(row.names(G85R.geneFDR)[G85R.geneFDR$GRM.CxOE < .05],
                  row.names(G85R.geneFC)[G85R.geneFC$GRM.CxOE > 0])

reverse.table[GDFFD, "GDFFD"] = 1
reverse.table[GDFFU, "GDFFU"] = 1
reverse.table[GOEFD, "GOEFD"] = 1
reverse.table[GOEFU, "GOEFU"] = 1
reverse.table[GDFMD, "GDFMD"] = 1
reverse.table[GDFMU, "GDFMU"] = 1
reverse.table[GOEMD, "GOEMD"] = 1
reverse.table[GOEMU, "GOEMU"] = 1



```


```{r echo = F}
library(gplots)

show.shared=function(chosen, min.num.shared, include, table = gene.table){
  ##Genes that are consistently different across models
  ##Up
  sub.table = table[,chosen]
  sub.table = row.names(sub.table[apply(sub.table, MARGIN = 1, sum) == length(chosen),])
  
  sub.table = gene.table[sub.table,include]
  
  min.num.shared = min.num.shared-1
  
  sub.table = sub.table[apply(sub.table, MARGIN = 1, sum)>length(chosen)+min.num.shared,]
  
  row.names(sub.table) = GeneIDKey[row.names(sub.table), "Symbol"]
  
  i=8
  gene.order = row.names(sub.table)[sub.table[,7]==1]
  while(i<=ncol(sub.table)){
    gene.order = c(gene.order, setdiff(row.names(sub.table)[sub.table[,i]==1], gene.order))
    i=i+1
  }
  
  sub.table = sub.table[gene.order,]
  sub.table = sub.table[order(apply(sub.table, MARGIN = 1, sum)),]
  
  lines = cumsum(rle(as.numeric(apply(sub.table, MARGIN = 1, sum)))$lengths)+.5
  row.colors = colorRampPalette(c("deepskyblue", "gold", "deeppink", "firebrick")) (ncol(sub.table)-length(chosen))[apply(sub.table, MARGIN = 1, sum)-length(chosen)]
  
  labelsize = 1
  if(nrow(sub.table)>10){
    labelsize = 1 -((nrow(sub.table)-40)/60)
  }
  if(nrow(sub.table)>40){
    labelsize = .5 -((nrow(sub.table)-40)/300)
  }
  if(labelsize<.1){
    labelsize = .1
  }
  
  heatmap(as.matrix(sub.table), 
        scale = "none", 
        Colv = NA, 
        Rowv = NA,
        RowSideColors = row.colors,
        add.expr = {
          abline(v=c(2.5,6.5,11.5,16.5), lty = c(1,1,1,1))
          abline(v=c(1.5,4.5,9.5,14.5,19.5), lty = c(2,2,2,2,2))
          abline(h = lines)
          },
        cexRow = labelsize)

}




```



```{r echo = F, fig.height=5, fig.width=5}

##Genes that are increased in G85R and not sensitive to TKT

#show.shared() uses data in gene.table
#columns required to have the DEG
chosen = c("GFU", "GMU", "DFU", "DMU", "OFU", "OMU")

#which columns to include from the plot
include = colnames(gene.table)[grep("U", colnames(gene.table))]
##number in addition to the chosen set
min.num.shared = 0

show.shared(chosen, min.num.shared, include)

```


```{r echo = F, fig.height=5, fig.width=5}

##Genes that are decreased in G85R and not sensitive to TKT

#show.shared() uses data in gene.table
#columns required to have the DEG
chosen = c("GFD", "GMD", "DFD", "DMD", "OFD", "OMD")
#which columns to include from the plot
include = colnames(gene.table)[grep("U", colnames(gene.table), invert = T)]
##number of comparisons that must share the DEG in addition to the chosen set
min.num.shared = 2

show.shared(chosen, min.num.shared, include)

```


```{r echo = F, fig.height=5, fig.width=5}

##Genes that are decreased in G85R/WT and significantly  increased in G85R,TKT-Df/G85R

#show.shared() uses data in gene.table
#columns required to have the DEG
chosen = c("GFD", "GMD")
#which columns to include from the plot
include = colnames(gene.table)[grep("U", colnames(gene.table), invert = T)]
##number of comparisons that must share the DEG in addition to the chosen set
min.num.shared = 5

reversed = gene.table[row.names(reverse.table)[reverse.table$GDFFU == 1 |
                                               reverse.table$GDFMU == 1 |
                                               reverse.table$GOEFU == 1 |
                                               reverse.table$GDFMU == 1],]

show.shared(chosen, min.num.shared, include, table = reversed)

```


```{r echo = F}

  ##Genes that are consistently different across models
  ##Up

table = cbind(gene.table[row.names(reversed),], reverse.table[row.names(reversed),])
include = c(colnames(table)[grep("U", colnames(table), invert = T)],
            colnames(reverse.table)[grep("U", colnames(reverse.table))])
min.num.shared = 5


  sub.table = table[,chosen]
  sub.table = row.names(sub.table[apply(sub.table, MARGIN = 1, sum) == length(chosen),])
  
  sub.table = table[sub.table,include]
  
  min.num.shared = min.num.shared-1
  
  sub.table = sub.table[apply(sub.table, MARGIN = 1, sum)>length(chosen)+min.num.shared,]
  
  row.names(sub.table) = GeneIDKey[row.names(sub.table), "Symbol"]
  
  i=8
  gene.order = row.names(sub.table)[sub.table[,7]==1]
  while(i<=ncol(sub.table)){
    gene.order = c(gene.order, setdiff(row.names(sub.table)[sub.table[,i]==1], gene.order))
    i=i+1
  }
  
  sub.table = sub.table[gene.order,]
  sub.table = sub.table[order(apply(sub.table, MARGIN = 1, sum)),]
  
  lines = cumsum(rle(as.numeric(apply(sub.table, MARGIN = 1, sum)))$lengths)+.5
  row.colors = colorRampPalette(c("deepskyblue", "gold", "deeppink", "firebrick")) (ncol(sub.table)-length(chosen))[apply(sub.table, MARGIN = 1, sum)-length(chosen)]
  
  labelsize = 1
  if(nrow(sub.table)>10){
    labelsize = 1 -((nrow(sub.table)-40)/60)
  }
  if(nrow(sub.table)>40){
    labelsize = .5 -((nrow(sub.table)-40)/300)
  }
  if(labelsize<.1){
    labelsize = .1
  }
  
  heatmap(as.matrix(sub.table), 
        scale = "none", 
        Colv = NA, 
        Rowv = NA,
        RowSideColors = row.colors,
        #add.expr = {
        #  abline(v=c(2.5,6.5,11.5,16.5), lty = c(1,1,1,1))
        #  abline(v=c(1.5,4.5,9.5,14.5,19.5), lty = c(2,2,2,2,2))
        #  abline(h = lines)
        #  },
        cexRow = labelsize)





```


```{r echo = F}

down.reverse.genes =  intersect(row.names(gene.table)[gene.table$GFD ==1 & gene.table$GMD == 1],row.names(reverse.table[reverse.table$GDFFU == 1 &
                reverse.table$GDFMU == 1,]))
#down.reverse.genes = intersect(down.reverse.genes, row.names(gene.table)[gene.table$DFD == 0 & gene.table$DFU == 0])

reverse = down.reverse.genes
  ##Genes that are consistently different across models
  ##Up

table = cbind(gene.table[reverse,], reverse.table[reverse,])
include = c(colnames(table)[grep("U", colnames(table), invert = T)],
            colnames(reverse.table)[grep("U", colnames(reverse.table))])
min.num.shared = 0


  sub.table = table[down.reverse.genes,chosen]
  sub.table = row.names(sub.table[apply(sub.table, MARGIN = 1, sum) == length(chosen),])
  
  sub.table = table[sub.table,include]
  
  min.num.shared = min.num.shared-1
  
  sub.table = sub.table[apply(sub.table, MARGIN = 1, sum)>length(chosen)+min.num.shared,]
  
  row.names(sub.table) = GeneIDKey[row.names(sub.table), "Symbol"]
  
  i=8
  gene.order = row.names(sub.table)[sub.table[,7]==1]
  while(i<=ncol(sub.table)){
    gene.order = c(gene.order, setdiff(row.names(sub.table)[sub.table[,i]==1], gene.order))
    i=i+1
  }
  
  sub.table = sub.table[gene.order,]
  sub.table = sub.table[order(apply(sub.table, MARGIN = 1, sum)),]
  
  lines = cumsum(rle(as.numeric(apply(sub.table, MARGIN = 1, sum)))$lengths)+.5
  row.colors = colorRampPalette(c("deepskyblue", "gold", "deeppink", "firebrick")) (ncol(sub.table)-length(chosen))[apply(sub.table, MARGIN = 1, sum)-length(chosen)]
  
  labelsize = 1
  if(nrow(sub.table)>10){
    labelsize = 1 -((nrow(sub.table)-40)/60)
  }
  if(nrow(sub.table)>40){
    labelsize = .5 -((nrow(sub.table)-40)/300)
  }
  if(labelsize<.1){
    labelsize = .1
  }
  
  heatmap(as.matrix(sub.table), 
        scale = "none", 
        Colv = NA, 
        Rowv = NA,
        RowSideColors = row.colors,
        #add.expr = {
        #  abline(v=c(2.5,6.5,11.5,16.5), lty = c(1,1,1,1))
        #  abline(v=c(1.5,4.5,9.5,14.5,19.5), lty = c(2,2,2,2,2))
        #  abline(h = lines)
        #  },
        cexRow = labelsize)
  
  
  ##All were sDEG between G85R and WT with a negative FC (male and female)
  ##All sere sDEG between G85R TKT-Df and G85R with a positive FC (male and female)
  ##mean cpm cutoff of at least 10 in G85R or WT
```


```{r echo = F}

up.reverse.genes =  intersect(row.names(gene.table)[gene.table$GFU ==1 & gene.table$GMU == 1],row.names(reverse.table[reverse.table$GDFFD == 1 &
                reverse.table$GDFMD == 1,]))
#up.reverse.genes = intersect(up.reverse.genes, row.names(gene.table)[gene.table$DFD == 0 & gene.table$DFU == 0])

reverse = up.reverse.genes
  ##Genes that are consistently different across models
  ##Up

chosen = c("GFU", "GMU")

table = cbind(gene.table[reverse,], reverse.table[reverse,])
include = c(colnames(table)[grep("U", colnames(table))],
            colnames(reverse.table)[grep("U", colnames(reverse.table), invert = T)])
min.num.shared = 0


  sub.table = table[up.reverse.genes,chosen]
  sub.table = row.names(sub.table[apply(sub.table, MARGIN = 1, sum) == length(chosen),])
  
  sub.table = table[sub.table,include]
  
  min.num.shared = min.num.shared-1
  
  sub.table = sub.table[apply(sub.table, MARGIN = 1, sum)>length(chosen)+min.num.shared,]
  
  row.names(sub.table) = GeneIDKey[row.names(sub.table), "Symbol"]
  
  i=8
  gene.order = row.names(sub.table)[sub.table[,7]==1]
  while(i<=ncol(sub.table)){
    gene.order = c(gene.order, setdiff(row.names(sub.table)[sub.table[,i]==1], gene.order))
    i=i+1
  }
  
  sub.table = sub.table[gene.order,]
  sub.table = sub.table[order(apply(sub.table, MARGIN = 1, sum)),]
  
  lines = cumsum(rle(as.numeric(apply(sub.table, MARGIN = 1, sum)))$lengths)+.5
  row.colors = colorRampPalette(c("deepskyblue", "gold", "deeppink", "firebrick")) (ncol(sub.table)-length(chosen))[apply(sub.table, MARGIN = 1, sum)-length(chosen)]
  
  labelsize = 1
  if(nrow(sub.table)>10){
    labelsize = 1 -((nrow(sub.table)-40)/60)
  }
  if(nrow(sub.table)>40){
    labelsize = .5 -((nrow(sub.table)-40)/300)
  }
  if(labelsize<.1){
    labelsize = .1
  }
  
  heatmap(as.matrix(sub.table), 
        scale = "none", 
        Colv = NA, 
        Rowv = NA,
        RowSideColors = row.colors,
        #add.expr = {
        #  abline(v=c(2.5,6.5,11.5,16.5), lty = c(1,1,1,1))
        #  abline(v=c(1.5,4.5,9.5,14.5,19.5), lty = c(2,2,2,2,2))
        #  abline(h = lines)
        #  },
        cexRow = labelsize)
  
  
  ##All were sDEG between G85R and WT with a negative FC (male and female)
  ##All sere sDEG between G85R TKT-Df and G85R with a positive FC (male and female)
  ##mean cpm cutoff of at least 10 in G85R or WT
```

```{r echo = F, fig.height=7, fig.width=7}
par(mfrow = c(2,2))

i=1
while(i<=length(down.reverse.genes)){
  plot.G85R(down.reverse.genes[i])
  i=i+1
}


```

```{r echo = F, fig.height=7, fig.width=7}
par(mfrow = c(2,2))

i=1
while(i<=length(up.reverse.genes)){
  plot.G85R(up.reverse.genes[i])
  i=i+1
}


```


```{r echo = F}

GRF = row.names(G85R.geneFDR)[G85R.FDR$GRxWT.FC <.05]
GRM = row.names(G85R.geneFDR)[G85R.FDR$GRxWT.FC <.05]


```



```{r echo = F, fig.height=10, fig.width=5}
##Down
sub.table = gene.table[,c("GFD", "GMD", "DFD", "DMD", "OFD", "OMD")]
sub.table = row.names(sub.table[apply(sub.table, MARGIN = 1, sum) == 6,])

sub.table = gene.table[sub.table,colnames(gene.table)[grep("U", colnames(gene.table), invert = T)]]
sub.table = sub.table[apply(sub.table, MARGIN = 1, sum)>6,]

row.names(sub.table) = GeneIDKey[row.names(sub.table), "Symbol"]

i=8
gene.order = row.names(sub.table)[sub.table[,7]==1]
while(i<=ncol(sub.table)){
  gene.order = c(gene.order, setdiff(row.names(sub.table)[sub.table[,i]==1], gene.order))
  i=i+1
}

sub.table = sub.table[gene.order,]
sub.table = sub.table[order(apply(sub.table, MARGIN = 1, sum)),]

lines = cumsum(rle(as.numeric(apply(sub.table, MARGIN = 1, sum)))$lengths)+.5



heatmap(as.matrix(sub.table), 
          scale = "none", 
          Colv = NA, 
          Rowv = NA,
        add.expr = {
          abline(v=c(2.5,6.5,11.5,16.5), lty = c(1,1,1,1))
          abline(v=c(1.5,4.5,9.5,14.5,19.5), lty = c(2,2,2,2,2))
          abline(h = lines)
          },
        cexRow = .25)

```


```{r echo = F}


##Plot levels of a specific metabolite
plot.metab = function(metabID){


ID.row = row.names(norm.data)[grep(metabID, row.names(norm.data))]

ID.row = metabID

if(length(ID.row) < 500){
if(length(ID.row) == 1){
metab = ID.row
name = ID.row

metab = data.frame(data = as.numeric(norm.data[metab,]), 
                   group = colnames(norm.data), 
                   geno = colnames(norm.data))


metab$group = factor(metab$group, levels = c("WT", "TktDfWT", "TktOEWT",
                                             "G85R", "TktDfGR", "TktOEGR"))

metab$geno = substr(metab$group, (nchar(as.character(metab$group))), nchar(as.character(metab$group)))

metab$geno[metab$geno == "R"] = "G85R"
metab$geno[metab$geno == "T"] = "WT"

metab$geno = factor(metab$geno, 
                     levels = c("WT", "G85R"))

par(mar = c(5,7,5,2))
plot(x = NA,
      y = NA,
     type = 'n',
     ylim = c(min(na.omit(metab$data)), max(na.omit(metab$data))),
     xlim = c(.5, 6.5),
     xaxt = "n",
     ylab="",
     yaxt = "n",
     xlab = NA)

#rect(0, 0-(1.5*max(gene$cpm)), 13, 1.5*max(gene$cpm), col = 'gray95')

boxplot(metab$data~metab$group, 
        xlab="",
        las = 2, 
        cex.axis = .8,
        xaxt = 'none',
        yaxt = 'none',
        boxwex = .75,
        boxlwd = 2,
        lwd = 2,
        cex.ticks = 2,
        add = T,
        col = c(rep("lightyellow", 3),
                rep("lightgreen", 3)))

box(lwd = 2)

points(x=as.numeric((metab$group)),
       y=metab$data,
       cex=1.25,
       pch=21,
       bg=c('gold3',"darkgreen")[as.numeric((metab$geno))])

axis(side = 1,
     at = 1:12,
     labels = rep(c("Control", "Df", "OE"), 4),
     line = 0,
     cex.axis = .75,
     lwd.ticks = 2)

axis(side = 2,
     line = 0,
     cex.axis = 1,
     lwd.ticks = 2,
     las = 2)

axis(side = 1,
     at = c(2, 5, 8, 11),
     labels = c("Silent", "G85R","Silent", "G85R"),
     tick = F,
     padj = 2,
     cex.axis = 1)

axis(side = 3,
     at = 3.5,
     labels = name,
     tick = F,
     padj = -.5,
     cex.axis = 1)

}

if(length(ID.row) != 1){
  ID.row
}

}
}


```


###Reversal genes analysis
```{r echo = F}

##FDf reversals
FC.data = G85R.geneFC[,c("GRxWT.FC", "GRDfxWT.F")]
FDR.data = G85R.geneFDR[,c("GRxWT.FC", "GRF.CxDf")]
##"GR.F"      "GR.M"      "TktDfGR.F" "TktDfGR.M"
##"TktDfWT.F" "TktDfWT.M" "TktOEGR.F" "TktOEGR.M"
##"TktOEWT.F" "TktOEWT.M" "WT.F"      "WT.M" 
mean.data = G85R.meancpm[,c("WT.F", "GR.F", "TktDfGR.F")]

gene.set = row.names(FC.data)

gene.set = intersect(gene.set,row.names(mean.data)[apply(mean.data, MARGIN = 1, sum)>5])

gene.set = intersect(gene.set, row.names(FDR.data)[FDR.data$GRxWT.FC < .05 &  FDR.data$GRF.CxDf < .05])

down.reversals = FC.data[FC.data$GRxWT.FC<0 & FC.data$GRDfxWT.F > FC.data$GRxWT.FC,]

down.reversals$Percent.reversed = (abs(down.reversals$GRxWT.FC) - abs(down.reversals$GRDfxWT.F))/abs(down.reversals$GRxWT.FC)

up.reversals = FC.data[FC.data$GRxWT.FC>0 & FC.data$GRDfxWT.F < FC.data$GRxWT.FC,]

up.reversals$Percent.reversed = ((up.reversals$GRxWT.FC) - (up.reversals$GRDfxWT.F))/(up.reversals$GRxWT.FC)

gene.set = intersect(gene.set, c(row.names(down.reversals)[down.reversals$Percent.reversed >.2], row.names(up.reversals)[up.reversals$Percent.reversed >.2]))

reversals = rbind(down.reversals, up.reversals)

FDf.reversals = reversals[intersect(gene.set, row.names(reversals)),]

##MDf reversals
FC.data = G85R.geneFC[,c("GRxWT.MC", "GRDfxWT.M")]
FDR.data = G85R.geneFDR[,c("GRxWT.MC", "GRM.CxDf")]
mean.data = G85R.meancpm[,c("WT.M", "GR.M", "TktDfGR.M")]

gene.set = row.names(FC.data)

gene.set = intersect(gene.set,row.names(mean.data)[apply(mean.data, MARGIN = 1, sum)>5])

gene.set = intersect(gene.set, row.names(FDR.data)[FDR.data$GRxWT.MC < .05 &  FDR.data$GRM.CxDf < .05])

down.reversals = FC.data[FC.data$GRxWT.MC<0 & FC.data$GRDfxWT.M > FC.data$GRxWT.MC,]

down.reversals$Percent.reversed = (abs(down.reversals$GRxWT.MC) - abs(down.reversals$GRDfxWT.M))/abs(down.reversals$GRxWT.MC)

up.reversals = FC.data[FC.data$GRxWT.MC>0 & FC.data$GRDfxWT.M < FC.data$GRxWT.MC,]

up.reversals$Percent.reversed = ((up.reversals$GRxWT.MC) - (up.reversals$GRDfxWT.M))/(up.reversals$GRxWT.MC)

gene.set = intersect(gene.set, c(row.names(down.reversals)[down.reversals$Percent.reversed >.2], row.names(up.reversals)[up.reversals$Percent.reversed >.2]))

reversals = rbind(down.reversals, up.reversals)

MDf.reversals = reversals[intersect(gene.set, row.names(reversals)),]


##FOE reversals
FC.data = G85R.geneFC[,c("GRxWT.FC", "GROExWT.F")]
FDR.data = G85R.geneFDR[,c("GRxWT.FC", "GRF.CxOE")]
mean.data = G85R.meancpm[,c("WT.F", "GR.F", "TktOEGR.F")]

gene.set = row.names(FC.data)

gene.set = intersect(gene.set,row.names(mean.data)[apply(mean.data, MARGIN = 1, sum)>5])

gene.set = intersect(gene.set, row.names(FDR.data)[FDR.data$GRxWT.FC < .05 &  FDR.data$GRF.CxOE < .05])

down.reversals = FC.data[FC.data$GRxWT.FC<0 & FC.data$GROExWT.F > FC.data$GRxWT.FC,]

down.reversals$Percent.reversed = (abs(down.reversals$GRxWT.FC) - abs(down.reversals$GROExWT.F))/abs(down.reversals$GRxWT.FC)

up.reversals = FC.data[FC.data$GRxWT.FC>0 & FC.data$GROExWT.F < FC.data$GRxWT.FC,]

up.reversals$Percent.reversed = ((up.reversals$GRxWT.FC) - (up.reversals$GROExWT.F))/(up.reversals$GRxWT.FC)

gene.set = intersect(gene.set, c(row.names(down.reversals)[down.reversals$Percent.reversed >.2], row.names(up.reversals)[up.reversals$Percent.reversed >.2]))

reversals = rbind(down.reversals, up.reversals)

FOE.reversals = reversals[intersect(gene.set, row.names(reversals)),]

##MOE reversals
FC.data = G85R.geneFC[,c("GRxWT.MC", "GROExWT.M")]
FDR.data = G85R.geneFDR[,c("GRxWT.MC", "GRM.CxOE")]
mean.data = G85R.meancpm[,c("WT.M", "GR.M", "TktOEGR.M")]

gene.set = row.names(FC.data)

gene.set = intersect(gene.set,row.names(mean.data)[apply(mean.data, MARGIN = 1, sum)>5])

gene.set = intersect(gene.set, row.names(FDR.data)[FDR.data$GRxWT.MC < .05 &  FDR.data$GRM.CxOE < .05])

down.reversals = FC.data[FC.data$GRxWT.MC<0 & FC.data$GROExWT.M > FC.data$GRxWT.MC,]

down.reversals$Percent.reversed = (abs(down.reversals$GRxWT.MC) - abs(down.reversals$GROExWT.M))/abs(down.reversals$GRxWT.MC)

up.reversals = FC.data[FC.data$GRxWT.MC>0 & FC.data$GROExWT.M < FC.data$GRxWT.MC,]

up.reversals$Percent.reversed = ((up.reversals$GRxWT.MC) - (up.reversals$GROExWT.M))/(up.reversals$GRxWT.MC)

gene.set = intersect(gene.set, c(row.names(down.reversals)[down.reversals$Percent.reversed >.2], row.names(up.reversals)[up.reversals$Percent.reversed >.2]))

reversals = rbind(down.reversals, up.reversals)

MOE.reversals = reversals[intersect(gene.set, row.names(reversals)),]

```


```{r echo = F}

##Metab Df reversals
FC.data = G85R.metabFC[,c("GRxWT.C", "GR.DfxWT.C")]
FDR.data = G85R.metabFDR[,c("GRxWT.C", "GR.DfxWT.C")]
mean.data = G85R.metabmean[,c("WT", "GR", "TktDfGR")]

gene.set = row.names(FC.data)

gene.set = intersect(gene.set,row.names(mean.data)[apply(mean.data, MARGIN = 1, sum)>5])

gene.set = intersect(gene.set, row.names(FDR.data)[FDR.data[,1] < .05])

down.reversals = FC.data[FC.data[,1]<0 & FC.data[,2] > FC.data[,1],]

down.reversals$Percent.reversed = (abs(down.reversals[,1]) - abs(down.reversals[,2]))/abs(down.reversals[,1])

up.reversals = FC.data[FC.data[,1]>0 & FC.data[,2] < FC.data[,1],]

up.reversals$Percent.reversed = ((up.reversals[,1]) - (up.reversals[,2]))/(up.reversals[,1])

gene.set = intersect(gene.set, c(row.names(down.reversals)[down.reversals$Percent.reversed >.2], row.names(up.reversals)[up.reversals$Percent.reversed >.2]))

reversals = rbind(down.reversals, up.reversals)

MetabDf.reversals = reversals[intersect(gene.set, row.names(reversals)),]

##Metab OE reversals
FC.data = G85R.metabFC[,c("GRxWT.C", "GR.OExWT.C")]
FDR.data = G85R.metabFDR[,c("GRxWT.C", "GR.OExWT.C")]
mean.data = G85R.metabmean[,c("WT", "GR", "TktOEGR")]

gene.set = row.names(FC.data)

gene.set = intersect(gene.set,row.names(mean.data)[apply(mean.data, MARGIN = 1, sum)>5])

gene.set = intersect(gene.set, row.names(FDR.data)[FDR.data[,1] < .05])

down.reversals = FC.data[FC.data[,1]<0 & FC.data[,2] > FC.data[,1],]

down.reversals$Percent.reversed = (abs(down.reversals[,1]) - abs(down.reversals[,2]))/abs(down.reversals[,1])

up.reversals = FC.data[FC.data[,1]>0 & FC.data[,2] < FC.data[,1],]

up.reversals$Percent.reversed = ((up.reversals[,1]) - (up.reversals[,2]))/(up.reversals[,1])

gene.set = intersect(gene.set, c(row.names(down.reversals)[down.reversals$Percent.reversed >.2], row.names(up.reversals)[up.reversals$Percent.reversed >.2]))

reversals = rbind(down.reversals, up.reversals)

MetabOE.reversals = reversals[intersect(gene.set, row.names(reversals)),]

```


```{r echo = F}


##Sample titles as strings. Only fill in up to your number of selected categories
set1="G85R-Df Reversal Metab."
set2="G85R-OE Reversal Metab."
  
##items to be compared (ex: gene names) as a 1 dimensional vectors. Only give inputs up to your number of selected categories
s1=row.names(MetabDf.reversals)
s2=row.names(MetabOE.reversals)

main = ""

##2-way Venn

  grid.newpage()
draw.pairwise.venn(area1=length(s1),area2=length(s2),cross.area=length(intersect(s1,s2)),fill = c("blue","red"),cex=1.5,cat.cex = 1,category = c(set1,set2), main = "main",
                   cat.pos = c(-20,10))



```

```{r echo = F, fig.height=9, fig.width=9}



par(mfrow = c(3,3))
i=1
while(i<=9){
  metabID = setdiff(s1,s2)[i]
  plot.metab(metabID)
  i=i+1
}

```


```{r echo = F, fig.height=9, fig.width=12}

par(mfrow = c(3,4))
i=1
while(i<=12){
  metabID = intersect(s1,s2)[i]
  plot.metab(metabID)
  i=i+1
}

```



```{r echo = F, fig.height=9, fig.width=9}

par(mfrow = c(3,3))
i=1
while(i<=7){
  metabID = setdiff(s2,s1)[i]
  plot.metab(metabID)
  i=i+1
}

```

```{r echo = F}

library(VennDiagram)

 ##Sample titles as strings. Only fill in up to your number of selected categories
  set1="Female TKT-Df"
  set2="Male TKT-Df"
  set3="Female TKT-OE"
  set4="Male TKT-OE"
  
  ##items to be compared (ex: gene names) as a 1 dimensional vectors. Only give inputs up to your number of selected categories
  s1 = row.names(FDf.reversals)
  s2 = row.names(MDf.reversals)
  s3 = row.names(FOE.reversals)
  s4 = row.names(MOE.reversals)
  
  main = 
  
  grid.newpage()
  tempvenn=draw.quad.venn(area1=length(s1),area2=length(s2),area3=length(s3),area4=length(s4), n12=length(intersect(s1,s2)),n13 = length(intersect(s1,s3)),n14 = length(intersect(s1,s4)),n23 = length(intersect(s2,s3)),n24 = length(intersect(s2,s4)),n34 = length(intersect(s3,s4)),n123 =  length(intersect(s1,intersect(s2,s3))),n124 =  length(intersect(s1,intersect(s2,s4))), n134 = length(intersect(s1,intersect(s3,s4))),n234 = length(intersect(s2,intersect(s3,s4))),n1234 = length(intersect(s1,intersect(s2,intersect(s3,s4)))),category =c(set1,set2,set3,set4),fill = c("blue", "red","green","yellow"),cex=2,cat.cex = 1, title = "main")

```


###Upset of reversal genes
```{r echo = F, fig.width=10, fig.height=5}

library(UpSetR)

reversals = list(s1,s2,s3,s4)
names(reversals) = c(set1,set2,set3,set4)

temp = upset(fromList(reversals))

temp


genes = unique(c(s1,s2,s3,s4))
upset.df = temp$New_data
row.names(upset.df) = genes




reversal.overlap = matrix(rep("", 15*nrow(upset.df)), ncol = 15)
row.names(reversal.overlap) = genes
colnames(reversal.overlap) = 1:15

comparison.df = matrix(rep(0,60), ncol = 4)
colnames(comparison.df) = colnames(upset.df)
row.names(comparison.df) = 1:15


comparison.df[c(4,6,8,10:12,14:15), "Male TKT-OE"] = 1
comparison.df[c(3,6:7,9,11,13:15), "Male TKT-Df"] = 1
comparison.df[c(2,5,8:9,12:15), "Female TKT-OE"] = 1
comparison.df[c(1,5,7,10:13,15), "Female TKT-Df"] = 1

i=1
while(i<=ncol(reversal.overlap)){
  reversals.seti = upset.df[colnames(comparison.df)[comparison.df[i,]==1]]
  reversals.seti = row.names(reversals.seti)[apply(reversals.seti, MARGIN = 1, sum) == sum(comparison.df[i,]==1)]
  not.reversals.seti = upset.df[colnames(comparison.df)[comparison.df[i,]==0]]
  not.reversals.seti = row.names(not.reversals.seti)[apply(not.reversals.seti, MARGIN = 1, sum) == 0]  
  reversal.overlap[intersect(reversals.seti, not.reversals.seti),i] = intersect(reversals.seti, not.reversals.seti)
  temp.colname = colnames(comparison.df)[comparison.df[i,]==1][1]
  j=2
  while(j<=length(colnames(comparison.df)[comparison.df[i,]==1])){
    temp.colname = paste0(temp.colname, ",", colnames(comparison.df)[comparison.df[i,]==1][j])
    j=j+1
  }
  colnames(reversal.overlap)[i] = temp.colname
  reversal.overlap[,i] =
    reversal.overlap[order(reversal.overlap[,i], decreasing = T),i]
  i=i+1
}


#write.csv(reversal.overlap, "/Users/johncsantiago/Desktop/Reversal.Intersect.GeneList.csv")

```



##Enrichement
```{r echo = F}
RescueGene.Enrichment = function(gene.set){
  sigs = row.names(gene.set)
  bg = row.names(G85R.geneFDR)
  
  
  sigsKEY = GeneIDKey[sigs,]
  sigs = na.omit(sigsKEY$Symbol)
  bgKEY = GeneIDKey[bg,]
  bg = na.omit(bgKEY$Symbol)
  
  genes = setNames(rep(0, length(bg)), bg)
  genes[sigs] = 1
  pwf=nullp(genes,"dm3","geneSymbol")
  GO.wall=goseq(pwf,"dm3","geneSymbol")
  GO.wall$adjp=p.adjust(GO.wall$over_represented_pvalue,method="BH")
  row.names(GO.wall) = GO.wall$category
  KEGG=goseq(pwf,gene2cat=GenesInKegg)
  KEGG$adjp=p.adjust(KEGG$over_represented_pvalue,method="BH")
  row.names(KEGG)=substr(as.character(KEGG[,1]),6,13)
  KEGG$Name=KEGG.Names[row.names(KEGG),1]
  
  enrichment.data = list(GO.wall, KEGG)
  names(enrichment.data) = c("GO", "KEGG")
  return(enrichment.data)
}

  
```

```{r echo = F, fig.keep='none'}

gene.set = FDf.reversals
FDf.reversal.Enrichment = RescueGene.Enrichment(gene.set)

gene.set = MDf.reversals
MDf.reversal.Enrichment = RescueGene.Enrichment(gene.set)

gene.set = FOE.reversals
FOE.reversal.Enrichment = RescueGene.Enrichment(gene.set)

gene.set = MOE.reversals
MOE.reversal.Enrichment = RescueGene.Enrichment(gene.set)

```


```{r echo = F}

RescueGene.GO = function(cat.data, compare, reversal.data){
  
  GO.data = cat.data$GO
  
  FC.data = setNames(G85R.geneFC[,compare],
                     row.names(G85R.geneFC))
  FDR.data = setNames(G85R.geneFDR[,compare],
                      row.names(G85R.geneFDR))
  
  
  GO.data = GO.data[GO.data$adjp <.05,
                    c("category", "term","adjp", "numDEInCat", "numInCat")]
  
  data = GO.data[,c("term","adjp","numDEInCat", "numInCat", "category")]
  
  if(nrow(data) > 20){
    data = data[1:20,]
  }
  
  
  data$Score = -log10(data$adjp)
  
  temp = nchar(data$term)
  data$label = data$term
  ##data$label[temp > 40] = paste0(substr(data$term[temp>40], 1 ,35), "...")
  
  data$term = factor(data$term, levels = c(unique(data$term)))
  data$up = 0
  data$down = 0
  data$allup = 0
  data$alldown = 0
  data$mean.rescue = 0
  sigs = row.names(reversal.data)
  
  i = 1
  while(i <= nrow(data)){
    go.id = row.names(data)[i]
    go.genes = genesingo[[go.id]]
    go.genes = GeneIDKey[GeneIDKey$ensembl %in% go.genes, "FBgn"]
    go.genes = intersect(go.genes, names(FC.data))
    sig.go.genes = intersect(go.genes, sigs)
    go.FC = FC.data[go.genes]
    sig.go.FC = FC.data[sig.go.genes]  
    
    data$allup[i] = length(go.FC[go.FC>0])
    data$alldown[i] = length(go.FC[go.FC<0])
    data$up[i] = length(sig.go.FC[sig.go.FC>0])
    data$down[i] = length(sig.go.FC[sig.go.FC<0])
    data$mean.rescue[i] = mean(reversal.data[sig.go.genes, "Percent.reversed"])
    i = i +1
  }
  
  data$down = data$down * -1
  data$alldown = data$alldown * -1
  
  m <- list(
    l = 50,
    r = 50,
    b = 100,
    t = 100,
    pad = 4
  )
  
  data$label = factor(data$label, levels = data$label)
  
  fig <- plot_ly(data, 
                 x = ~up, y = ~label, 
                 type = 'bar',
                 name = "Sig. Increased FC",
                 marker = list(color = 'brown',
                               line = list(color = "black", 
                                           width = 1.5)),
                 hoverinfo = "text",
                 hovertext = paste("Sample:", data$term,
                                   "\nGO ID: ", data$category,
                                   "\nTotal DE: ", data$down + data$up,
                                   "\nTotal in Cat.: ", data$allup + data$alldown,
                                   "\nDE up: ", data$up,
                                   "\nDE down: ", data$down,
                                   "\nFDR: ", signif(data$adjp, 3),
                                   "\nmean % reversal: ", signif(data$mean.rescue*100, 3))) %>%
    add_trace(x = ~down, 
              y ~term, 
              marker = list(color = 'steelblue', 
                            line = list(color = "black", width = 1.5)), 
              name = "Sig. Decreased FC")%>%
    
    layout(xaxis = list(title = "Number of Genes"),
           yaxis = list(title = ""),
           title = paste0(""),
           margin = m, barmode = 'overlay')
  
  return(fig)
}


```


```{r echo = F}

cat.data = FDf.reversal.Enrichment
compare = "GRxWT.FC"
reversal.data = FDf.reversals
RescueGene.GO(cat.data, compare, reversal.data)

cat.data = MDf.reversal.Enrichment
compare = "GRxWT.MC"
reversal.data = MDf.reversals
RescueGene.GO(cat.data, compare, reversal.data)

cat.data = FOE.reversal.Enrichment
compare = "GRxWT.FC"
reversal.data = FOE.reversals
RescueGene.GO(cat.data, compare, reversal.data)


##NO SIG CATS
#cat.data = MOE.reversal.Enrichment
#compare = "GRxWT.MC"
#reversal.data = MOE.reversals
#RescueGene.GO(cat.data, compare, reversal.data)

```


```{r echo = F}

plotgo.genes = function(specific.go, compare, mean.data, reversal.data){
  
  FC.data = setNames(G85R.geneFC[,compare],
                     row.names(G85R.geneFC))
  FDR.data = setNames(G85R.geneFDR[,compare],
                      row.names(G85R.geneFDR))
  
  ##select F if you want point size to scale with mean cpm of variable data
  set.size = F
  ##select T if you only want the genes in category to show
  catgenes.only = T
  
  volcano.data = data.frame(Symbol = GeneIDKey[names(FDR.data), "Symbol"], 
                            FBgn = names(FDR.data),
                            FDR = -log2(FDR.data),
                            FC = FC.data,
                            Color = 'grey',
                            size = 5*log(mean.data[names(FDR.data),1]),
                            Variable.cpm = mean.data[names(FDR.data),1],
                            Control.cpm = mean.data[names(FDR.data),2])
  
  if(set.size == T){
    volcano.data$size = 15
    volcano.data$size[volcano.data$FDR <= -log2(.05)] = 5
  }
  
  
  go.id = row.names(GO.Names)[GO.Names$term == specific.go]
  go.genes = (genesingo[go.id])[[1]]
  go.genes = GeneIDKey[GeneIDKey$ensembl %in% go.genes, 'Symbol']
  volcano.data$Color = 'honeydew'
  #row.names(volcano.data) = volcano.data$Symbol
  volcano.data[volcano.data$FBgn %in% row.names(reversal.data), 'Color'] = 'deeppink'
  volcano.data = volcano.data[order(volcano.data$Color, decreasing = T),]
  main.title = GO.Names[go.id, 'term']

  
  volcano.data = volcano.data[volcano.data$Symbol %in% go.genes,]
  
  
  fig = plot_ly(data = volcano.data,
                x = ~FC,
                y = ~FDR,
                type = 'scatter',
                mode = 'markers',
                marker = list(color = ~Color, colors = ~Color, size = volcano.data$size,
                              line = list(color = 'black', width = .5)),
                hoverinfo = "text",
                hovertext = paste("Gene:", volcano.data$Symbol,
                                  "\nFBgn:", volcano.data$FBgn,
                                  "\n-log2(FDR): ", round(volcano.data$FDR,2),
                                  "\nFC: ", round(volcano.data$FC,2),
                                  "\n ", colnames(mean.data)[1], "mean cpm: ",
                                  round(volcano.data$Variable.cpm, 1),
                                  "\n ", colnames(mean.data)[2], "mean cpm: ",
                                  round(volcano.data$Control.cpm, 1)))
  fig = fig %>% layout(title = main.title)
  
  
  return(fig)
}

```



```{r echo = F}

specific.go = "neurogenesis"
compare = "GRxWT.FC"
mean.data = G85R.meancpm[,c("GR.F","WT.F")]
reversal.data = FDf.reversals
plotgo.genes(specific.go, compare, mean.data, reversal.data)

```


```{r echo = F}
comparego.reversalgenes = function(specific.go, compare1, compare2, mean.data, reversal.data){
  
  FC.data = G85R.geneFC[,c(compare1, compare2)]
  FDR.data = G85R.geneFDR[,c(compare1, compare2)]
  
  go.id = row.names(GO.Names)[GO.Names$term == specific.go]
  
  go.genes = (genesingo[go.id])[[1]]
  go.genes = GeneIDKey[GeneIDKey$ensembl %in% go.genes, 'FBgn']
  
  
data = data.frame(Symbol = GeneIDKey[go.genes, "Symbol"],
                  FBgn = go.genes,
                  FDR1 = -log2(FDR.data[go.genes, 1]),
                  FDR2 = -log2(FDR.data[go.genes, 2]),
                  FC1 = FC.data[go.genes, 1],
                  FC2 = FC.data[go.genes, 2],
                  Color = 'grey',
                  size = 1,
                  Variable1.cpm = mean.data[go.genes,1],
                  Control1.cpm = mean.data[go.genes,2],
                  Variable2.cpm = mean.data[go.genes,3],
                  Control2.cpm = mean.data[go.genes,4])

  main.title = GO.Names[go.id, 'term']
  
  #data$Color[(data$FC1 - 1) > data$FC2] = 'royalblue'
  #data$Color[(data$FC2 - 1) > data$FC1] = 'firebrick' 
  data$Color[data$FBgn %in% row.names(reversal.data)] = "deeppink"
  data$size = 2.5*apply(data[,c('FDR1', 'FDR2')], MARGIN = 1, max)
  data$size[data$size < -2.5*log2(.05)] = 5
  data = na.omit(data)
  data$size[data$FBgn %in% setdiff(data$FBgn, row.names(reversal.data))] = 5
  
  fig = plot_ly(data = data,
                x = ~FC1,
                y = ~FC2,
                type = 'scatter',
                mode = 'markers',
                marker = list(color = ~Color,
                              colors = ~Color,
                              line = list(color = "black", width = 1.5),
                              size = ~size),
                hoverinfo = "text",
                hovertext = paste("Symbol:", data$Symbol,
                                  "\nFBgn:", data$FBgn,
                                  "\n ", colnames(FDR.data)[1], "FDR: ", round(2^-data$FDR1, 2),
                                  "\n ", colnames(FDR.data)[2], "FDR: ", round(2^-data$FDR2,2),
                                  "\n ", colnames(FC.data)[1], "FC: ", round(data$FC1, 2),
                                  "\n ", colnames(FC.data)[2], "FC: ", round(data$FC2,2),
                                  "\n ", colnames(mean.data)[1], "mean CPM: ", signif(data$Variable1,2),
                                  "\n ", colnames(mean.data)[2], "mean CPM: ", signif(data$Control1,2),
                                  "\n ", colnames(mean.data)[3], "mean CPM: ", signif(data$Variable2,2),
                                  "\n ", colnames(mean.data)[4], "mean CPM: ", signif(data$Control2,2)))
  fig = fig %>% layout(title = main.title,
                       shapes = list(
                         type = "line",
                         line = list(color = "black", dash = 'dash', width = 2),
                         x0 = min(data$FC1, data$FC2) - 1,
                         x1 = max(data$FC1, data$FC2) + 1,
                         y0 = min(data$FC1, data$FC2) - 1,
                         y1 = max(data$FC1, data$FC2) + 1),
                       xaxis = list(title = paste(colnames(FC.data)[1], "FC")),
                       yaxis = list(title = paste(colnames(FC.data)[2], "FC")))
  
  
  fig
}

```


```{r echo = F}

specific.go = "neurogenesis"
compare1 = "GRxWT.FC"
compare2 = "GRDfxWT.F"
mean.data = G85R.meancpm[,c("GR.F","WT.F", "TktDfGR.F", "WT.F")]
reversal.data = FDf.reversals
comparego.reversalgenes(specific.go, compare1, compare2, mean.data, reversal.data)

```


```{r echo = F}



tree = function(cat.data, GO.ontology){
  
  GO.data = cat.data$GO
  
  go_analysis = GO.data$category[GO.data$adjp <= .05 & 
                                   GO.data$ontology == GO.ontology]
  scores = setNames(-log10(GO.data[GO.data$category %in% go_analysis, "over_represented_pvalue"]), go_analysis)
  
  simMatrix <- calculateSimMatrix(go_analysis,
                                  orgdb="org.Dm.eg.db",
                                  ont=GO.ontology,
                                  method="Rel")
  
  reducedTerms <- reduceSimMatrix(simMatrix,
                                  scores,
                                  threshold=0.7,
                                  orgdb="org.Dm.eg.db")
  
  return(reducedTerms)
}

```

```{r echo = F}

#rtCC = tree(MDf.reversal.Enrichment, "CC")
treemapPlot(rtCC)

#rtBP = tree(MDf.reversal.Enrichment, "BP")
treemapPlot(rtBP)

#rtMF = tree(MDf.reversal.Enrichment, "MF")
treemapPlot(rtMF)
```


```{r}

rtCC2 = tree(MDf.reversal.Enrichment, "CC")
treemapPlot(rtCC2)

rtBP2 = tree(MDf.reversal.Enrichment, "BP")
treemapPlot(rtBP2)

rtMF2 = tree(MDf.reversal.Enrichment, "MF")
treemapPlot(rtMF2)

```


```{r echo = F}

plotparentcat.reversalgenes = function(parent.category, compare, mean.data){
  
  FC.data = setNames(G85R.geneFC[,compare],
                     row.names(G85R.geneFC))
  FDR.data = setNames(G85R.geneFDR[,compare],
                      row.names(G85R.geneFDR))
  
  #if(length(rt[rt$parentTerm == parent.category, "go"]) == 0){
  #  parent.category = rt$parentTerm[1]
  #}
  
  
  ##select F if you want point size to scale with mean cpm of variable data
  set.size = F
  ##select T if you only want the genes in category to show
  catgenes.only = T
  
  GOterm.genes = vector('list', length = length(unique(rt$parent)))
  names(GOterm.genes) = unique(rt$parent)
  
  i=1
  while(i<=length(GOterm.genes)){
    goinparent = rt[grep(names(GOterm.genes)[i], rt$parent),'go']
    genesinparent = unlist(genesingo[goinparent])
    GOterm.genes[[i]] = GeneIDKey[GeneIDKey$ensembl %in% genesinparent, 'FBgn']
    i = i +1
  }
  
  volcano.data = data.frame(Symbol = GeneIDKey[names(FDR.data), "Symbol"], 
                            FDR = -log2(FDR.data),
                            FC = FC.data,
                            Color = 'grey',
                            size = 5*log(mean.data[names(FDR.data),1]+2),
                            Variable.cpm = mean.data[names(FDR.data),1],
                            Control.cpm = mean.data[names(FDR.data),2],
                            GO.terms = "none")
  
  if(set.size == T){
    volcano.data$size = 15
    volcano.data$size[volcano.data$FDR <= -log2(.05)] = 5
  }
  
  parent.genes = GOterm.genes[[intersect(rt[rt$parentTerm == parent.category, "go"],
                                         names(GOterm.genes))]]
  parent.genes = intersect(parent.genes, row.names(volcano.data))
  volcano.data$Color = 'honeydew'
  volcano.data[parent.genes, 'Color'] = 'deeppink'
  volcano.data = volcano.data[order(volcano.data$Color, decreasing = T),]
  main.title = parent.category
  
  if(catgenes.only == T){
    volcano.data = volcano.data[volcano.data$Color == 'deeppink',]
    volcano.data$Color[volcano.data$FDR < -log2(.05)] = 'honeydew'
  }
  
  fig = plot_ly(data = volcano.data,
                x = ~FC,
                y = ~FDR,
                type = 'scatter',
                mode = 'markers',
                marker = list(color = ~Color, colors = ~Color, size = volcano.data$size,
                              line = list(color = 'black', width = .5)),
                hoverinfo = "text",
                hovertext = paste("Gene:", volcano.data$Symbol,
                                  "\n-log2(FDR): ", round(volcano.data$FDR,2),
                                  "\nFC: ", round(volcano.data$FC,2),
                                  "\n ", colnames(mean.data)[1], "mean cpm: ",
                                  round(volcano.data$Variable.cpm, 1),
                                  "\n ", colnames(mean.data)[2], "mean cpm: ",
                                  round(volcano.data$Control.cpm, 1)))
  fig = fig %>% layout(title = main.title)
  
  return(fig)
}

```



```{r echo = F}

#MDf.rt = tree(MDf.reversal.Enrichment, "BP")

parent.category = "fatty acid beta-oxidation"
compare = "GRxWT.MC"
mean.data = G85R.meancpm[,c("GR.M","WT.M")]
rt = rtBP2
plotparentcat.reversalgenes(parent.category, compare, mean.data)

```



```{r echo = F}

compareparent.reversalgenes = function(parent.category, compare1, compare2, mean.data, reversal.data){
  
  FC.data = G85R.geneFC[,c(compare1, compare2)]
  FDR.data = G85R.geneFDR[,c(compare1, compare2)]
  
  if(length(rt[rt$parentTerm == parent.category, "go"]) == 0){
    parent.category = rt$parentTerm[1]
  }
  
  ##select F if you want point size to scale with mean cpm of variable data
  set.size = F
  ##select T if you only want the genes in category to show
  catgenes.only = T
  
  GOterm.genes = vector('list', length = length(unique(rt$parent)))
  names(GOterm.genes) = unique(rt$parent)
  
  i=1
  while(i<=length(GOterm.genes)){
    goinparent = rt[grep(names(GOterm.genes)[i], rt$parent),'go']
    genesinparent = unlist(genesingo[goinparent])
    GOterm.genes[[i]] = GeneIDKey[GeneIDKey$ensembl %in% genesinparent, 'FBgn']
    i = i +1
  }
  
  parent.genes = GOterm.genes[[intersect(rt[rt$parentTerm == parent.category, "go"],
                                         names(GOterm.genes))]]
  parent.genes = intersect(parent.genes, row.names(FDR.data))
  
  
  data = data.frame(Symbol = GeneIDKey[parent.genes, "Symbol"],
                    FBgn = parent.genes,
                    FDR1 = -log2(FDR.data[parent.genes, 1]),
                    FDR2 = -log2(FDR.data[parent.genes, 2]),
                    FC1 = FC.data[parent.genes, 1],
                    FC2 = FC.data[parent.genes, 2],
                    Color = 'grey',
                    size = 1,
                    Variable1.cpm = mean.data[parent.genes,1],
                    Control1.cpm = mean.data[parent.genes,2],
                    Variable2.cpm = mean.data[parent.genes,3],
                    Control2.cpm = mean.data[parent.genes,4],
                    PercentReversal = 0)
  
  main.title = parent.category
  
  #data$Color[(data$FC1 - 1) > data$FC2] = 'royalblue'
  #data$Color[(data$FC2 - 1) > data$FC1] = 'firebrick' 
  
  data$Color[data$FBgn %in% row.names(reversal.data)] = "deeppink"
  
  data$size = 2.5*apply(data[,c('FDR1', 'FDR2')], MARGIN = 1, max)
  data$size[data$size < -2.5*log2(.05)] = 5
  data = na.omit(data)
  
  data$size[data$FBgn %in% setdiff(data$FBgn, row.names(reversal.data))] = 5
  
  fig = plot_ly(data = data,
                x = ~FC1,
                y = ~FC2,
                type = 'scatter',
                mode = 'markers',
                marker = list(color = ~Color,
                              colors = ~Color,
                              line = list(color = "black", width = 1.5),
                              size = ~size),
                hoverinfo = "text",
                hovertext = paste("Symbol:", data$Symbol,
                                  "\nFBgn:", data$FBgn,
                                  "\n ", colnames(FDR.data)[1], "FDR: ", round(2^-data$FDR1, 2),
                                  "\n ", colnames(FDR.data)[2], "FDR: ", round(2^-data$FDR2,2),
                                  "\n ", colnames(FC.data)[1], "FC: ", round(data$FC1, 2),
                                  "\n ", colnames(FC.data)[2], "FC: ", round(data$FC2,2),
                                  "\n ", colnames(mean.data)[1], "mean CPM: ", signif(data$Variable1,2),
                                  "\n ", colnames(mean.data)[2], "mean CPM: ", signif(data$Control1,2),
                                  "\n ", colnames(mean.data)[3], "mean CPM: ", signif(data$Variable2,2),
                                  "\n ", colnames(mean.data)[4], "mean CPM: ", signif(data$Control2,2)))
  fig = fig %>% layout(title = main.title,
                       shapes = list(
                         type = "line",
                         line = list(color = "black", dash = 'dash', width = 2),
                         x0 = min(data$FC1, data$FC2) - 1,
                         x1 = max(data$FC1, data$FC2) + 1,
                         y0 = min(data$FC1, data$FC2) - 1,
                         y1 = max(data$FC1, data$FC2) + 1),
                       xaxis = list(title = paste(colnames(FC.data)[1], "FC")),
                       yaxis = list(title = paste(colnames(FC.data)[2], "FC")))
  
  
  fig
}
```




```{r echo = F}

#MDf.rt = tree(MDf.reversal.Enrichment, "BP")

parent.category = "fatty acid beta-oxidation"
compare1 = "GRxWT.MC"
compare2 = "GRDfxWT.M"
mean.data = G85R.meancpm[,c("GR.M", "WT.M", "TktDfGR.M", "WT.M")]
reversal.data = MDf.reversals
compareparent.reversalgenes(parent.category, compare1, compare2, mean.data, reversal.data)

```



```{r echo = F}

RescueGene.KEGG = function(cat.data, compare, reversal.data){
  
  KEGG.data = cat.data$KEGG
  FC.data = setNames(G85R.geneFC[,compare],
                     row.names(G85R.geneFC))
  FDR.data = setNames(G85R.geneFDR[,compare],
                      row.names(G85R.geneFDR))
  
  
  data = KEGG.data[, c("category", "Name","adjp", "numDEInCat", "numInCat")]
  
  data$term = data$Name
  if(length(unique(data$term)) < length(data$term)){
    data$term[duplicated(data$term)] = paste(data$term[duplicated(data$term)], "2")
  }  
  data = na.omit(data[data$Name != 'Metabolic pathways',])
  data = data[data$adjp<0.05,]
  
  if(nrow(data)>20){
    data = data[1:20,]
  }

  data = data[nrow(data):1,]
  
  data$Score = -log10(data$adjp)
  data$term = factor(data$term, levels = c(unique(data$term)))
  data$up = 0
  data$down = 0
  data$allup = 0
  data$alldown = 0
  data$mean.rescue
  
  sigs = row.names(reversal.data)
  
  i = 1
  while(i <= nrow(data)){
    kegg.id = data$category[i]
    kegg.genes = names(GenesInKegg[grep(kegg.id, GenesInKegg)])
    kegg.genes = GeneIDKey[GeneIDKey$Symbol %in% kegg.genes, "FBgn"]
    kegg.genes = intersect(kegg.genes, names(FC.data))
    sig.kegg.genes = intersect(kegg.genes, sigs)
    kegg.FC = FC.data[kegg.genes]
    sig.kegg.FC = FC.data[sig.kegg.genes]
    data$allup[i] = length(kegg.FC[kegg.FC>0])
    data$alldown[i] = length(kegg.FC[kegg.FC<0])
    data$up[i] = length(sig.kegg.FC[sig.kegg.FC>0])
    data$down[i] = length(sig.kegg.FC[sig.kegg.FC<0])
    data$mean.rescue[i] = mean(reversal.data[sig.kegg.genes, "Percent.reversed"])
    i = i +1
  }
  
  data$down = data$down * -1
  data$alldown = data$alldown * -1
  
  
  m <- list(
    l = 50,
    r = 50,
    b = 100,
    t = 100,
    pad = 4
  )
  
  fig <- plot_ly(data,
                 x = ~up, y = ~term, 
                 type = 'bar',
                 name = "Sig. Increased FC",
                 marker = list(color = 'brown',
                               line = list(color = "black", 
                                           width = 1.5)),
                 hoverinfo = "text",
                 hovertext = paste("Sample:", data$term,
                                   "\nKEGG ID: ", data$category,
                                   "\nTotal DE: ", data$numDEInCat,
                                   "\nTotal in Cat.: ", data$numInCat,
                                   "\nDE up: ", data$up,
                                   "\nDE down: ", data$down,
                                   "\nFDR: ", signif(data$adjp, 3),
                                   "\nmean % reversal: ", signif(data$mean.rescue*100, 3))) %>%
    add_trace(x = ~down, 
              y ~term, 
              marker = list(color = 'steelblue', 
                            line = list(color = "black", 
                                        width = 1.5)), 
              name = "Sig. Decreased FC")%>%
    layout(xaxis = list(title = "Number of Genes"),
           yaxis = list(title = ""),
           title = paste0("Top 20 Most Enriched KEGG Terms"),
           margin = m, barmode = 'overlay')
  
  return(fig)
  
}


```


```{r echo = F}
##NO SIG CATS
#cat.data = FDf.reversal.Enrichment
#compare = "GRxWT.FC"
#reversal.data = FDf.reversals
#RescueGene.KEGG(cat.data, compare, reversal.data)

cat.data = MDf.reversal.Enrichment
compare = "GRxWT.MC"
reversal.data = MDf.reversals
RescueGene.KEGG(cat.data, compare, reversal.data)

cat.data = FOE.reversal.Enrichment
compare = "GRxWT.FC"
reversal.data = FOE.reversals
RescueGene.KEGG(cat.data, compare, reversal.data)



cat.data = MOE.reversal.Enrichment
compare = "GRxWT.MC"
reversal.data = MOE.reversals
RescueGene.KEGG(cat.data, compare, reversal.data)

```


```{r echo = F}


GRF = row.names(G85R.FDR)[G85R.FDR$GRxWT.FC < .05]
GRM = row.names(G85R.FDR)[G85R.FDR$GRxWT.MC < .05]

A4V.3FH = row.names(A4V.FDR)[A4V.FDR$AvS3FH < 0.05]
A4V.3MH = row.names(A4V.FDR)[A4V.FDR$AvS3MH < 0.05]

 ##Sample titles as strings. Only fill in up to your number of selected categories
  set1="A4V 3FH"
  set2="A4V 3MH"
  set3="G85R F"
  set4="G85R M"
  
  ##items to be compared (ex: gene names) as a 1 dimensional vectors. Only give inputs up to your number of selected categories
  s1 = A4V.3FH
  s2 = A4V.3MH
  s3 = GRF
  s4 = GRM
  main = 
  
grid.newpage()
tempvenn=draw.quad.venn(area1=length(s1),area2=length(s2),area3=length(s3),area4=length(s4), n12=length(intersect(s1,s2)),n13 = length(intersect(s1,s3)),n14 = length(intersect(s1,s4)),n23 = length(intersect(s2,s3)),n24 = length(intersect(s2,s4)),n34 = length(intersect(s3,s4)),n123 =  length(intersect(s1,intersect(s2,s3))),n124 =  length(intersect(s1,intersect(s2,s4))), n134 = length(intersect(s1,intersect(s3,s4))),n234 = length(intersect(s2,intersect(s3,s4))),n1234 = length(intersect(s1,intersect(s2,intersect(s3,s4)))),category =c(set1,set2,set3,set4),fill = c("blue", "red","green","yellow"),cex=2,cat.cex = 1, title = "main")

```



```{r echo = F}


A4V.9FH = row.names(A4V.FDR)[A4V.FDR$AvS9FH < 0.05]
A4V.9MH = row.names(A4V.FDR)[A4V.FDR$AvS9MH < 0.05]

 ##Sample titles as strings. Only fill in up to your number of selected categories
  set1="A4V 9FH"
  set2="A4V 9MH"
  set3="G85R F"
  set4="G85R M"
  
  ##items to be compared (ex: gene names) as a 1 dimensional vectors. Only give inputs up to your number of selected categories
  s1 = A4V.9FH
  s2 = A4V.9MH
  s3 = GRF
  s4 = GRM
  main = 
  
grid.newpage()
tempvenn=draw.quad.venn(area1=length(s1),area2=length(s2),area3=length(s3),area4=length(s4), n12=length(intersect(s1,s2)),n13 = length(intersect(s1,s3)),n14 = length(intersect(s1,s4)),n23 = length(intersect(s2,s3)),n24 = length(intersect(s2,s4)),n34 = length(intersect(s3,s4)),n123 =  length(intersect(s1,intersect(s2,s3))),n124 =  length(intersect(s1,intersect(s2,s4))), n134 = length(intersect(s1,intersect(s3,s4))),n234 = length(intersect(s2,intersect(s3,s4))),n1234 = length(intersect(s1,intersect(s2,intersect(s3,s4)))),category =c(set1,set2,set3,set4),fill = c("blue", "red","green","yellow"),cex=2,cat.cex = 1, title = "main")

```




```{r echo = F}


A4V.40FH = row.names(A4V.FDR)[A4V.FDR$AvS40FH < 0.05]
A4V.9MH = row.names(A4V.FDR)[A4V.FDR$AvS9MH < 0.05]

 ##Sample titles as strings. Only fill in up to your number of selected categories
  set1="A4V 40FH"
  set2="A4V 9MH"
  set3="G85R F"
  set4="G85R M"
  
  ##items to be compared (ex: gene names) as a 1 dimensional vectors. Only give inputs up to your number of selected categories
  s1 = A4V.40FH
  s2 = A4V.9MH
  s3 = GRF
  s4 = GRM
  main = 
  
grid.newpage()
tempvenn=draw.quad.venn(area1=length(s1),area2=length(s2),area3=length(s3),area4=length(s4), n12=length(intersect(s1,s2)),n13 = length(intersect(s1,s3)),n14 = length(intersect(s1,s4)),n23 = length(intersect(s2,s3)),n24 = length(intersect(s2,s4)),n34 = length(intersect(s3,s4)),n123 =  length(intersect(s1,intersect(s2,s3))),n124 =  length(intersect(s1,intersect(s2,s4))), n134 = length(intersect(s1,intersect(s3,s4))),n234 = length(intersect(s2,intersect(s3,s4))),n1234 = length(intersect(s1,intersect(s2,intersect(s3,s4)))),category =c(set1,set2,set3,set4),fill = c("blue", "red","green","yellow"),cex=2,cat.cex = 1, title = "main")

```




```{r echo = F, fig.width=10, fig.height=5}

head.list = list(G85RFxWTF = GRF,
                 G85RMxWTM = GRM,
                 A4VF.3HxWTF.3H = A4V.3FH,
                 A4VM.3HxWTM.3H = A4V.3MH,
                 A4VF.9HxWTF.9H = A4V.9FH,
                 A4VM.9HxWTM.9H = A4V.9MH,
                 A4VF.40HxWTF.40H = A4V.40FH)

#upset(fromList(head.list), nsets = 7, nintersects = NA)


combination.matrix = matrix(rep(1, length(names(head.list))))
row.names(combination.matrix) = names(head.list)

n = 6
while(n>0){
  temp = combn(row.names(combination.matrix), n)
  i=1
  while(i<=ncol(temp)){
    combo = combination.matrix[,1]-1
    combo[temp[,i]] = 1
    combination.matrix = cbind(combination.matrix, combo)
    colnames(combination.matrix) = c(1:ncol(combination.matrix))
    i=i+1
  }
  n=n-1
}


gene.list = c(head.list[[1]])
i=1
while(i<8){
  gene.list = c(gene.list, 
              setdiff(head.list[[i]], gene.list))
  i=i+1
}

unique.genes = matrix(rep(0, ncol(combination.matrix) *
                            length(gene.list)), 
                      ncol = ncol(combination.matrix))
row.names(unique.genes) = gene.list

i=1
while(i<=ncol(combination.matrix)){
  combo = row.names(combination.matrix)[combination.matrix[,i]==1]
  common.genes = head.list[[combo[1]]]
  j=2
  while(j<=length(combo)){
    common.genes = intersect(common.genes, head.list[[combo[j]]])
    j=j+1
  }
  unique.genes[common.genes,i] = 1
  i=i+1
}

DEG.symbol = c(rep("", nrow(combination.matrix)+1), GeneIDKey[row.names(unique.genes), "Symbol"])

total.DEGs = apply(unique.genes, MARGIN = 2, sum)
shared.DEGs = rbind(combination.matrix, unique.genes)
shared.DEGs = rbind(total.DEGs, shared.DEGs)

shared.DEGs = cbind(DEG.symbol, shared.DEGs)

##write.csv(shared.DEGs, "/Users/johncsantiago/Desktop/A4VHead-G85R_SharedDEGs.csv")

```


```{r echo = F}


A4V.3FT = row.names(A4V.FDR)[A4V.FDR$AvS3FT < 0.05]
A4V.3MT = row.names(A4V.FDR)[A4V.FDR$AvS3MT < 0.05]

 ##Sample titles as strings. Only fill in up to your number of selected categories
  set1="A4V 3FT"
  set2="A4V 3MT"
  set3="G85R F"
  set4="G85R M"
  
  ##items to be compared (ex: gene names) as a 1 dimensional vectors. Only give inputs up to your number of selected categories
  s1 = A4V.3FT
  s2 = A4V.3MT
  s3 = GRF
  s4 = GRM
  main = 
  
grid.newpage()
tempvenn=draw.quad.venn(area1=length(s1),area2=length(s2),area3=length(s3),area4=length(s4), n12=length(intersect(s1,s2)),n13 = length(intersect(s1,s3)),n14 = length(intersect(s1,s4)),n23 = length(intersect(s2,s3)),n24 = length(intersect(s2,s4)),n34 = length(intersect(s3,s4)),n123 =  length(intersect(s1,intersect(s2,s3))),n124 =  length(intersect(s1,intersect(s2,s4))), n134 = length(intersect(s1,intersect(s3,s4))),n234 = length(intersect(s2,intersect(s3,s4))),n1234 = length(intersect(s1,intersect(s2,intersect(s3,s4)))),category =c(set1,set2,set3,set4),fill = c("blue", "red","green","yellow"),cex=2,cat.cex = 1, title = "main")

```



```{r echo = F}


A4V.9FT = row.names(A4V.FDR)[A4V.FDR$AvS9FT < 0.05]
A4V.9MT = row.names(A4V.FDR)[A4V.FDR$AvS9MT < 0.05]

 ##Sample titles as strings. Only fill in up to your number of selected categories
  set1="A4V 9FT"
  set2="A4V 9MT"
  set3="G85R F"
  set4="G85R M"
  
  ##items to be compared (ex: gene names) as a 1 dimensional vectors. Only give inputs up to your number of selected categories
  s1 = A4V.9FT
  s2 = A4V.9MT
  s3 = GRF
  s4 = GRM
  main = 
  
grid.newpage()
tempvenn=draw.quad.venn(area1=length(s1),area2=length(s2),area3=length(s3),area4=length(s4), n12=length(intersect(s1,s2)),n13 = length(intersect(s1,s3)),n14 = length(intersect(s1,s4)),n23 = length(intersect(s2,s3)),n24 = length(intersect(s2,s4)),n34 = length(intersect(s3,s4)),n123 =  length(intersect(s1,intersect(s2,s3))),n124 =  length(intersect(s1,intersect(s2,s4))), n134 = length(intersect(s1,intersect(s3,s4))),n234 = length(intersect(s2,intersect(s3,s4))),n1234 = length(intersect(s1,intersect(s2,intersect(s3,s4)))),category =c(set1,set2,set3,set4),fill = c("blue", "red","green","yellow"),cex=2,cat.cex = 1, title = "main")

```




```{r echo = F}


A4V.40FT = row.names(A4V.FDR)[A4V.FDR$AvS40FT < 0.05]
A4V.9MT = row.names(A4V.FDR)[A4V.FDR$AvS9MT < 0.05]

 ##Sample titles as strings. Only fill in up to your number of selected categories
  set1="A4V 40FT"
  set2="A4V 9MT"
  set3="G85R F"
  set4="G85R M"
  
  ##items to be compared (ex: gene names) as a 1 dimensional vectors. Only give inputs up to your number of selected categories
  s1 = A4V.40FT
  s2 = A4V.9MT
  s3 = GRF
  s4 = GRM
  main = 
  
grid.newpage()
tempvenn=draw.quad.venn(area1=length(s1),area2=length(s2),area3=length(s3),area4=length(s4), n12=length(intersect(s1,s2)),n13 = length(intersect(s1,s3)),n14 = length(intersect(s1,s4)),n23 = length(intersect(s2,s3)),n24 = length(intersect(s2,s4)),n34 = length(intersect(s3,s4)),n123 =  length(intersect(s1,intersect(s2,s3))),n124 =  length(intersect(s1,intersect(s2,s4))), n134 = length(intersect(s1,intersect(s3,s4))),n234 = length(intersect(s2,intersect(s3,s4))),n1234 = length(intersect(s1,intersect(s2,intersect(s3,s4)))),category =c(set1,set2,set3,set4),fill = c("blue", "red","green","yellow"),cex=2,cat.cex = 1, title = "main")

```




```{r echo = F, fig.width=10, fig.height=5}

thor.list = list(G85RFxWTF = GRF,
                 G85RMxWTM = GRM,
                 A4VF.3TxWTF.3T = A4V.3FT,
                 A4VM.3TxWTM.3T = A4V.3MT,
                 A4VF.9TxWTF.9T = A4V.9FT,
                 A4VM.9TxWTM.9T = A4V.9MT,
                 A4VF.40TxWTF.40T = A4V.40FT)

#upset(fromList(thor.list), nsets = 7, nintersects = NA)


combination.matrix = matrix(rep(1, length(names(thor.list))))
row.names(combination.matrix) = names(thor.list)

n = 6
while(n>0){
  temp = combn(row.names(combination.matrix), n)
  i=1
  while(i<=ncol(temp)){
    combo = combination.matrix[,1]-1
    combo[temp[,i]] = 1
    combination.matrix = cbind(combination.matrix, combo)
    colnames(combination.matrix) = c(1:ncol(combination.matrix))
    i=i+1
  }
  n=n-1
}


gene.list = c(thor.list[[1]])
i=1
while(i<8){
  gene.list = c(gene.list, 
              setdiff(thor.list[[i]], gene.list))
  i=i+1
}

unique.genes = matrix(rep(0, ncol(combination.matrix) *
                            length(gene.list)), 
                      ncol = ncol(combination.matrix))
row.names(unique.genes) = gene.list

i=1
while(i<=ncol(combination.matrix)){
  combo = row.names(combination.matrix)[combination.matrix[,i]==1]
  common.genes = thor.list[[combo[1]]]
  j=2
  while(j<=length(combo)){
    common.genes = intersect(common.genes, thor.list[[combo[j]]])
    j=j+1
  }
  unique.genes[common.genes,i] = 1
  i=i+1
}

DEG.symbol = c(rep("", nrow(combination.matrix)+1), GeneIDKey[row.names(unique.genes), "Symbol"])

total.DEGs = apply(unique.genes, MARGIN = 2, sum)
shared.DEGs = rbind(combination.matrix, unique.genes)
shared.DEGs = rbind(total.DEGs, shared.DEGs)

shared.DEGs = cbind(DEG.symbol, shared.DEGs)


##write.csv(shared.DEGs, "/Users/johncsantiago/Desktop/A4VThorax-G85R_SharedDEGs.csv")

```





```{r echo = F}


A4V.3FA = row.names(A4V.FDR)[A4V.FDR$AvS3FA < 0.05]
A4V.3MA = row.names(A4V.FDR)[A4V.FDR$AvS3MA < 0.05]

 ##Sample titles as strings. Only fill in up to your number of selected categories
  set1="A4V 3FA"
  set2="A4V 3MA"
  set3="G85R F"
  set4="G85R M"
  
  ##items to be compared (ex: gene names) as a 1 dimensional vectors. Only give inputs up to your number of selected categories
  s1 = A4V.3FA
  s2 = A4V.3MA
  s3 = GRF
  s4 = GRM
  main = 
  
grid.newpage()
tempvenn=draw.quad.venn(area1=length(s1),area2=length(s2),area3=length(s3),area4=length(s4), n12=length(intersect(s1,s2)),n13 = length(intersect(s1,s3)),n14 = length(intersect(s1,s4)),n23 = length(intersect(s2,s3)),n24 = length(intersect(s2,s4)),n34 = length(intersect(s3,s4)),n123 =  length(intersect(s1,intersect(s2,s3))),n124 =  length(intersect(s1,intersect(s2,s4))), n134 = length(intersect(s1,intersect(s3,s4))),n234 = length(intersect(s2,intersect(s3,s4))),n1234 = length(intersect(s1,intersect(s2,intersect(s3,s4)))),category =c(set1,set2,set3,set4),fill = c("blue", "red","green","yellow"),cex=2,cat.cex = 1, title = "main")

```



```{r echo = F}


A4V.9FA = row.names(A4V.FDR)[A4V.FDR$AvS9FA < 0.05]
A4V.9MA = row.names(A4V.FDR)[A4V.FDR$AvS9MA < 0.05]

 ##Sample titles as strings. Only fill in up to your number of selected categories
  set1="A4V 9FA"
  set2="A4V 9MA"
  set3="G85R F"
  set4="G85R M"
  
  ##items to be compared (ex: gene names) as a 1 dimensional vectors. Only give inputs up to your number of selected categories
  s1 = A4V.9FA
  s2 = A4V.9MA
  s3 = GRF
  s4 = GRM
  main = 
  
grid.newpage()
tempvenn=draw.quad.venn(area1=length(s1),area2=length(s2),area3=length(s3),area4=length(s4), n12=length(intersect(s1,s2)),n13 = length(intersect(s1,s3)),n14 = length(intersect(s1,s4)),n23 = length(intersect(s2,s3)),n24 = length(intersect(s2,s4)),n34 = length(intersect(s3,s4)),n123 =  length(intersect(s1,intersect(s2,s3))),n124 =  length(intersect(s1,intersect(s2,s4))), n134 = length(intersect(s1,intersect(s3,s4))),n234 = length(intersect(s2,intersect(s3,s4))),n1234 = length(intersect(s1,intersect(s2,intersect(s3,s4)))),category =c(set1,set2,set3,set4),fill = c("blue", "red","green","yellow"),cex=2,cat.cex = 1, title = "main")

```




```{r echo = F}


A4V.40FA = row.names(A4V.FDR)[A4V.FDR$AvS40FA < 0.05]
A4V.9MA = row.names(A4V.FDR)[A4V.FDR$AvS9MA < 0.05]

 ##Sample titles as strings. Only fill in up to your number of selected categories
  set1="A4V 40FA"
  set2="A4V 9MA"
  set3="G85R F"
  set4="G85R M"
  
  ##items to be compared (ex: gene names) as a 1 dimensional vectors. Only give inputs up to your number of selected categories
  s1 = A4V.40FA
  s2 = A4V.9MA
  s3 = GRF
  s4 = GRM
  main = 
  
grid.newpage()
tempvenn=draw.quad.venn(area1=length(s1),area2=length(s2),area3=length(s3),area4=length(s4), n12=length(intersect(s1,s2)),n13 = length(intersect(s1,s3)),n14 = length(intersect(s1,s4)),n23 = length(intersect(s2,s3)),n24 = length(intersect(s2,s4)),n34 = length(intersect(s3,s4)),n123 =  length(intersect(s1,intersect(s2,s3))),n124 =  length(intersect(s1,intersect(s2,s4))), n134 = length(intersect(s1,intersect(s3,s4))),n234 = length(intersect(s2,intersect(s3,s4))),n1234 = length(intersect(s1,intersect(s2,intersect(s3,s4)))),category =c(set1,set2,set3,set4),fill = c("blue", "red","green","yellow"),cex=2,cat.cex = 1, title = "main")

```






```{r echo = F, fig.width=10, fig.height=5}

abdm.list = list(G85RFxWTF = GRF,
                 G85RMxWTM = GRM,
                 A4VF.3AxWTF.3A = A4V.3FA,
                 A4VM.3AxWTM.3A = A4V.3MA,
                 A4VF.9AxWTF.9A = A4V.9FA,
                 A4VM.9AxWTM.9A = A4V.9MA,
                 A4VF.40AxWTF.40A = A4V.40FA)

#upset(fromList(abdm.list), nsets = 7, nintersects = NA)


combination.matrix = matrix(rep(1, length(names(abdm.list))))
row.names(combination.matrix) = names(abdm.list)

n = 6
while(n>0){
  temp = combn(row.names(combination.matrix), n)
  i=1
  while(i<=ncol(temp)){
    combo = combination.matrix[,1]-1
    combo[temp[,i]] = 1
    combination.matrix = cbind(combination.matrix, combo)
    colnames(combination.matrix) = c(1:ncol(combination.matrix))
    i=i+1
  }
  n=n-1
}


gene.list = c(abdm.list[[1]])
i=1
while(i<8){
  gene.list = c(gene.list, 
              setdiff(abdm.list[[i]], gene.list))
  i=i+1
}

unique.genes = matrix(rep(0, ncol(combination.matrix) *
                            length(gene.list)), 
                      ncol = ncol(combination.matrix))
row.names(unique.genes) = gene.list

i=1
while(i<=ncol(combination.matrix)){
  combo = row.names(combination.matrix)[combination.matrix[,i]==1]
  common.genes = abdm.list[[combo[1]]]
  j=2
  while(j<=length(combo)){
    common.genes = intersect(common.genes, abdm.list[[combo[j]]])
    j=j+1
  }
  unique.genes[common.genes,i] = 1
  i=i+1
}

DEG.symbol = c(rep("", nrow(combination.matrix)+1), GeneIDKey[row.names(unique.genes), "Symbol"])

total.DEGs = apply(unique.genes, MARGIN = 2, sum)
shared.DEGs = rbind(combination.matrix, unique.genes)
shared.DEGs = rbind(total.DEGs, shared.DEGs)

shared.DEGs = cbind(DEG.symbol, shared.DEGs)


##write.csv(shared.DEGs, "/Users/johncsantiago/Desktop/A4VAbdomen-G85R_SharedDEGs.csv")

```




```{r echo = F, fig.width=10, fig.height=5}

Day3.list = list(G85RFxWTF = GRF,
                 G85RMxWTM = GRM,
                 A4VF.3HxWTF.3H = A4V.3FH,
                 A4VF.3TxWTF.3T = A4V.3FT,
                 A4VF.3AxWTF.3A = A4V.3FA,
                 A4VM.3HxWTM.3H = A4V.3MH,
                 A4VM.3TxWTM.3T = A4V.3MT,
                 A4VM.3AxWTM.3A = A4V.3MA)

#upset(fromList(abdm.list), nsets = 7, nintersects = NA)

use.list = Day3.list

combination.matrix = matrix(rep(1, length(names(use.list))))
row.names(combination.matrix) = names(use.list)

n = 6
while(n>0){
  temp = combn(row.names(combination.matrix), n)
  i=1
  while(i<=ncol(temp)){
    combo = combination.matrix[,1]-1
    combo[temp[,i]] = 1
    combination.matrix = cbind(combination.matrix, combo)
    colnames(combination.matrix) = c(1:ncol(combination.matrix))
    i=i+1
  }
  n=n-1
}


gene.list = c(use.list[[1]])
i=1
while(i<=length(use.list)){
  gene.list = c(gene.list, 
              setdiff(use.list[[i]], gene.list))
  i=i+1
}

unique.genes = matrix(rep(0, ncol(combination.matrix) *
                            length(gene.list)), 
                      ncol = ncol(combination.matrix))
row.names(unique.genes) = gene.list

i=1
while(i<=ncol(combination.matrix)){
  combo = row.names(combination.matrix)[combination.matrix[,i]==1]
  common.genes = use.list[[combo[1]]]
  j=2
  while(j<=length(combo)){
    common.genes = intersect(common.genes, use.list[[combo[j]]])
    j=j+1
  }
  unique.genes[common.genes,i] = 1
  i=i+1
}

DEG.symbol = c(rep("", nrow(combination.matrix)+1), GeneIDKey[row.names(unique.genes), "Symbol"])

total.DEGs = apply(unique.genes, MARGIN = 2, sum)
shared.DEGs = rbind(combination.matrix, unique.genes)
shared.DEGs = rbind(total.DEGs, shared.DEGs)

shared.DEGs = cbind(DEG.symbol, shared.DEGs)


##write.csv(shared.DEGs, "/Users/johncsantiago/Desktop/A4V3Day-G85R_SharedDEGs.csv")

```





```{r echo = F, fig.width=10, fig.height=5}

Day9.list = list(G85RFxWTF = GRF,
                 G85RMxWTM = GRM,
                 A4VF.9HxWTF.9H = A4V.9FH,
                 A4VF.9TxWTF.9T = A4V.9FT,
                 A4VF.9AxWTF.9A = A4V.9FA,
                 A4VM.9HxWTM.9H = A4V.9MH,
                 A4VM.9TxWTM.9T = A4V.9MT,
                 A4VM.9AxWTM.9A = A4V.9MA)

#upset(fromList(abdm.list), nsets = 7, nintersects = NA)

use.list = Day9.list

combination.matrix = matrix(rep(1, length(names(use.list))))
row.names(combination.matrix) = names(use.list)

n = 6
while(n>0){
  temp = combn(row.names(combination.matrix), n)
  i=1
  while(i<=ncol(temp)){
    combo = combination.matrix[,1]-1
    combo[temp[,i]] = 1
    combination.matrix = cbind(combination.matrix, combo)
    colnames(combination.matrix) = c(1:ncol(combination.matrix))
    i=i+1
  }
  n=n-1
}


gene.list = c(use.list[[1]])
i=1
while(i<=length(use.list)){
  gene.list = c(gene.list, 
              setdiff(use.list[[i]], gene.list))
  i=i+1
}

unique.genes = matrix(rep(0, ncol(combination.matrix) *
                            length(gene.list)), 
                      ncol = ncol(combination.matrix))
row.names(unique.genes) = gene.list

i=1
while(i<=ncol(combination.matrix)){
  combo = row.names(combination.matrix)[combination.matrix[,i]==1]
  common.genes = use.list[[combo[1]]]
  j=2
  while(j<=length(combo)){
    common.genes = intersect(common.genes, use.list[[combo[j]]])
    j=j+1
  }
  unique.genes[common.genes,i] = 1
  i=i+1
}

DEG.symbol = c(rep("", nrow(combination.matrix)+1), GeneIDKey[row.names(unique.genes), "Symbol"])

total.DEGs = apply(unique.genes, MARGIN = 2, sum)
shared.DEGs = rbind(combination.matrix, unique.genes)
shared.DEGs = rbind(total.DEGs, shared.DEGs)

shared.DEGs = cbind(DEG.symbol, shared.DEGs)


##write.csv(shared.DEGs, "/Users/johncsantiago/Desktop/A4V9Day-G85R_SharedDEGs.csv")

```




```{r echo = F, fig.width=10, fig.height=5}

Day40.list = list(G85RFxWTF = GRF,
                 G85RMxWTM = GRM,
                 A4VF.40HxWTF.40H = A4V.40FH,
                 A4VF.40TxWTF.40T = A4V.40FT,
                 A4VF.40AxWTF.40A = A4V.40FA,
                 A4VM.9HxWTM.9H = A4V.9MH,
                 A4VM.9TxWTM.9T = A4V.9MT,
                 A4VM.9AxWTM.9A = A4V.9MA)

#upset(fromList(abdm.list), nsets = 7, nintersects = NA)

use.list = Day40.list

combination.matrix = matrix(rep(1, length(names(use.list))))
row.names(combination.matrix) = names(use.list)

n = 6
while(n>0){
  temp = combn(row.names(combination.matrix), n)
  i=1
  while(i<=ncol(temp)){
    combo = combination.matrix[,1]-1
    combo[temp[,i]] = 1
    combination.matrix = cbind(combination.matrix, combo)
    colnames(combination.matrix) = c(1:ncol(combination.matrix))
    i=i+1
  }
  n=n-1
}


gene.list = c(use.list[[1]])
i=1
while(i<=length(use.list)){
  gene.list = c(gene.list, 
              setdiff(use.list[[i]], gene.list))
  i=i+1
}


unique.genes = matrix(rep(0, ncol(combination.matrix) *
                            length(gene.list)), 
                      ncol = ncol(combination.matrix))
row.names(unique.genes) = gene.list
intersect.genes = unique.genes

i=1
while(i<=ncol(combination.matrix)){
  combo = row.names(combination.matrix)[combination.matrix[,i]==1]
  not.combo = row.names(combination.matrix)[combination.matrix[,i]==0]
  common.genes = use.list[[combo[1]]]
  j=2
  while(j<=length(combo)){
    common.genes = intersect(common.genes, use.list[[combo[j]]])
    j=j+1
  }
  
  not.common.genes = common.genes
  k=length(not.combo)
  while(k>0){
    not.common.genes = setdiff(not.common.genes,
                               use.list[[not.combo[[k]]]])
    k=k-1
  }
  
  
  unique.genes[common.genes,i] = 1
  i=i+1
}


DEG.symbol = c(rep("", nrow(combination.matrix)+1), GeneIDKey[row.names(unique.genes), "Symbol"])

total.DEGs = apply(unique.genes, MARGIN = 2, sum)
shared.DEGs = rbind(combination.matrix, unique.genes)
shared.DEGs = rbind(total.DEGs, shared.DEGs)

shared.DEGs = cbind(DEG.symbol, shared.DEGs)


##write.csv(shared.DEGs, "/Users/johncsantiago/Desktop/A4V40Day-G85R_SharedDEGs.csv")


```
