---
title: "Defficiency Screen Functional Analysis"
author: "John Santiago"
date: "11/28/2020"
output: html_document
---

```{r setup, include=FALSE}
library(rgl)
knitr::opts_chunk$set(echo = FALSE, fig.align="center")
knitr::knit_hooks$set(webgl = hook_webgl)
```

```{r echo = F, include=F}
##Load Libraries

library(biomaRt)
library(org.Dm.eg.db)
library(goseq)
library(GO.db)
library(visNetwork)
library(rrvgo)
library(plotly)
library(KEGGREST)
library(pathview)
##library(RColorBrewer)
```

```{r echo = F, include =F}
##load all files from github
git.dir = "https://raw.githubusercontent.com/johncsantiago/WhartonLab/master/TKT_RNAseq/CountTables/"
cpmdata = read.csv(paste0(git.dir,"TKT_cpmdata.csv"),row.names = 1)
groups  = read.csv(paste0(git.dir,"TKT.metadata.csv"),row.names = 1)
TKT.EdgeR = read.csv(paste0(git.dir,"TKT.EdgeR.Table.csv"),row.names = 1)
GeneIDKey = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/GeneralDataFiles/GeneIDKey.csv", row.names = 1)

##CamiData = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/GeneralDataFiles/Genes by Df Modifier.csv")

##background = setNames(unique(CamiData$Background), unique(CamiData$Background))

##moderate = setNames(rep(0, length(background)), names(background))

##moderate[unique(CamiData$Moderate)] = 1

##strong = setNames(rep(0, length(background)), names(background))

##strong[unique(CamiData$Strong)] = 1

##lethal = setNames(rep(0, length(background)), names(background))

##lethal[unique(CamiData$Lethal)] = 1

##enhancer = setNames(rep(0, length(background)), names(background))

##enhancer[unique(CamiData$Enhancers)] = 1

##no.effect = setNames(rep(0, length(background)), names(background))

##no.effect[unique(CamiData$No.Effect)] = 1



##FB2Ensembl
##x1=as.list(org.Dm.egENSEMBL2EG)
##Ensembl2Symbol
##x2=as.list(org.Dm.egSYMBOL)
##Symbol2Ensembl
##x3=as.list(org.Dm.egSYMBOL2EG)
##Ensembl2FB
##x4=as.list(org.Dm.egENSEMBL)
##ensembl to FBgn
##x5=as.list(org.Dm.egFLYBASE)

##FBgn2ensembl = row.names(CamiData)
##names(FBgn2ensembl) = row.names(CamiData)
##tempEG = unlist(x1[lengths(x1)==1][row.names(CamiData)])
##FBgn2ensembl[names(tempEG)]=tempEG

##ensembl2symbol = row.names(CamiData)
##names(ensembl2symbol) = FBgn2ensembl
##tempSymbol = unlist(x2[FBgn2ensembl])
##ensembl2symbol[names(tempSymbol)]=tempSymbol
##symbol2ensembl = names(ensembl2symbol)
##names(symbol2ensembl) = ensembl2symbol

##write.csv(names(symbol2ensembl)[grep("FBgn", names(symbol2ensembl))], "/Users/johncsantiago/Documents/CamiExtraGenes.csv")

##extras = read.csv("/Users/johncsantiago/Downloads/FlyBase_Symbol_download.csv", row.names = 1)
##ensembl2symbol[row.names(extras)] = extras$SYMBOL


##symbol = ensembl2symbol

##symbol = background

##symbol[intersect(GeneIDKey$FBgn, background)] = 
##  GeneIDKey[intersect(GeneIDKey$FBgn, background), "Symbol"]

##CamiData = data.frame(FBgn       = background[1:14674],
##                      Symbol     = symbol[1:14674],
##                      Moderate   = moderate[1:14674],
##                      Strong     = strong[1:14674],
##                      Lethal     = lethal[1:14674],
##                      Enhancer   = enhancer[1:14674],
##                      No.Effect  = no.effect[1:14674])




##write.csv(CamiData, "/Users/johncsantiago/Documents/GitHub/WhartonLab/GeneralDataFiles/DeficiencyModifierGenes.csv")


Df.data = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/GeneralDataFiles/DeficiencyModifierGenes.csv", row.names = 1)

```

```{r include=F, echo=F}


##write.csv(kegg.names, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/KEGG.names.csv")
kegg.names = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/KEGG.names.csv", row.names = 1)

keggID=keggConv("dme","ncbi-geneid")

kegg = readRDS("/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/kegg.symbol2path.RData")


##sigs = Df.data[Df.data$Strong == 1 | Df.data$Moderate == 1 , "Symbol"]
##genes = setNames(rep(0, nrow(Df.data)), Df.data$Symbol)
##genes[sigs] = 1
##pwf=nullp(genes,"dm3","geneSymbol")
##GO.wall=goseq(pwf,"dm3","geneSymbol")
##GO.wall$adjp=p.adjust(GO.wall$over_represented_pvalue,method="BH")
##row.names(GO.wall) = GO.wall$category
##Repress.GO = GO.wall
##write.csv(Repress.GO, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/RepressorGOAnalysis.csv")

##KEGG term enrichment is KEGG
##KEGG=goseq(pwf,gene2cat=kegg)
##KEGG$adjp=p.adjust(KEGG$over_represented_pvalue,method="BH")
##row.names(KEGG)=substr(as.character(KEGG[,1]),6,13)
##KEGG$Name=kegg.names[row.names(KEGG),1]
##Repress.KEGG = KEGG
##write.csv(Repress.KEGG, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/RepressorKEGGAnalysis.csv")

##sigs = Df.data[Df.data$Moderate == 1 , "Symbol"]
##genes = setNames(rep(0, nrow(Df.data)), Df.data$Symbol)
##genes[sigs] = 1
##pwf=nullp(genes,"dm3","geneSymbol")
##GO.wall=goseq(pwf,"dm3","geneSymbol")
##GO.wall$adjp=p.adjust(GO.wall$over_represented_pvalue,method="BH")
##row.names(GO.wall) = GO.wall$category
##Moderate.GO = GO.wall
##write.csv(Moderate.GO, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/ModerateGOAnalysis.csv")

##KEGG term enrichment is KEGG
##KEGG=goseq(pwf,gene2cat=kegg)
##KEGG$adjp=p.adjust(KEGG$over_represented_pvalue,method="BH")
##row.names(KEGG)=substr(as.character(KEGG[,1]),6,13)
##KEGG$Name=kegg.names[row.names(KEGG),1]
##Moderate.KEGG = KEGG
##write.csv(Moderate.KEGG, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/ModerateKEGGAnalysis.csv")


##sigs = Df.data[Df.data$Strong == 1 , "Symbol"]
##genes = setNames(rep(0, nrow(Df.data)), Df.data$Symbol)
##genes[sigs] = 1
##pwf=nullp(genes,"dm3","geneSymbol")
##GO.wall=goseq(pwf,"dm3","geneSymbol")
##GO.wall$adjp=p.adjust(GO.wall$over_represented_pvalue,method="BH")
##row.names(GO.wall) = GO.wall$category
##Strong.GO = GO.wall
##write.csv(Strong.GO, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/StrongGOAnalysis.csv")

##KEGG term enrichment is KEGG
##KEGG=goseq(pwf,gene2cat=kegg)
##KEGG$adjp=p.adjust(KEGG$over_represented_pvalue,method="BH")
##row.names(KEGG)=substr(as.character(KEGG[,1]),6,13)
##KEGG$Name=kegg.names[row.names(KEGG),1]
##Strong.KEGG = KEGG
##write.csv(Strong.KEGG, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/StrongKEGGAnalysis.csv")

##sigs = Df.data[Df.data$Lethal == 1, "Symbol"]
##genes = setNames(rep(0, nrow(Df.data)), Df.data$Symbol)
##genes[sigs] = 1
##pwf=nullp(genes,"dm3","geneSymbol")
##GO.wall=goseq(pwf,"dm3","geneSymbol")
##GO.wall$adjp=p.adjust(GO.wall$over_represented_pvalue,method="BH")
##row.names(GO.wall) = GO.wall$category
##Lethal.GO = GO.wall
##write.csv(Lethal.GO, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/LethalGOAnalysis.csv")

##KEGG term enrichment is KEGG
##KEGG=goseq(pwf,gene2cat=kegg)
##KEGG$adjp=p.adjust(KEGG$over_represented_pvalue,method="BH")
##row.names(KEGG)=substr(as.character(KEGG[,1]),6,13)
##KEGG$Name=kegg.names[row.names(KEGG),1]
##Lethal.KEGG = KEGG
##write.csv(Lethal.KEGG, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/LethalKEGGAnalysis.csv")

##sigs = Df.data[Df.data$Enhancer == 1, "Symbol"]
##genes = setNames(rep(0, nrow(Df.data)), Df.data$Symbol)
##genes[sigs] = 1
##pwf=nullp(genes,"dm3","geneSymbol")
##GO.wall=goseq(pwf,"dm3","geneSymbol")
##GO.wall$adjp=p.adjust(GO.wall$over_represented_pvalue,method="BH")
##row.names(GO.wall) = GO.wall$category
##Enhance.GO = GO.wall
##write.csv(Enhance.GO, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/EnhancerGOAnalysis.csv")

##KEGG term enrichment is KEGG
##KEGG=goseq(pwf,gene2cat=kegg)
##KEGG$adjp=p.adjust(KEGG$over_represented_pvalue,method="BH")
##row.names(KEGG)=substr(as.character(KEGG[,1]),6,13)
##EGG$Name=kegg.names[row.names(KEGG),1]
##Enhance.KEGG = KEGG
##write.csv(Enhance.KEGG, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/EnhancerKEGGAnalysis.csv")

Moderate.GO = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/ModerateGOAnalysis.csv", row.names = 1)
Strong.GO = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/StrongGOAnalysis.csv", row.names = 1)

Repress.GO = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/RepressorGOAnalysis.csv", row.names = 1)
Lethal.GO = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/LethalGOAnalysis.csv", row.names = 1)
Enhance.GO = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/EnhancerGOAnalysis.csv", row.names = 1)



```


```{r, fig.width= 10}

GO.data = Moderate.GO
GO.data = GO.data[GO.data$ontology == 'BP',
                  c("category", "term","adjp", "numDEInCat", "numInCat")]


data = GO.data[20:1,c("term","adjp","numDEInCat", "numInCat", "category")]
data$Score = -log10(data$adjp)
data$term = factor(data$term, levels = c(unique(data$term)))

m <- list(
  l = 50,
  r = 50,
  b = 100,
  t = 100,
  pad = 4
)

fig <- plot_ly(data, 
               x = ~numDEInCat, y = ~term, 
               type = 'bar',
               name = "term",
               marker = list(colorscale = list(c(0,.5,1), c("brown","gold", "steelblue")),
    reversescale =T,
                             colorbar = list(title = "-log10(FDR)",
                                      len = .8, outlinewidth = 0,
                                      tickformat = ".2f",
                                      tick0 = 0),##, dtick = .01),
                             color = ~Score,
                             line = list(color = "black", width = 1.5)),
    hoverinfo = "text",
    hovertext = paste("Sample:", data$term,
                      "\nGO ID: ", data$category,
                      "\nTotal DE: ", data$numDEInCat,
                      "\nTotal in Cat.: ", data$numInCat,
                      "\nFDR: ", signif(data$adjp, 3))) %>%
    layout(xaxis = list(title = "Number of Genes"),
           yaxis = list(title = ""),
           title = "Top 20 Most Enriched GO Terms",
           margin = m)

fig

```



```{r include=F, echo=F}


go_analysis = GO.data$category[GO.data$adjp <= .05]
scores = setNames(-log10(GO.data$adjp), go_analysis)

simMatrix <- calculateSimMatrix(go_analysis,
                                orgdb="org.Dm.eg.db",
                                ont="BP",
                                method="Rel")

##write.csv(simMatrix, "/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/Repressor.BP.simMatrix.csv")

reducedTerms <- reduceSimMatrix(simMatrix,
                                scores,
                                threshold=0.7,
                                orgdb="org.Dm.eg.db")
##write.csv(reducedTerms,"/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/Repressor.BP.reducedTerms.csv")

##simMatrix = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/Repressor.BP.simMatrix.csv", row.names = 1)
##reducedTerms = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/Deficiency Screen/DataFiles/Repressor.BP.reducedTerms.csv", row.names = 1)

```




```{r fig.height=7, fig.width=10}

heatmapPlot(simMatrix,
            reducedTerms,
            annotateParent=TRUE,
            annotationLabel="parentTerm",
            fontsize=6,
            main = "Repressor Gene Enriched Biological Process GO terms")

```


```{r, fig.align='left', include=F}

scatterPlot(simMatrix, reducedTerms)

```


```{r, fig.width=10}
 use.data   = simMatrix
    pca <- prcomp(t(use.data), scale.=TRUE) 
    pc1=scale(pca$x[,1])
    pc2=scale(pca$x[,2])
    eigs <- pca$sdev^2
    ve=signif(((eigs / sum(eigs))*100)[1:3],4)

    pca.data=data.frame(PC1=pc1,
                        PC2=pc2,
                        sdev=pca$sdev,
                        Percent1=ve[1],
                        Percent2=ve[2],
                        Group = reducedTerms[row.names(use.data), "parentTerm"],
                        Score = reducedTerms[row.names(use.data), "score"],
                        Term = reducedTerms[row.names(use.data), "term"],
                        TotalDE = GO.data[row.names(use.data), "numDEInCat"],
                        Total = GO.data[row.names(use.data), "numInCat"],
                        SigVal = signif(GO.data[row.names(use.data), "adjp"],3))

    pca.data$Group = factor(pca.data$Group, levels = unique(pca.data$Group))
    pca.data$Score = 20*(1+pca.data$Score/mean(pca.data$Score))
    
  fig  = plot_ly(data = pca.data, 
                 x = ~PC1, 
                 y = ~PC2,
                 name = ~Group,
                 type = 'scatter',
                 mode = 'markers',
                 showlegend = T,
                 color = ~Group,
                 ##symbol = ~Group,
                 ##symbols = as.character(seq_along(unique(point.data$Set))),
                 ##colors = c("firebrick","gold","deepskyblue"),
                 marker = list(size = pca.data$Score,
                               line = list(color = "black", width = 1.5)),
                 hoverinfo = "text",
                 hovertext = paste("Sample:", pca.data$Term, 
                                   "\nTotal DE: ", pca.data$TotalDE, 
                                   "\nTotal in Cat.: ", pca.data$Total, 
                                   "\nFDR: ", pca.data$SigVal)) %>%
    layout(xaxis = list(title = paste0("PC1", "(", ve[1], "%)")),
           yaxis = list(title = paste0("PC2", "(", ve[2], "%)")),
           title = "Enriched GO term similarity")
           
  fig
  
```


```{r fig.align='left'}

treemapPlot(reducedTerms)

```




















```{r, include=F, echo=F}
GO2Gene   = read.csv("/Users/johncsantiago/Documents/GitHub/WhartonLab/GeneralDataFiles/GenesInGOTerms.csv", row.names = 1)

ccpar=as.list(GOCCPARENTS)
ccchild=as.list(GOCCCHILDREN)

bppar=as.list(GOBPPARENTS)
bpchild=as.list(GOBPCHILDREN)

mfpar=as.list(GOMFPARENTS)
mfchild=as.list(GOMFCHILDREN)
```

```{r, include=F, echo=F}

compare = "GRM.CxDf"
filter.samples = c("GR.M", "TktDfGR.M")

sigs = row.names(TKT.EdgeR)[TKT.EdgeR[,compare]<=.05]
sigs = sigs[apply(cpmdata[sigs,groups$Group %in% filter.samples], 1, min) > 10]

genes=c(rep(0, nrow(cpmdata)))
names(genes) = row.names(cpmdata)
genes[sigs] = 1
names(genes) = GeneIDKey[names(genes), "Symbol"]

pwf=nullp(genes,"dm3","geneSymbol")

GO.wall=goseq(pwf,"dm3","geneSymbol")
GO.wall$adjp=p.adjust(GO.wall$over_represented_pvalue,method="BH")
row.names(GO.wall) = GO.wall$category

GO.wall$Significant = "not"
GO.wall[GO.wall$adjp <= .05, "Significant"] = "sig"
sigGO = GO.wall[GO.wall$adjp<.05,]


##Biological Processes
bpGO = sigGO[sigGO$ontology == 'BP',]

##parent terms are those directly above in hierarchy
## isa implies a defining relationship; part of implies they contribute to the category

parents = bppar[bpGO$category]

parents = data.frame(from = unlist(parents),
                     label = substring(names(unlist(parents)),12),
                     to = substring(names(unlist(parents)),1,10))

parents = parents[parents$to %in% row.names(GO.wall),]

children = bpchild[bpGO$category]

children = data.frame(from = substring(names(unlist(children)),1,10),
                      label = substring(names(unlist(children)),12),
                      to = unlist(children))

children = children[children$to %in% row.names(GO.wall),]

edges = rbind(parents, children)
edges = edges[edges$label == "isa",]
edges = unique(edges)

edges = edges[GO.wall[edges$to, "numDEInCat"]>0,]

node.id = unique(c(edges$from, edges$to))
node.label = GO.wall[node.id, "term"]
node.group = GO.wall[node.id, "Significant"]
node.value = 100*(GO.wall[node.id, "numDEInCat"]/GO.wall[node.id, "numInCat"])

nodes = data.frame(id = node.id,
                   label = node.label,
                   group = node.group,
                   value = node.value)
```

```{r include=F}

visNetwork(nodes, edges)%>%
  visLayout(hierarchical=F, improvedLayout=T)%>%
  visPhysics(solver="forceAtlas2Based", forceAtlas2Based = list(gravitationalConstant=-70),enabled=T)%>%
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE)%>%
  visEdges(arrows='to')%>%
  visGroups(groupname = "sig", shape = "box", color = list(background = "gold", border="black", groupname="black"),physics=F,font=list(color="black"))%>%
  visGroups(groupname = "not", shape = "dot", color = list(background = "grey", border="black", groupname="black"),physics=T,font=list(color="black"))

```


