---
title: "Defficiency Screen Functional Analysis"
author: "John Santiago"
date: "11/28/2020"
output: html_document
---

```{r setup, include=FALSE}
library(rgl)
knitr::opts_chunk$set(echo = FALSE, fig.align="center")
knitr::knit_hooks$set(webgl = hook_webgl)
```

```{r echo = F, include=F}
##Load Libraries

library(org.Dm.eg.db)
##library(goseq)
library(rrvgo)
library(plotly)
```



```{r echo = F, include =F}
##load all files from github
git.dir = "https://raw.githubusercontent.com/johncsantiago/WhartonLab/master/"
GeneIDKey = read.csv(paste0(git.dir,"GeneralDataFiles/GeneIDKey.csv"),row.names = 1)
Df.data = read.csv(paste0(git.dir,"DeficiencyScreen/DataFiles/DeficiencyModifierGenes.csv"),row.names = 1)
##kegg = readRDS(gzcon(url(paste0(git.dir,"DeficiencyScreen/DataFiles/kegg.symbol2path.RData"))))
##kegg.names = read.csv(paste0(git.dir, "DeficiencyScreen/DataFiles/KEGG.names.csv"), row.names = 1)

Moderate.GO = read.csv(paste0(git.dir, "DeficiencyScreen/DataFiles/ModerateGOAnalysis.csv"), row.names = 1)
Strong.GO = read.csv(paste0(git.dir, "DeficiencyScreen/DataFiles/StrongGOAnalysis.csv"), row.names = 1)
Repress.GO = read.csv(paste0(git.dir, "DeficiencyScreen/DataFiles/RepressorGOAnalysis.csv"), row.names = 1)
Lethal.GO = read.csv(paste0(git.dir, "DeficiencyScreen/DataFiles/LethalGOAnalysis.csv"), row.names = 1)
Enhancer.GO = read.csv(paste0(git.dir, "DeficiencyScreen/DataFiles/EnhancerGOAnalysis.csv"), row.names = 1)

genesingo=as.list(org.Dm.egGO2ALLEGS)

```

```{r echo=F, include=F}

GO.data = Repress.GO
GO.ontology = "BP"

go_analysis = GO.data$category[GO.data$adjp <= .05 & GO.data$ontology == GO.ontology]
scores = setNames(-log10(GO.data$adjp), go_analysis)

simMatrix <- calculateSimMatrix(go_analysis,
                                orgdb="org.Dm.eg.db",
                                ont=GO.ontology,
                                method="Rel")

reducedTerms <- reduceSimMatrix(simMatrix,
                                scores,
                                threshold=0.7,
                                orgdb="org.Dm.eg.db")

Sup.BP.SM = simMatrix
Sup.BP.RT = reducedTerms
Sup.BP.RT$Freq = 1
i=1
while(i<=nrow(Sup.BP.RT)){
  Sup.BP.RT$Freq[i] =  sum(Sup.BP.RT$parentTerm == Sup.BP.RT$parentTerm[i])
  i=i+1
}
Sup.BP.RT = Sup.BP.RT[order(Sup.BP.RT$Freq, decreasing = T),]


GO.ontology = "CC"

go_analysis = GO.data$category[GO.data$adjp <= .05 & GO.data$ontology == GO.ontology]
scores = setNames(-log10(GO.data$adjp), go_analysis)

simMatrix <- calculateSimMatrix(go_analysis,
                                orgdb="org.Dm.eg.db",
                                ont=GO.ontology,
                                method="Rel")

reducedTerms <- reduceSimMatrix(simMatrix,
                                scores,
                                threshold=0.7,
                                orgdb="org.Dm.eg.db")

Sup.CC.SM = simMatrix
Sup.CC.RT = reducedTerms
Sup.CC.RT$Freq = 1
i=1
while(i<=nrow(Sup.CC.RT)){
  Sup.CC.RT$Freq[i] =  sum(Sup.CC.RT$parentTerm == Sup.CC.RT$parentTerm[i])
  i=i+1
}
Sup.CC.RT = Sup.CC.RT[order(Sup.CC.RT$Freq, decreasing = T),]

GO.ontology = "MF"

go_analysis = GO.data$category[GO.data$adjp <= .05 & GO.data$ontology == GO.ontology]
scores = setNames(-log10(GO.data$adjp), go_analysis)

simMatrix <- calculateSimMatrix(go_analysis,
                                orgdb="org.Dm.eg.db",
                                ont=GO.ontology,
                                method="Rel")

reducedTerms <- reduceSimMatrix(simMatrix,
                                scores,
                                threshold=0.7,
                                orgdb="org.Dm.eg.db")

Sup.MF.SM = simMatrix
Sup.MF.RT = reducedTerms
Sup.MF.RT$Freq = 1
i=1
while(i<=nrow(Sup.MF.RT)){
  Sup.MF.RT$Freq[i] =  sum(Sup.MF.RT$parentTerm == Sup.MF.RT$parentTerm[i])
  i=i+1
}
Sup.MF.RT = Sup.MF.RT[order(Sup.MF.RT$Freq, decreasing = T),]

```

```{r echo = F}

sigGO = Repress.GO[c(row.names(Sup.BP.RT), 
                     row.names(Sup.CC.RT), 
                     row.names(Sup.MF.RT)), ]
sigGO = sigGO[row.names(sigGO)!="GO:0032991",]

sigGO = sigGO[, c("category", "term","adjp", "numDEInCat", "numInCat", "ontology")]

sigGO$notInCat = sigGO$numInCat - sigGO$numDEInCat

data = sigGO[nrow(sigGO):1,c("term","adjp","numDEInCat", "numInCat", "category", "ontology", "notInCat")]
data$Score = -log10(data$adjp)
data$term = factor(data$term, levels = c(unique(data$term)))

m <- list(
  l = 100,
  r = 50,
  b = 100,
  t = 100,
  pad = 10
)




fig <- plot_ly(data, 
               x = ~numDEInCat, y = ~term, 
               type = 'bar',
               name = "Candidate Suppressor Genes",
               #marker = list(colorscale = list(c(0,.9,1), c("#EA337F","#FEFF54", "#387EF7"))),
               #marker = list(colorscale = list(c(0,.9,1), c("#C1607E","#EBE3A4", "#419193"))),
               #marker = list(colorscale = list(c(0, .75, 1), c("#E7327F","#FEFE57", "#3A7EF7"))),
               marker = list(colorscale = list(c(0,.9,1), c("brown","gold", "steelblue")),
                             color = ~Score,
                             reversescale = T,
                             colorbar = list(title = "-log10(FDR)",
                                      len = .8, outlinewidth = 0,
                                      tickformat = ".2f",
                                      tick0 = 0, xpad = 10),
                             line = list(color = "black", width = 1.5)),
               
               
                             
    hoverinfo = "text",
    hovertext = paste("Sample:", data$term,
                      "\nGO ID: ", data$category,
                      "\nTotal DE: ", data$numDEInCat,
                      "\nTotal in Cat.: ", data$numInCat,
                      "\nFDR: ", signif(data$adjp, 3)))


fig2 <- fig %>% add_trace(fig, data, x = ~notInCat, y = ~term,
                       type = 'bar',
                       name = "Total Genes",
                       ##colors = rep("lightgrey", nrow(data)),
                       marker = list(color = "lightgrey",line = list(color = "black", width = 1.5), colorbar = F),
               hoverinfo = "text",
               hovertext = "")



fig3 <- fig2 %>% layout(xaxis = list(title = "Number of Genes"),
           yaxis = list(title = ""),
           title = "Suppressor Enriched GO Terms",
           margin = m,
           barmode = 'stack',
           shapes = list(
                         list(type = "rect",
                              fillcolor = "white", 
                              line = list(color = "black", width = 2.5), 
                              opacity = 1,
                              x0 = -30, x1 = -5, xref = "x",
                              y0 = -.5, y1 = 15.5, yref = "y",
                              layer = "below"),
                         list(type = "rect",
                              fillcolor = "white", 
                              line = list(color = "black", width = 2.5), 
                              opacity = 1,
                              x0 = -30, x1 = -5, xref = "x",
                              y0 = 15.5, y1 = 21.5, yref = "y"),
                         list(type = "rect",
                              fillcolor = "white", 
                              line = list(color = "black", width = 2.5), 
                              opacity = 1,
                              x0 = -30, x1 = -5, xref = "x",
                              y0 = 21.5, y1 = 31.5, yref = "y")
                         ))

fig4 <- fig3 %>% add_annotations(x = -17.5,
                        y = 7.5,
                        text = "Molecular Function",
                        showarrow = F,
                        textangle = -90,
                        font = list(size = 15))

fig5 <- fig4 %>% add_annotations(x = -17.5,
                        y = 18.5,
                        text = "Cellular Component",
                        showarrow = F,
                        textangle = -90,
                        font = list(size = 15))

fig6 <- fig5 %>% add_annotations(x = -17.5,
                        y = 27,
                        text = "Biological Process",
                        showarrow = F,
                        textangle = -90,
                        font = list(size = 15))

```


```{r}

treemapPlot(Sup.CC.RT)

```


```{r}

scatterPlot(Sup.CC.SM, Sup.CC.RT)

```

```{r}

treemapPlot(Sup.BP.RT)

```


```{r}

scatterPlot(Sup.BP.SM, Sup.BP.RT)

```


```{r}

treemapPlot(Sup.MF.RT)

```


```{r}

scatterPlot(Sup.MF.SM, Sup.MF.RT)

```


```{r fig.height=12, fig.width=15, fig.align='left'}

fig6

```


```{r include = FALSE}


color.function <- colorRampPalette( c( "steelblue" , "gold", "brown" ) )
order = c(1:17, NA, 18:23, NA, 24:35)
par(mar = c(3,12,1,3))
barplot(height = data$numInCat[order],
        names.arg = data$term[order],
        horiz = T, 
        cex.names = .5,
        xlim = c(0,900),
        axes =F)
barplot(height = data$numDEInCat[order],
        names.arg = "",
        add = T,
        horiz = T,
        col = "gold",
        xlim = c(0,900),
        axes = F)
axis(1, seq(0, 1000, by=100), labels=T, las = 2, cex.axis = .5)
axis(1, seq(0, 1000, by=25), labels=FALSE, tck=-.01)

```

```{r echo=F, include=F}

GO.data = Enhancer.GO
GO.ontology = "BP"

go_analysis = GO.data$category[GO.data$adjp <= .05 & GO.data$ontology == GO.ontology]
scores = setNames(-log10(GO.data$adjp), go_analysis)

simMatrix <- calculateSimMatrix(go_analysis,
                                orgdb="org.Dm.eg.db",
                                ont=GO.ontology,
                                method="Rel")

reducedTerms <- reduceSimMatrix(simMatrix,
                                scores,
                                threshold=0.7,
                                orgdb="org.Dm.eg.db")

Enh.BP.SM = simMatrix
Enh.BP.RT = reducedTerms

Enh.BP.RT$Freq = 1
i=1
while(i<=nrow(Enh.BP.RT)){
  Enh.BP.RT$Freq[i] =  sum(Enh.BP.RT$parentTerm == Enh.BP.RT$parentTerm[i])
  i=i+1
}
Enh.BP.RT = Enh.BP.RT[order(Enh.BP.RT$Freq, decreasing = T),]

GO.ontology = "CC"

go_analysis = GO.data$category[GO.data$adjp <= .05 & GO.data$ontology == GO.ontology]
scores = setNames(-log10(GO.data$adjp), go_analysis)

simMatrix <- calculateSimMatrix(go_analysis,
                                orgdb="org.Dm.eg.db",
                                ont=GO.ontology,
                                method="Rel")

reducedTerms <- reduceSimMatrix(simMatrix,
                                scores,
                                threshold=0.7,
                                orgdb="org.Dm.eg.db")

Enh.CC.SM = simMatrix
Enh.CC.RT = reducedTerms

Enh.CC.RT$Freq = 1
i=1
while(i<=nrow(Enh.CC.RT)){
  Enh.CC.RT$Freq[i] =  sum(Enh.CC.RT$parentTerm == Enh.CC.RT$parentTerm[i])
  i=i+1
}
Enh.CC.RT = Enh.CC.RT[order(Enh.CC.RT$Freq, decreasing = T),]

GO.ontology = "MF"

go_analysis = GO.data$category[GO.data$adjp <= .05 & GO.data$ontology == GO.ontology]
scores = setNames(-log10(GO.data$adjp), go_analysis)

simMatrix <- calculateSimMatrix(go_analysis,
                                orgdb="org.Dm.eg.db",
                                ont=GO.ontology,
                                method="Rel")

reducedTerms <- reduceSimMatrix(simMatrix,
                                scores,
                                threshold=0.7,
                                orgdb="org.Dm.eg.db")

Enh.MF.SM = simMatrix
Enh.MF.RT = reducedTerms

Enh.MF.RT$Freq = 1
i=1
while(i<=nrow(Enh.MF.RT)){
  Enh.MF.RT$Freq[i] =  sum(Enh.MF.RT$parentTerm == Enh.MF.RT$parentTerm[i])
  i=i+1
}
Enh.MF.RT = Enh.MF.RT[order(Enh.MF.RT$Freq, decreasing = T),]

```

```{r echo = F}


sigGO = Enhancer.GO[c(row.names(Enh.BP.RT), 
                     row.names(Enh.CC.RT), 
                     row.names(Enh.MF.RT)), ]

sigGO = sigGO[, c("category", "term","adjp", "numDEInCat", "numInCat", "ontology")]

sigGO$notInCat = sigGO$numInCat - sigGO$numDEInCat

data = sigGO[nrow(sigGO):1,c("term","adjp","numDEInCat", "numInCat", "category", "ontology", "notInCat")]
data$Score = -log10(data$adjp)
data$term = factor(data$term, levels = c(unique(data$term)))

m <- list(
  l = 50,
  r = 50,
  b = 100,
  t = 100,
  pad = 10
)



fig <- plot_ly(data, 
               x = ~numDEInCat, y = ~term, 
               type = 'bar',
               name = "Candidate Enhancer Genes",
               marker = list(colorscale = list(c(0,.9,1), c("brown","gold", "steelblue")),
    reversescale =T,
                             colorbar = list(title = "-log10(FDR)",
                                      len = .8, outlinewidth = 0,
                                      tickformat = ".2f",
                                      tick0 = 0),##, dtick = .01),
                             color = ~Score,
                             line = list(color = "black", width = 1.5)),
    hoverinfo = "text",
    hovertext = paste("Sample:", data$term,
                      "\nGO ID: ", data$category,
                      "\nTotal DE: ", data$numDEInCat,
                      "\nTotal in Cat.: ", data$numInCat,
                      "\nFDR: ", signif(data$adjp, 3)))


fig2 <- fig %>% add_trace(fig, data, x = ~notInCat, y = ~term,
                       type = 'bar',
                       name = "Total Genes",
                       marker = list(color = "lightgrey",line = list(color = "black", width = 1.5), colorbar = F),
               hoverinfo = "text",
               hovertext = "")



fig3 <- fig2 %>% layout(xaxis = list(title = "Number of Genes"),
           yaxis = list(title = ""),
           title = "Enhancer Enriched GO Terms",
           margin = m,
           barmode = 'stack',
           shapes = list(
                         list(type = "rect",
                              fillcolor = "white", 
                              line = list(color = "black", width = 2.5), 
                              opacity = 1,
                              x0 = -10, x1 = -2.5, xref = "x",
                              y0 = -.5, y1 = 2.5, yref = "y",
                              layer = "below"),
                         list(type = "rect",
                              fillcolor = "white", 
                              line = list(color = "black", width = 2.5), 
                              opacity = 1,
                              x0 = -10, x1 = -2.5, xref = "x",
                              y0 = 2.5, y1 = 5.5, yref = "y"),
                         list(type = "rect",
                              fillcolor = "white", 
                              line = list(color = "black", width = 2.5), 
                              opacity = 1,
                              x0 = -10, x1 = -2.5, xref = "x",
                              y0 = 5.5, y1 = 9.5, yref = "y")
                         ))

fig4 <- fig3 %>% add_annotations(x = -6.5,
                        y = 1,
                        text = "Molecular Function",
                        showarrow = F,
                        textangle = -90,
                        font = list(size = 12))

fig5 <- fig4 %>% add_annotations(x = -6.5,
                        y = 4,
                        text = "Cellular Component",
                        showarrow = F,
                        textangle = -90,
                        font = list(size = 12))

fig6 <- fig5 %>% add_annotations(x = -6.5,
                        y = 7.5,
                        text = "Biological Process",
                        showarrow = F,
                        textangle = -90,
                        font = list(size = 12))

```


##All Suppressors
```{r}

treemapPlot(Enh.CC.RT)

```


```{r}

scatterPlot(Enh.CC.SM, Enh.CC.RT)

```

```{r}

treemapPlot(Enh.BP.RT)

```




```{r}

scatterPlot(Enh.BP.SM, Enh.BP.RT)

```


```{r}

treemapPlot(Enh.MF.RT)

```


```{r}

scatterPlot(Enh.MF.SM, Enh.MF.RT)

```

```{r fig.height=8, fig.width=15, fig.align='left'}

fig6

```





#Enhancers
```{r echo=F, include=F}

GO.data = Moderate.GO
GO.ontology = "BP"

go_analysis = GO.data$category[GO.data$adjp <= .05 & GO.data$ontology == GO.ontology]
scores = setNames(-log10(GO.data$adjp), go_analysis)

simMatrix <- calculateSimMatrix(go_analysis,
                                orgdb="org.Dm.eg.db",
                                ont=GO.ontology,
                                method="Rel")

reducedTerms <- reduceSimMatrix(simMatrix,
                                scores,
                                threshold=0.7,
                                orgdb="org.Dm.eg.db")

Mod.BP.SM = simMatrix
Mod.BP.RT = reducedTerms
Mod.BP.RT$Freq = 1
i=1
while(i<=nrow(Mod.BP.RT)){
  Mod.BP.RT$Freq[i] =  sum(Mod.BP.RT$parentTerm == Mod.BP.RT$parentTerm[i])
  i=i+1
}
Mod.BP.RT = Mod.BP.RT[order(Mod.BP.RT$Freq, decreasing = T),]


GO.ontology = "CC"

go_analysis = GO.data$category[GO.data$adjp <= .05 & GO.data$ontology == GO.ontology]
scores = setNames(-log10(GO.data$adjp), go_analysis)

simMatrix <- calculateSimMatrix(go_analysis,
                                orgdb="org.Dm.eg.db",
                                ont=GO.ontology,
                                method="Rel")

reducedTerms <- reduceSimMatrix(simMatrix,
                                scores,
                                threshold=0.7,
                                orgdb="org.Dm.eg.db")

Mod.CC.SM = simMatrix
Mod.CC.RT = reducedTerms
Mod.CC.RT$Freq = 1
i=1
while(i<=nrow(Mod.CC.RT)){
  Mod.CC.RT$Freq[i] =  sum(Mod.CC.RT$parentTerm == Mod.CC.RT$parentTerm[i])
  i=i+1
}
Mod.CC.RT = Mod.CC.RT[order(Mod.CC.RT$Freq, decreasing = T),]

GO.ontology = "MF"

go_analysis = GO.data$category[GO.data$adjp <= .05 & GO.data$ontology == GO.ontology]
scores = setNames(-log10(GO.data$adjp), go_analysis)

simMatrix <- calculateSimMatrix(go_analysis,
                                orgdb="org.Dm.eg.db",
                                ont=GO.ontology,
                                method="Rel")

reducedTerms <- reduceSimMatrix(simMatrix,
                                scores,
                                threshold=0.7,
                                orgdb="org.Dm.eg.db")

Mod.MF.SM = simMatrix
Mod.MF.RT = reducedTerms
Mod.MF.RT$Freq = 1
i=1
while(i<=nrow(Mod.MF.RT)){
  Mod.MF.RT$Freq[i] =  sum(Mod.MF.RT$parentTerm == Mod.MF.RT$parentTerm[i])
  i=i+1
}
Mod.MF.RT = Mod.MF.RT[order(Mod.MF.RT$Freq, decreasing = T),]

```

```{r echo = F}

sigGO = Repress.GO[c(row.names(Mod.BP.RT), 
                     row.names(Mod.CC.RT), 
                     row.names(Mod.MF.RT)), ]
sigGO = sigGO[row.names(sigGO)!="GO:0032991",]

sigGO = sigGO[, c("category", "term","adjp", "numDEInCat", "numInCat", "ontology")]

sigGO$notInCat = sigGO$numInCat - sigGO$numDEInCat

data = sigGO[nrow(sigGO):1,c("term","adjp","numDEInCat", "numInCat", "category", "ontology", "notInCat")]
data$Score = -log10(data$adjp)
data$term = factor(data$term, levels = c(unique(data$term)))

m <- list(
  l = 100,
  r = 50,
  b = 100,
  t = 100,
  pad = 10
)




fig <- plot_ly(data, 
               x = ~numDEInCat, y = ~term, 
               type = 'bar',
               name = "Candidate Modpressor Genes",
               marker = list(colorscale = list(c(0,.9,1), c("brown","gold", "steelblue")),
    reversescale =T,
                             colorbar = list(title = "-log10(FDR)",
                                      len = .8, outlinewidth = 0,
                                      tickformat = ".2f",
                                      tick0 = 0, xpad = 10),
                             color = ~Score,
                             line = list(color = "black", width = 1.5)),
    hoverinfo = "text",
    hovertext = paste("Sample:", data$term,
                      "\nGO ID: ", data$category,
                      "\nTotal DE: ", data$numDEInCat,
                      "\nTotal in Cat.: ", data$numInCat,
                      "\nFDR: ", signif(data$adjp, 3)))


fig2 <- fig %>% add_trace(fig, data, x = ~notInCat, y = ~term,
                       type = 'bar',
                       name = "Total Genes",
                       ##colors = rep("lightgrey", nrow(data)),
                       marker = list(color = "lightgrey",line = list(color = "black", width = 1.5), colorbar = F),
               hoverinfo = "text",
               hovertext = "")



fig3 <- fig2 %>% layout(xaxis = list(title = "Number of Genes"),
           yaxis = list(title = ""),
           title = "Modpressor Enriched GO Terms",
           margin = m,
           barmode = 'stack',
           shapes = list(
                         list(type = "rect",
                              fillcolor = "white", 
                              line = list(color = "black", width = 2.5), 
                              opacity = 1,
                              x0 = -30, x1 = -5, xref = "x",
                              y0 = -.5, y1 = 15.5, yref = "y",
                              layer = "below"),
                         list(type = "rect",
                              fillcolor = "white", 
                              line = list(color = "black", width = 2.5), 
                              opacity = 1,
                              x0 = -30, x1 = -5, xref = "x",
                              y0 = 15.5, y1 = 22.5, yref = "y"),
                         list(type = "rect",
                              fillcolor = "white", 
                              line = list(color = "black", width = 2.5), 
                              opacity = 1,
                              x0 = -30, x1 = -5, xref = "x",
                              y0 = 22.5, y1 = 34.5, yref = "y")
                         ))

fig4 <- fig3 %>% add_annotations(x = -17.5,
                        y = 7.5,
                        text = "Molecular Function",
                        showarrow = F,
                        textangle = -90,
                        font = list(size = 15))

fig5 <- fig4 %>% add_annotations(x = -17.5,
                        y = 19,
                        text = "Cellular Component",
                        showarrow = F,
                        textangle = -90,
                        font = list(size = 15))

fig6 <- fig5 %>% add_annotations(x = -17.5,
                        y = 29,
                        text = "Biological Process",
                        showarrow = F,
                        textangle = -90,
                        font = list(size = 15))

```

#Moderate Suppressors
```{r}

treemapPlot(Mod.CC.RT)

```


```{r}

treemapPlot(Mod.BP.RT)

```


```{r}

treemapPlot(Mod.MF.RT)

```


```{r fig.height=12, fig.width=15, fig.align='left'}

fig6

```


